# -*- coding: utf-8 -*-
T = {}

T['ru'] = {
  "title": "Два телефона — бесплатная радионяня | Руководство",
  "desc": "Как сделать бесплатную радионяню из запасного телефона или старого планшета: как работает радионяня по Wi-Fi, чем она отличается от отдельного устройства и что умеет каждая функция.",
  "kicker": "РУКОВОДСТВО",
  "h1": "Два телефона, одна бесплатная радионяня: всё, что умеет BabyPhone.online",
  "lede": "Не нужно ничего покупать, устанавливать или регистрировать. Откройте сайт на двух устройствах, которые у вас уже есть, — и получите приватную радионяню с живым видео и звуком, дома или в отпуске.",
  "introP": "Обычная радионяня — это ещё один прибор, который нужно купить, заряжать и возить с собой. BabyPhone.online идёт другим путём: ваши устройства сами становятся камерой и монитором прямо в браузере. Ниже — чем это удобно и что делает каждая кнопка.",
  "reuseH": "Дайте старому телефону или планшету вторую жизнь",
  "reuseP": "Телефон, который лежит в ящике с позапрошлого обновления, или планшет, которым дети почти не пользуются, — любой из них станет камерой для малыша. Поставьте его у кроватки, откройте babyphone.online, нажмите «Детский блок» — и он передаёт живое видео и звук на ваш телефон. SIM-карта не нужна: домашнего Wi-Fi достаточно. Настоящая детская камера, без покупок и без выбрасывания.",
  "travelH": "Сделано для отпуска и ночей вне дома",
  "travelP": "Именно здесь это раскрывается лучше всего. В отпуске не хочется везти громоздкую радионяню с её коротким радиусом действия. С BabyPhone.online вы просто берёте два телефона, которые и так с собой: один оставляете в номере или палатке с ребёнком, второй берёте на террасу или в соседнюю комнату. Связь идёт через интернет (Wi-Fi или 4G/5G), поэтому дальность не ограничена стенами одного здания и вы не зависите от сигнала базовой станции. Два телефона — и всё готово, где угодно.",
  "setupH": "Связь меньше чем за минуту",
  "setupP": "Соединение специально сделано простым, чтобы справиться и в три часа ночи спросонья.",
  "steps": [
    "На устройстве рядом с ребёнком нажмите «Детский блок». Появятся код из 6 символов и QR-код.",
    "На своём телефоне нажмите «Родительский блок».",
    "Введите код или отсканируйте QR — и вы сразу видите и слышите ребёнка."
  ],
  "featH": "Все возможности и зачем они нужны",
  "featLede": "Всё управляется с родительского телефона, а детское устройство просто передаёт. Вот полный список.",
  "features": [
    {"n": "Живое видео и звук", "d": "Видите и слышите ребёнка в реальном времени с малой задержкой — в том числе через 4G/5G, не только по домашнему Wi-Fi."},
    {"n": "Обратная связь", "d": "Нажмите и говорите: ваш голос звучит на детском устройстве, и вы можете успокоить малыша, не заходя в комнату."},
    {"n": "Колыбельные и музыка", "d": "Включайте спокойные звуки или свои MP3 на детском устройстве прямо со своего телефона."},
    {"n": "Ночник", "d": "Включите мягкое тёплое свечение на экране детского устройства со своей стороны связи."},
    {"n": "Оповещение о плаче", "d": "Получайте сигнал, когда ребёнок плачет, с чувствительностью, которую вы задаёте сами, плюс журнал событий."},
    {"n": "Таймер сна", "d": "Пусть колыбельная играет и сама остановится через выбранное вами время."},
    {"n": "Только звук и приватный экран", "d": "Оставьте звук и скройте картинку, когда видео не нужно, а слушать хочется."},
    {"n": "Заряд батареи", "d": "Видите уровень заряда детского устройства у себя на экране, чтобы оно не разрядилось незаметно."},
    {"n": "Запись фрагмента", "d": "Сохраните момент с видео и звуком прямо на своё устройство. Ничего никуда не загружается."},
    {"n": "Всегда восстанавливает связь", "d": "Переживает переключение Wi-Fi и мобильной сети, выключение экрана, и сразу сообщает, если связь пропала."},
    {"n": "30 языков", "d": "Весь интерфейс на вашем языке — выберите один раз, и выбор запомнится."},
    {"n": "Бесплатно, без аккаунта", "d": "Основная радионяня бесплатна и не требует регистрации. Откройте сайт и пользуйтесь."}
  ],
  "privacyH": "Приватность по умолчанию",
  "privacyP": "Видео и звук идут напрямую между вашими двумя устройствами, peer-to-peer и в зашифрованном виде. Ничего не записывается, и ни один сервер не подсматривает. Без аккаунта, без рекламы, без слежки — только ваши устройства говорят друг с другом.",
  "worksH": "Работает на устройствах, которые у вас уже есть",
  "worksP": "Подойдёт любой телефон, планшет или ноутбук с современным браузером (Chrome, Safari, Firefox, Edge) — в том числе старые модели, лишь бы браузер был достаточно свежим. Устройству на детской стороне нужны камера и микрофон; оставьте его на зарядке — и оно продержится всю ночь.",
  "wifiH": "Как на самом деле работает радионяня через Wi-Fi",
  "wifiP": "Классическая радионяня — это пара маломощных раций: камера передаёт, родительский блок принимает, а толстая стена обрывает разговор. Радионяня по Wi-Fi отправляет видео и звук как данные через интернет. BabyPhone.online использует WebRTC — ту же технологию, которой ваш браузер пользуется для видеозвонков, — поэтому два устройства открывают прямой зашифрованный канал друг к другу. Код комнаты нужен только для того, чтобы они нашли друг друга в начале, а зашифрованный ретранслятор подключается лишь тогда, когда ваша сеть закрывает прямой путь; ни то, ни другое не может видеть или слышать поток. Практическая разница: дальность перестаёт измеряться в метрах, но оба устройства должны быть в сети.",
  "vsH": "Приложение-радионяня или отдельное устройство?",
  "vsLede": "Однозначного победителя нет — они подводят по-разному. Честное сравнение.",
  "vs": [
    {"n": "Дальность", "d": "Отдельное устройство работает в пределах своего радиуса и вообще не нуждается в интернете. У приложения дальность практически не ограничена, но оба устройства должны быть в сети."},
    {"n": "Цена", "d": "Видеоняня стоит реальных денег и превращается в электронный мусор, когда ребёнок вырастает. Здесь вы не платите ничего и используете технику, которая уже есть."},
    {"n": "Поездки", "d": "База, камера и две зарядки занимают половину сумки. Два телефона, которые вы и так везёте, не занимают ничего."},
    {"n": "Надёжность", "d": "Отдельный прибор делает одно дело, ему не помешают обновление системы или входящий звонок. Телефону нужна забота: держите его на зарядке, экран не давайте гаснуть, лишние приложения закройте."},
    {"n": "Приватность", "d": "Облачные камеры хранят записи на серверах производителя; дешёвые аналоговые няни ловятся приёмником по соседству. Прямая связь избавляет от обоих рисков — но вы сами решаете, кому дать код комнаты."},
    {"n": "Ночное видение", "d": "У специальных устройств есть инфракрасные светодиоды, у телефонной камеры их нет. В полной темноте вы всё услышите, но мало увидите — выручает встроенный ночник."}
  ],
  "faqH": "Частые вопросы",
  "faq": [
    {"n": "Безопасно ли приложение-радионяня?", "d": "Всё зависит от того, куда идёт видео и кто может подключиться. Здесь поток идёт напрямую между вашими двумя устройствами и шифруется в пути, так что нет облачного аккаунта, который можно взломать, и нет записей на чужом сервере. Детский блок не отвечает автоматически: устройство, отсканировавшее QR, несёт одноразовый ключ, а тот, кто ввёл код вручную, должен быть одобрен на экране самого детского блока."},
    {"n": "Работает ли радионяня без Wi-Fi?", "d": "Этой нужен интернет на обоих устройствах — но не обязательно Wi-Fi и не обязательно одна сеть: детское устройство может быть на Wi-Fi, а вы на 4G или 5G. Если интернета нет совсем ни с одной стороны, устройства не найдут друг друга, и классическая радионяня подойдёт лучше."},
    {"n": "Сколько это стоит?", "d": "Нисколько. Все функции бесплатны, платных тарифов и аккаунтов нет, а на сайте нет ни рекламы, ни трекеров."},
    {"n": "Можно ли взять старый телефон?", "d": "Да, в этом и смысл. Подойдёт любой запасной телефон или планшет с камерой, микрофоном и свежим браузером, с SIM-картой или без. Держите его на зарядке — трансляция видео всю ночь съедает батарею."},
    {"n": "Нужно ли что-то устанавливать?", "d": "Нет. Оба устройства просто открывают сайт. Ничего не нужно скачивать, регистрировать и настраивать."},
    {"n": "Сколько человек могут смотреть одновременно?", "d": "Второй зритель может подключиться по тому же коду комнаты, но детский блок сначала спрашивает разрешение на своём экране — так что никто не смотрит без согласия того, кто рядом с ребёнком."}
  ],
  "ctaH": "Попробуйте сегодня вечером",
  "ctaP": "Возьмите два устройства, откройте сайт на обоих и убедитесь, как это быстро.",
  "ctaBtn": "Открыть BabyPhone.online",
  "shotHome": "Откройте сайт на любом устройстве — без установки и без аккаунта.",
  "shotParent": "Родительский блок: живой просмотр с обратной связью, колыбельными, ночником, оповещением о плаче и записью — всё с вашего телефона.",
  "shotBaby": "Детский блок: живая камера, код комнаты и QR для связи, а также управление камерой, микрофоном, режимом «только звук» и приватным экраном.",
  "backToApp": "← Назад в приложение",
  "readTime": "4 мин чтения",
  "updated": "Обновлено в июле 2026",
}

T['uk'] = {
  "title": "Два телефони — безкоштовна радіоняня | Посібник",
  "desc": "Як зробити безкоштовну радіоняню зі запасного телефона чи старого планшета: як працює радіоняня через Wi-Fi, чим вона відрізняється від окремого пристрою і що вміє кожна функція.",
  "kicker": "ПОСІБНИК",
  "h1": "Два телефони, одна безкоштовна радіоняня: усе, що вміє BabyPhone.online",
  "lede": "Нічого не треба купувати, встановлювати чи реєструвати. Відкрийте сайт на двох пристроях, які у вас уже є, — і матимете приватну радіоняню з живим відео та звуком, удома чи у відпустці.",
  "introP": "Звичайна радіоняня — це ще один прилад, який треба купити, заряджати й возити з собою. BabyPhone.online іде іншим шляхом: ваші пристрої самі стають камерою та монітором просто в браузері. Нижче — чим це зручно і що робить кожна кнопка.",
  "reuseH": "Дайте старому телефону чи планшету друге життя",
  "reuseP": "Телефон, що лежить у шухляді ще з позаминулого оновлення, або планшет, яким діти майже не користуються, — будь-який із них стане камерою для малюка. Поставте його біля ліжечка, відкрийте babyphone.online, натисніть «Дитячий блок» — і він передає живе відео та звук на ваш телефон. SIM-картка не потрібна: домашнього Wi-Fi досить. Справжня дитяча камера, без покупок і без викидання.",
  "travelH": "Створено для відпустки та ночей поза домом",
  "travelP": "Саме тут це розкривається найкраще. У відпустці не хочеться везти громіздку радіоняню з її коротким радіусом дії. З BabyPhone.online ви просто берете два телефони, які й так із собою: один лишаєте в номері чи наметі з дитиною, другий берете на терасу або в сусідню кімнату. Зв'язок іде через інтернет (Wi-Fi або 4G/5G), тож дальність не обмежена стінами однієї будівлі й ви не залежите від сигналу базової станції. Два телефони — і все готово, будь-де.",
  "setupH": "З'єднання менш ніж за хвилину",
  "setupP": "З'єднання зроблено навмисне простим, щоб упоратися й о третій ночі спросоння.",
  "steps": [
    "На пристрої біля дитини натисніть «Дитячий блок». З'являться код із 6 символів і QR-код.",
    "На своєму телефоні натисніть «Батьківський блок».",
    "Введіть код або відскануйте QR — і ви одразу бачите та чуєте дитину."
  ],
  "featH": "Усі можливості та навіщо вони",
  "featLede": "Усе керується з батьківського телефона, а дитячий пристрій просто передає. Ось повний перелік.",
  "features": [
    {"n": "Живе відео та звук", "d": "Бачите й чуєте дитину в реальному часі з малою затримкою — зокрема через 4G/5G, не лише домашнім Wi-Fi."},
    {"n": "Зворотний зв'язок", "d": "Натисніть і говоріть: ваш голос лунає на дитячому пристрої, тож ви можете заспокоїти малюка, не заходячи до кімнати."},
    {"n": "Колискові та музика", "d": "Вмикайте спокійні звуки або власні MP3 на дитячому пристрої просто зі свого телефона."},
    {"n": "Нічник", "d": "Увімкніть м'яке тепле світло на екрані дитячого пристрою зі свого боку зв'язку."},
    {"n": "Сповіщення про плач", "d": "Отримуйте сигнал, коли дитина плаче, з чутливістю, яку задаєте самі, плюс журнал подій."},
    {"n": "Таймер сну", "d": "Хай колискова грає і сама зупиниться через обраний вами час."},
    {"n": "Лише звук і приватний екран", "d": "Залиште звук і сховайте зображення, коли відео не потрібне, а слухати хочеться."},
    {"n": "Заряд батареї", "d": "Бачите рівень заряду дитячого пристрою у себе на екрані, щоб він не розрядився непомітно."},
    {"n": "Запис фрагмента", "d": "Збережіть момент із відео та звуком просто на свій пристрій. Нічого нікуди не надсилається."},
    {"n": "Завжди відновлює зв'язок", "d": "Переживає перемикання Wi-Fi і мобільної мережі, вимкнення екрана, і одразу повідомляє, якщо зв'язок зник."},
    {"n": "30 мов", "d": "Увесь інтерфейс вашою мовою — оберіть один раз, і вибір запам'ятається."},
    {"n": "Безкоштовно, без облікового запису", "d": "Основна радіоняня безкоштовна й не потребує реєстрації. Відкрийте сайт і користуйтеся."}
  ],
  "privacyH": "Приватність за задумом",
  "privacyP": "Відео та звук ідуть напряму між вашими двома пристроями, peer-to-peer і в зашифрованому вигляді. Нічого не записується, і жоден сервер не підглядає. Без облікового запису, без реклами, без стеження — лише ваші пристрої говорять один з одним.",
  "worksH": "Працює на пристроях, які у вас уже є",
  "worksP": "Підійде будь-який телефон, планшет чи ноутбук із сучасним браузером (Chrome, Safari, Firefox, Edge) — зокрема старі моделі, аби браузер був досить свіжим. Пристрою на дитячому боці потрібні камера й мікрофон; лишіть його на зарядці — і він протримається цілу ніч.",
  "wifiH": "Як насправді працює радіоняня через Wi-Fi",
  "wifiP": "Класична радіоняня — це пара маломіцних рацій: камера передає, батьківський блок приймає, а товста стіна обриває розмову. Радіоняня через Wi-Fi надсилає відео та звук як дані через інтернет. BabyPhone.online використовує WebRTC — ту саму технологію, якою ваш браузер користується для відеодзвінків, — тож два пристрої відкривають прямий зашифрований канал один до одного. Код кімнати потрібен лише для того, щоб вони знайшли одне одного на початку, а зашифрований ретранслятор долучається тільки тоді, коли ваша мережа закриває прямий шлях; ні той, ні інший не може бачити чи чути потік. Практична різниця: дальність перестає вимірюватися в метрах, але обидва пристрої мають бути в мережі.",
  "vsH": "Застосунок-радіоняня чи окремий пристрій?",
  "vsLede": "Однозначного переможця немає — вони підводять по-різному. Чесне порівняння.",
  "vs": [
    {"n": "Дальність", "d": "Окремий пристрій працює в межах свого радіуса й узагалі не потребує інтернету. У застосунку дальність практично необмежена, але обидва пристрої мають бути в мережі."},
    {"n": "Ціна", "d": "Відеоняня коштує реальних грошей і стає електронним сміттям, коли дитина виростає. Тут ви не платите нічого й використовуєте техніку, яка вже є."},
    {"n": "Подорожі", "d": "База, камера й дві зарядки займають пів сумки. Два телефони, які ви й так везете, не займають нічого."},
    {"n": "Надійність", "d": "Окремий прилад робить одну справу, йому не завадять оновлення системи чи вхідний дзвінок. Телефону потрібна турбота: тримайте його на зарядці, не давайте екрану гаснути, зайві застосунки закрийте."},
    {"n": "Приватність", "d": "Хмарні камери зберігають записи на серверах виробника; дешеві аналогові няні ловляться приймачем по сусідству. Прямий зв'язок позбавляє обох ризиків — але ви самі вирішуєте, кому дати код кімнати."},
    {"n": "Нічне бачення", "d": "У спеціальних пристроїв є інфрачервоні світлодіоди, у телефонної камери їх немає. У повній темряві ви все почуєте, але мало побачите — виручає вбудований нічник."}
  ],
  "faqH": "Часті запитання",
  "faq": [
    {"n": "Чи безпечний застосунок-радіоняня?", "d": "Усе залежить від того, куди йде відео і хто може під'єднатися. Тут потік іде напряму між вашими двома пристроями й шифрується в дорозі, тож немає хмарного облікового запису, який можна зламати, і немає записів на чужому сервері. Дитячий блок не відповідає автоматично: пристрій, що відсканував QR, несе одноразовий ключ, а той, хто ввів код вручну, має бути схвалений на екрані самого дитячого блоку."},
    {"n": "Чи працює радіоняня без Wi-Fi?", "d": "Цій потрібен інтернет на обох пристроях — але не обов'язково Wi-Fi і не обов'язково одна мережа: дитячий пристрій може бути на Wi-Fi, а ви на 4G чи 5G. Якщо інтернету немає зовсім із жодного боку, пристрої не знайдуть одне одного, і класична радіоняня підійде краще."},
    {"n": "Скільки це коштує?", "d": "Нічого. Усі функції безкоштовні, платних тарифів і облікових записів немає, а на сайті немає ані реклами, ані трекерів."},
    {"n": "Чи можна взяти старий телефон?", "d": "Так, у цьому й суть. Підійде будь-який запасний телефон або планшет із камерою, мікрофоном і свіжим браузером, із SIM-карткою чи без. Тримайте його на зарядці — трансляція відео цілу ніч з'їдає батарею."},
    {"n": "Чи треба щось встановлювати?", "d": "Ні. Обидва пристрої просто відкривають сайт. Нічого не треба завантажувати, реєструвати й налаштовувати."},
    {"n": "Скільки людей можуть дивитися одночасно?", "d": "Другий глядач може під'єднатися за тим самим кодом кімнати, але дитячий блок спершу питає дозволу на своєму екрані — тож ніхто не дивиться без згоди того, хто поруч із дитиною."}
  ],
  "ctaH": "Спробуйте сьогодні ввечері",
  "ctaP": "Візьміть два пристрої, відкрийте сайт на обох і переконайтеся, як це швидко.",
  "ctaBtn": "Відкрити BabyPhone.online",
  "shotHome": "Відкрийте сайт на будь-якому пристрої — без встановлення та без облікового запису.",
  "shotParent": "Батьківський блок: живий перегляд зі зворотним зв'язком, колисковими, нічником, сповіщенням про плач і записом — усе з вашого телефона.",
  "shotBaby": "Дитячий блок: жива камера, код кімнати та QR для з'єднання, а також керування камерою, мікрофоном, режимом «лише звук» і приватним екраном.",
  "backToApp": "← Назад до застосунку",
  "readTime": "4 хв читання",
  "updated": "Оновлено в липні 2026",
}

T['pl'] = {
  "title": "Dwa telefony jako darmowa niania elektroniczna | Poradnik",
  "desc": "Jak zrobić darmową nianię elektroniczną z zapasowego telefonu lub starego tabletu: jak działa niania przez Wi-Fi, czym różni się od osobnego urządzenia i co potrafi każda funkcja.",
  "kicker": "PORADNIK",
  "h1": "Dwa telefony, jedna darmowa niania: wszystko, co potrafi BabyPhone.online",
  "lede": "Nic nie trzeba kupować, instalować ani zakładać konta. Otwórz stronę na dwóch urządzeniach, które już masz, a otrzymasz prywatną nianię z obrazem i dźwiękiem na żywo — w domu i na wakacjach.",
  "introP": "Zwykła niania elektroniczna to kolejny sprzęt do kupienia, ładowania i pakowania. BabyPhone.online idzie inną drogą: twoje własne urządzenia stają się kamerą i odbiornikiem, wprost w przeglądarce. Poniżej wyjaśniamy, dlaczego to takie wygodne — i co robi każdy przycisk.",
  "reuseH": "Daj staremu telefonowi lub tabletowi drugie życie",
  "reuseP": "Telefon leżący w szufladzie od dwóch wymian albo tablet, z którego dzieci prawie nie korzystają — każdy z nich stanie się kamerą przy łóżeczku. Oprzyj go przy łóżeczku, otwórz babyphone.online, dotknij „Jednostka dziecka”, a będzie przesyłał obraz i dźwięk na twój telefon. Karta SIM nie jest potrzebna: wystarczy domowe Wi-Fi. Prawdziwa kamera niemowlęca, bez kupowania i bez wyrzucania czegokolwiek.",
  "travelH": "Stworzone na wakacje i noce poza domem",
  "travelP": "Właśnie tu sprawdza się najlepiej. Na wakacjach nie chcesz pakować sporej niani z jej krótkim zasięgiem. Z BabyPhone.online używasz po prostu dwóch telefonów, które i tak masz przy sobie: jeden zostawiasz w pokoju hotelowym albo namiocie przy dziecku, drugi bierzesz na taras lub do sąsiedniego pokoju. Połączenie idzie przez internet (Wi-Fi albo 4G/5G), więc zasięg nie kończy się na ścianach jednego budynku i nie zależysz od sygnału stacji bazowej. Dwa telefony i gotowe — gdziekolwiek jesteś.",
  "setupH": "Połączenie w niecałą minutę",
  "setupP": "Parowanie jest celowo proste, żeby dało się je wykonać o trzeciej w nocy, na wpół śpiąc.",
  "steps": [
    "Na urządzeniu przy dziecku dotknij „Jednostka dziecka”. Pokaże 6-znakowy kod i kod QR.",
    "Na swoim telefonie dotknij „Jednostka rodzica”.",
    "Wpisz kod albo zeskanuj QR — od razu widzisz i słyszysz dziecko."
  ],
  "featH": "Każda funkcja i do czego służy",
  "featLede": "Wszystkim sterujesz z telefonu rodzica, a urządzenie przy dziecku po prostu nadaje. Oto pełna lista.",
  "features": [
    {"n": "Obraz i dźwięk na żywo", "d": "Widzisz i słyszysz dziecko w czasie rzeczywistym, z małym opóźnieniem — także przez 4G/5G, nie tylko przez domowe Wi-Fi."},
    {"n": "Mów do dziecka", "d": "Dotknij i mów: twój głos rozlega się na urządzeniu przy dziecku, więc możesz je uspokoić bez wchodzenia do pokoju."},
    {"n": "Kołysanki i muzyka", "d": "Włącz kojące dźwięki albo własne pliki MP3 na urządzeniu przy dziecku, prosto ze swojego telefonu."},
    {"n": "Lampka nocna", "d": "Włącz miękką, ciepłą poświatę na ekranie urządzenia przy dziecku ze swojej strony połączenia."},
    {"n": "Alarm płaczu", "d": "Otrzymuj powiadomienie, gdy dziecko płacze, z czułością, którą sam ustawiasz, plus dziennik zdarzeń."},
    {"n": "Wyłącznik czasowy", "d": "Niech kołysanka gra i sama się zatrzyma po wybranym przez ciebie czasie."},
    {"n": "Tylko dźwięk i zasłona prywatności", "d": "Zostaw dźwięk, a ukryj obraz, kiedy wideo jest zbędne, ale chcesz słuchać."},
    {"n": "Stan baterii", "d": "Widzisz poziom baterii urządzenia przy dziecku na swoim ekranie, więc nigdy nie rozładuje się niezauważenie."},
    {"n": "Nagraj fragment", "d": "Zapisz moment z obrazem i dźwiękiem prosto na swoje urządzenie. Nic nie jest nigdzie wysyłane."},
    {"n": "Zawsze wraca do połączenia", "d": "Przetrwa przełączenie Wi-Fi i sieci komórkowej oraz wygaszenie ekranu, a o zerwaniu łącza powiadomi natychmiast."},
    {"n": "30 języków", "d": "Cały interfejs w twoim języku — wybierz raz, a wybór zostanie zapamiętany."},
    {"n": "Za darmo, bez konta", "d": "Podstawowa niania jest bezpłatna i nie wymaga rejestracji. Otwórz stronę i korzystaj."}
  ],
  "privacyH": "Prywatność z założenia",
  "privacyP": "Obraz i dźwięk idą bezpośrednio między twoimi dwoma urządzeniami, peer-to-peer i zaszyfrowane w drodze. Nic nie jest nagrywane i żaden serwer nie podgląda. Bez konta, bez reklam, bez śledzenia — po prostu twoje urządzenia rozmawiają ze sobą.",
  "worksH": "Działa na urządzeniach, które już masz",
  "worksP": "Wystarczy dowolny telefon, tablet lub laptop z nowszą przeglądarką (Chrome, Safari, Firefox, Edge) — także starsze modele, o ile przeglądarka jest w miarę aktualna. Urządzenie po stronie dziecka potrzebuje kamery i mikrofonu; zostaw je na ładowarce, a wytrzyma całą noc.",
  "wifiH": "Jak naprawdę działa niania elektroniczna przez Wi-Fi",
  "wifiP": "Klasyczna niania to para krótkozasięgowych radiotelefonów: kamera nadaje, odbiornik rodzica odbiera, a gruba ściana kończy rozmowę. Niania przez Wi-Fi wysyła obraz i dźwięk jako dane przez internet. BabyPhone.online używa WebRTC — tej samej technologii, której przeglądarka używa do rozmów wideo — więc oba urządzenia otwierają bezpośrednie, szyfrowane łącze między sobą. Kod pokoju służy tylko do tego, żeby odnalazły się na początku, a szyfrowany przekaźnik wkracza wyłącznie wtedy, gdy twoja sieć blokuje drogę bezpośrednią; żadne z nich nie widzi ani nie słyszy strumienia. Praktyczna różnica: zasięgu nie mierzy się już w metrach, ale oba urządzenia muszą być w sieci.",
  "vsH": "Aplikacja-niania czy osobne urządzenie?",
  "vsLede": "Żadne nie wygrywa jednoznacznie — zawodzą na różne sposoby. Uczciwe porównanie.",
  "vs": [
    {"n": "Zasięg", "d": "Osobne urządzenie działa wszędzie w zasięgu swojego radia i w ogóle nie potrzebuje internetu. Aplikacja ma praktycznie nieograniczony zasięg, ale oba urządzenia muszą być online."},
    {"n": "Koszt", "d": "Niania z obrazem kosztuje realne pieniądze i staje się elektrośmieciem, gdy dziecko z niej wyrośnie. To nie kosztuje nic i wykorzystuje sprzęt, który już masz."},
    {"n": "Podróże", "d": "Stacja bazowa, kamera i dwie ładowarki zajmują pół torby. Dwa telefony, które i tak wieziesz, nie zajmują nic."},
    {"n": "Niezawodność", "d": "Osobne urządzenie robi jedną rzecz, nie przeszkodzi mu aktualizacja systemu ani przychodzące połączenie. Telefon wymaga uwagi: trzymaj go na ładowarce, nie pozwól wygasić ekranu, zamknij inne aplikacje."},
    {"n": "Prywatność", "d": "Kamery chmurowe trzymają nagrania na serwerach producenta; tanie nianie analogowe może przechwycić odbiornik w pobliżu. Połączenie bezpośrednie omija oba problemy — ale to ty decydujesz, kto dostanie kod pokoju."},
    {"n": "Widzenie w nocy", "d": "Osobne urządzenia mają diody podczerwieni, aparat telefonu tego nie potrafi. W zupełnie ciemnym pokoju wszystko usłyszysz, a zobaczysz niewiele — pomaga wbudowana lampka nocna."}
  ],
  "faqH": "Najczęstsze pytania",
  "faq": [
    {"n": "Czy aplikacja-niania jest bezpieczna?", "d": "To zależy, dokąd trafia obraz i kto może dołączyć. Tutaj strumień biegnie prosto między twoimi dwoma urządzeniami i jest szyfrowany w drodze, więc nie ma konta w chmurze, które można włamać, ani nagrań na cudzym serwerze. Jednostka dziecka też nie odbiera automatycznie: urządzenie, które zeskanowało kod QR, niesie jednorazowy klucz, a każdy, kto wpisał kod ręcznie, musi zostać zatwierdzony na ekranie samej jednostki dziecka."},
    {"n": "Czy niania działa bez Wi-Fi?", "d": "Ta potrzebuje internetu na obu urządzeniach — ale niekoniecznie Wi-Fi i niekoniecznie tej samej sieci: urządzenie przy dziecku może być na Wi-Fi, a ty na 4G lub 5G. Gdy po żadnej stronie nie ma internetu, urządzenia się nie odnajdą i lepszym narzędziem będzie klasyczna niania radiowa."},
    {"n": "Ile to kosztuje?", "d": "Nic. Wszystkie funkcje są bezpłatne, nie ma wersji płatnej ani konta, a strona nie zawiera reklam ani skryptów śledzących."},
    {"n": "Czy mogę użyć starego telefonu?", "d": "Tak, i o to właśnie chodzi. Wystarczy dowolny zapasowy telefon lub tablet z kamerą, mikrofonem i aktualną przeglądarką, z kartą SIM albo bez. Trzymaj go podłączony do ładowarki — nadawanie obrazu przez całą noc wyczerpuje baterię."},
    {"n": "Czy muszę coś instalować?", "d": "Nie. Oba urządzenia po prostu otwierają stronę. Nie ma czego pobierać, gdzie się rejestrować ani czego konfigurować."},
    {"n": "Ile osób może patrzeć naraz?", "d": "Drugi widz może dołączyć tym samym kodem pokoju, ale jednostka dziecka najpierw pyta o zgodę na własnym ekranie — więc nikt nie patrzy bez zgody kogoś, kto jest w pokoju."}
  ],
  "ctaH": "Wypróbuj dziś wieczorem",
  "ctaP": "Weź dwa urządzenia, otwórz stronę na obu i przekonaj się, jak to szybko idzie.",
  "ctaBtn": "Otwórz BabyPhone.online",
  "shotHome": "Otwórz stronę na dowolnym urządzeniu — bez instalacji, bez konta.",
  "shotParent": "Jednostka rodzica: podgląd na żywo z mówieniem do dziecka, kołysankami, lampką nocną, alarmem płaczu i nagrywaniem — wszystko z twojego telefonu.",
  "shotBaby": "Jednostka dziecka: kamera na żywo, kod pokoju i QR do sparowania, a także sterowanie kamerą, mikrofonem, trybem tylko dźwięku i zasłoną prywatności.",
  "backToApp": "← Powrót do aplikacji",
  "readTime": "4 min czytania",
  "updated": "Zaktualizowano w lipcu 2026",
}
