# -*- coding: utf-8 -*-
T = {}

T['tr'] = {
  "title": "İki telefonu ücretsiz bebek telsizine dönüştürün | Rehber",
  "desc": "Yedek bir telefondan veya eski bir tabletten nasıl ücretsiz bebek telsizi yapılır: Wi-Fi üzerinden bebek telsizi nasıl çalışır, özel cihazlarla farkı nedir ve her özellik ne işe yarar.",
  "kicker": "REHBER",
  "h1": "İki telefon, bir ücretsiz bebek telsizi: BabyPhone.online'ın yapabildiği her şey",
  "lede": "Satın alınacak kutu, kurulacak uygulama, açılacak hesap yok. Zaten sahip olduğunuz iki cihazda siteyi açın; evde de tatilde de canlı görüntü ve sesle özel bir bebek telsiziniz olsun.",
  "introP": "Geleneksel bebek telsizi, satın alınacak, şarj edilecek ve valize konacak bir cihaz daha demek. BabyPhone.online başka bir yol izliyor: elinizdeki cihazları doğrudan tarayıcıda kameraya ve monitöre dönüştürüyor. İşte bunun neden bu kadar pratik olduğu — ve her düğmenin ne yaptığı.",
  "reuseH": "Eski telefona ya da tablete ikinci bir hayat verin",
  "reuseP": "İki model önceki çekmecede duran telefon ya da çocukların pek kullanmadığı tablet — ikisi de bebek kamerası olabilir. Beşiğin yanına yerleştirin, babyphone.online'ı açın, „Bebek ünitesi\"ne dokunun; canlı görüntü ve sesi kendi telefonunuza yayınlasın. SIM kart gerekmez: ev Wi-Fi'si yeter. Hiçbir şey satın almadan — ve atmadan — gerçek bir bebek kamerası.",
  "travelH": "Tatiller ve evden uzak geceler için",
  "travelP": "Asıl burada parlıyor. Tatilde kısa menzilli, hantal bir telsizi yanınızda taşımak istemezsiniz. BabyPhone.online ile zaten yanınızda olan iki telefonu kullanırsınız: birini otel odasında ya da çadırda bebeğin yanında bırakır, diğerini terasa veya yan odaya götürürsünüz. Bağlantı internet üzerinden (Wi-Fi ya da 4G/5G) gittiği için menzil tek bir binayla sınırlı kalmaz ve baz istasyonu sinyaline bağlı olmazsınız. İki telefon yeter — nerede olursanız olun.",
  "setupH": "Bir dakikadan kısa sürede bağlanın",
  "setupP": "Eşleştirme bilerek basit tutuldu; gecenin üçünde yarı uykulu haldeyken de yapabilesiniz diye.",
  "steps": [
    "Bebeğin yanındaki cihazda „Bebek ünitesi\"ne dokunun. 6 karakterlik bir kod ve bir QR kod gösterir.",
    "Kendi telefonunuzda „Ebeveyn ünitesi\"ne dokunun.",
    "Kodu yazın ya da QR'ı okutun — bebeğinizi anında görür ve duyarsınız."
  ],
  "featH": "Her özellik ve ne işe yaradığı",
  "featLede": "Her şey ebeveyn telefonundan yönetilir; bebek cihazı yalnızca yayın yapar. İşte tam liste.",
  "features": [
    {"n": "Canlı görüntü ve ses", "d": "Bebeğinizi gerçek zamanlı, düşük gecikmeyle görün ve duyun — yalnızca ev Wi-Fi'sinde değil, 4G/5G üzerinden de."},
    {"n": "Karşılık verme", "d": "Dokunun ve konuşun: sesiniz bebek cihazından duyulur, odaya girmeden sakinleştirebilirsiniz."},
    {"n": "Ninniler ve müzik", "d": "Sakinleştirici sesleri ya da kendi MP3'lerinizi bebek cihazında, doğrudan telefonunuzdan çalın."},
    {"n": "Gece lambası", "d": "Bağlantının kendi tarafınızdan, bebek cihazının ekranında yumuşak ve sıcak bir ışık yakın."},
    {"n": "Ağlama uyarısı", "d": "Bebeğiniz ağladığında, kendi belirlediğiniz hassasiyetle uyarı alın; olay günlüğü de var."},
    {"n": "Uyku zamanlayıcı", "d": "Ninni çalsın, seçtiğiniz sürenin sonunda kendiliğinden dursun."},
    {"n": "Yalnızca ses ve gizlilik perdesi", "d": "Görüntüyü kapatıp kulağınız açık kalsın istediğinizde sesi tutun, resmi gizleyin."},
    {"n": "Pil durumu", "d": "Bebek cihazının pil seviyesini kendi ekranınızda görün; fark edilmeden bitmesin."},
    {"n": "Klip kaydet", "d": "Görüntülü ve sesli bir anı doğrudan kendi cihazınıza kaydedin. Hiçbir yere yüklenmez."},
    {"n": "Her zaman yeniden bağlanır", "d": "Wi-Fi/mobil geçişlerini ve ekran kapanmalarını atlatır, bağlantı koptuğu anda sizi uyarır."},
    {"n": "30 dil", "d": "Tüm arayüz kendi dilinizde — bir kez seçin, hatırlansın."},
    {"n": "Ücretsiz, hesapsız", "d": "Temel telsiz ücretsizdir ve kayıt gerektirmez. Siteyi açın ve başlayın."}
  ],
  "privacyH": "Tasarımdan gelen gizlilik",
  "privacyP": "Görüntü ve ses doğrudan iki cihazınız arasında, uçtan uca eşler arası ve yolda şifrelenmiş olarak gider. Hiçbir şey kaydedilmez ve hiçbir sunucu izleyemez. Hesap yok, reklam yok, takip yok — sadece kendi cihazlarınız birbiriyle konuşuyor.",
  "worksH": "Zaten sahip olduğunuz cihazlarda çalışır",
  "worksP": "Güncel bir tarayıcısı (Chrome, Safari, Firefox, Edge) olan her telefon, tablet ya da dizüstü bilgisayar işe yarar — tarayıcı makul ölçüde güncel olduğu sürece eski modeller dahil. Bebek tarafındaki cihazın kamerası ve mikrofonu olmalı; şarjda bırakın, bütün gece yeter.",
  "wifiH": "Wi-Fi üzerinden bebek telsizi gerçekte nasıl çalışır",
  "wifiP": "Klasik bebek telsizi kısa menzilli bir çift telsizdir: kamera ünitesi yayın yapar, ebeveyn ünitesi alır ve kalın bir duvar konuşmayı bitirir. Wi-Fi üzerinden çalışan telsiz ise görüntü ve sesi internet üzerinden veri olarak gönderir. BabyPhone.online, tarayıcınızın görüntülü aramalarda kullandığı teknoloji olan WebRTC'yi kullanır; böylece iki cihaz birbirine doğrudan, şifreli bir bağlantı açar. Oda kodu yalnızca başlangıçta birbirlerini bulmalarına yarar, şifreli bir aktarıcı ise sadece ağınız doğrudan yolu kapattığında devreye girer; ikisi de yayını görebilir ya da duyabilir değildir. Pratik fark şu: menzil artık metreyle ölçülmez, ama iki cihazın da çevrimiçi olması gerekir.",
  "vsH": "Bebek telsizi uygulaması mı, özel cihaz mı?",
  "vsLede": "Hiçbiri kesin üstün değil — farklı şekillerde yetersiz kalıyorlar. Dürüst bir karşılaştırma.",
  "vs": [
    {"n": "Menzil", "d": "Özel bir cihaz kendi telsiz menzili içinde her yerde çalışır ve internete hiç ihtiyaç duymaz. Uygulamanın menzili pratikte sınırsızdır, ama iki cihaz da çevrimiçi olmalıdır."},
    {"n": "Maliyet", "d": "Görüntülü telsiz gerçek para eder ve çocuk büyüyünce elektronik atığa dönüşür. Bu hiçbir şeye mal olmaz ve zaten sahip olduğunuz donanımı yeniden değerlendirir."},
    {"n": "Seyahat", "d": "Bir ana ünite, bir kamera ve iki şarj aleti çantanın yarısını doldurur. Zaten taşıdığınız iki telefon hiç yer kaplamaz."},
    {"n": "Güvenilirlik", "d": "Özel cihaz tek bir iş yapar; araya işletim sistemi güncellemesi ya da gelen çağrı girmez. Telefon ise ilgi ister: şarjda tutun, ekranı uyanık bırakın, diğer uygulamaları kapatın."},
    {"n": "Gizlilik", "d": "Bulut kameraları görüntüleri üreticinin sunucularında tutar; ucuz analog telsizler yakındaki bir alıcı tarafından yakalanabilir. Eşler arası bağlantı ikisinden de kaçınır — ama oda kodunu kimin alacağına siz karar verirsiniz."},
    {"n": "Gece görüşü", "d": "Özel cihazlarda kızılötesi ledler bulunur; telefon kamerası bunu yapamaz. Zifiri karanlık bir odada her şeyi duyar, az şey görürsünüz — yerleşik gece lambası işe yarar."}
  ],
  "faqH": "Sık sorulan sorular",
  "faq": [
    {"n": "Bebek telsizi uygulaması güvenli mi?", "d": "Görüntünün nereye gittiğine ve kimin katılabildiğine bağlı. Burada yayın doğrudan iki cihazınız arasında akar ve yolda şifrelenir; yani kırılacak bir bulut hesabı ve başkasının sunucusunda duran bir kayıt yoktur. Bebek ünitesi de kendiliğinden yanıt vermez: QR'ı okutan cihaz tek kullanımlık bir anahtar taşır, kodu elle yazan kişinin ise bebek cihazının kendi ekranında onaylanması gerekir."},
    {"n": "Bebek telsizi Wi-Fi olmadan çalışır mı?", "d": "Bunun iki cihazda da internete ihtiyacı var — ama özellikle Wi-Fi'ye değil ve aynı ağa da değil: bebek cihazı Wi-Fi'de olabilirken siz 4G ya da 5G'de olabilirsiniz. İki tarafta da hiç internet yoksa cihazlar birbirini bulamaz; o durumda klasik telsiz daha doğru araçtır."},
    {"n": "Maliyeti ne kadar?", "d": "Hiç. Bütün özellikler ücretsiz, ücretli bir sürüm ve hesap yok, sitede reklam ve takip kodu da yok."},
    {"n": "Eski bir telefon kullanabilir miyim?", "d": "Evet, zaten fikir bu. Kamerası, mikrofonu ve güncel bir tarayıcısı olan her yedek telefon ya da tablet olur; SIM kartlı da olur, kartsız da. Fişte bırakın — bütün gece video yayınlamak pili bitirir."},
    {"n": "Bir şey kurmam gerekiyor mu?", "d": "Hayır. İki cihaz da sadece web sitesini açar. İndirilecek, kaydolunacak ya da ayarlanacak hiçbir şey yok."},
    {"n": "Aynı anda kaç kişi izleyebilir?", "d": "İkinci bir izleyici aynı oda koduyla katılabilir, ama bebek ünitesi önce kendi ekranında onay ister — yani odadaki biri kabul etmeden kimse izlemez."}
  ],
  "ctaH": "Bu akşam deneyin",
  "ctaP": "İki cihaz alın, ikisinde de siteyi açın ve ne kadar hızlı olduğunu görün.",
  "ctaBtn": "BabyPhone.online'ı aç",
  "shotHome": "Siteyi herhangi bir cihazda açın — kurulum yok, hesap yok.",
  "shotParent": "Ebeveyn ünitesi: karşılık verme, ninniler, gece lambası, ağlama uyarısı ve kayıtla canlı görüntü — hepsi telefonunuzdan.",
  "shotBaby": "Bebek ünitesi: canlı kamera, oda kodu ve eşleştirme için QR; kamera, mikrofon, yalnızca ses ve gizlilik perdesi denetimleriyle.",
  "backToApp": "← Uygulamaya dön",
  "readTime": "4 dk okuma",
  "updated": "Temmuz 2026'da güncellendi",
}

T['id'] = {
  "title": "Ubah dua ponsel jadi baby monitor gratis | Panduan",
  "desc": "Cara membuat baby monitor gratis dari ponsel cadangan atau tablet lama: bagaimana baby monitor lewat Wi-Fi bekerja, bedanya dengan perangkat khusus, dan penjelasan setiap fitur.",
  "kicker": "PANDUAN",
  "h1": "Dua ponsel, satu baby monitor gratis: semua yang bisa dilakukan BabyPhone.online",
  "lede": "Tidak ada kotak yang harus dibeli, aplikasi yang harus dipasang, atau akun yang harus dibuat. Buka situsnya di dua perangkat yang sudah Anda miliki, dan Anda punya baby monitor pribadi dengan video dan suara langsung — di rumah maupun saat liburan.",
  "introP": "Baby monitor tradisional adalah satu lagi barang yang harus dibeli, diisi daya, dan dibawa. BabyPhone.online mengambil jalan berbeda: perangkat yang sudah Anda punya menjadi kamera dan monitornya, langsung di peramban. Berikut alasan mengapa itu praktis — dan apa fungsi setiap tombolnya.",
  "reuseH": "Beri ponsel atau tablet lama kehidupan kedua",
  "reuseP": "Ponsel di laci sisa dua kali ganti perangkat, atau tablet yang jarang dipakai anak-anak — keduanya bisa jadi kamera bayi. Sandarkan di dekat boks bayi, buka babyphone.online, ketuk „Unit bayi\", dan ia menyiarkan video serta suara langsung ke ponsel Anda. Tanpa kartu SIM: Wi-Fi rumah sudah cukup. Kamera bayi sungguhan, tanpa membeli — atau membuang — apa pun.",
  "travelH": "Dibuat untuk liburan dan malam di luar rumah",
  "travelP": "Di sinilah keunggulannya terasa. Saat liburan Anda tidak ingin membawa monitor besar dengan sinyal jarak pendeknya. Dengan BabyPhone.online Anda cukup memakai dua ponsel yang memang sudah dibawa: satu ditinggal di kamar hotel atau tenda bersama bayi, satunya Anda bawa ke teras atau kamar sebelah. Karena koneksinya lewat internet (Wi-Fi atau 4G/5G), jangkauannya tidak terbatas pada satu bangunan dan Anda tidak bergantung pada sinyal stasiun induk. Dua ponsel, dan beres — di mana pun.",
  "setupH": "Terhubung dalam waktu kurang dari satu menit",
  "setupP": "Pemasangannya sengaja dibuat sederhana, supaya bisa dilakukan sambil setengah mengantuk pukul tiga pagi.",
  "steps": [
    "Di perangkat dekat bayi, ketuk „Unit bayi\". Akan muncul kode 6 karakter dan sebuah kode QR.",
    "Di ponsel Anda sendiri, ketuk „Unit orang tua\".",
    "Ketik kodenya atau pindai QR — Anda langsung melihat dan mendengar bayi Anda."
  ],
  "featH": "Setiap fitur dan gunanya",
  "featLede": "Semua dikendalikan dari ponsel orang tua, sementara perangkat bayi hanya menyiarkan. Ini daftar lengkapnya.",
  "features": [
    {"n": "Video & suara langsung", "d": "Lihat dan dengar bayi Anda secara real-time dengan jeda kecil — juga lewat 4G/5G, bukan hanya Wi-Fi rumah."},
    {"n": "Bicara balik", "d": "Ketuk lalu bicara: suara Anda terdengar di perangkat bayi, jadi Anda bisa menenangkan tanpa masuk kamar."},
    {"n": "Nina bobo & musik", "d": "Putar suara yang menenangkan atau MP3 Anda sendiri di perangkat bayi, langsung dari ponsel."},
    {"n": "Lampu malam", "d": "Nyalakan cahaya hangat yang lembut di layar perangkat bayi dari sisi Anda."},
    {"n": "Peringatan tangis", "d": "Dapatkan peringatan saat bayi menangis, dengan kepekaan yang Anda atur sendiri, plus catatan kejadian."},
    {"n": "Pengatur waktu tidur", "d": "Biarkan nina bobo berputar, lalu berhenti sendiri setelah waktu yang Anda pilih."},
    {"n": "Hanya suara & tirai privasi", "d": "Pertahankan suara tetapi sembunyikan gambar saat video tidak perlu tetapi telinga tetap ingin mendengar."},
    {"n": "Status baterai", "d": "Lihat level baterai perangkat bayi di layar Anda, supaya tidak mati tanpa disadari."},
    {"n": "Rekam klip", "d": "Simpan momen video dan suara langsung ke perangkat Anda sendiri. Tidak ada yang diunggah."},
    {"n": "Selalu tersambung lagi", "d": "Bertahan saat berpindah Wi-Fi/seluler dan saat layar mati, serta memberi tahu Anda begitu sambungan putus."},
    {"n": "30 bahasa", "d": "Seluruh antarmuka dalam bahasa Anda — pilih sekali dan akan diingat."},
    {"n": "Gratis, tanpa akun", "d": "Monitor intinya gratis dan tanpa pendaftaran. Buka situsnya dan langsung pakai."}
  ],
  "privacyH": "Privat sejak dirancang",
  "privacyP": "Video dan suara berjalan langsung antara dua perangkat Anda, dari perangkat ke perangkat dan terenkripsi di perjalanan. Tidak ada yang direkam, dan tidak ada server yang bisa ikut menonton. Tanpa akun, tanpa iklan, tanpa pelacakan — hanya perangkat Anda sendiri yang saling berbicara.",
  "worksH": "Berjalan di perangkat yang sudah Anda miliki",
  "worksP": "Ponsel, tablet, atau laptop apa pun dengan peramban yang cukup baru (Chrome, Safari, Firefox, Edge) bisa dipakai — termasuk model lama, selama peramban cukup mutakhir. Perangkat di sisi bayi perlu kamera dan mikrofon; biarkan tercolok ke pengisi daya dan ia siap semalaman.",
  "wifiH": "Bagaimana sebenarnya baby monitor lewat Wi-Fi bekerja",
  "wifiP": "Baby monitor klasik adalah sepasang radio jarak pendek: unit kamera memancar, unit orang tua menerima, dan tembok tebal mengakhiri percakapan. Baby monitor Wi-Fi mengirim video dan suara sebagai data lewat internet. BabyPhone.online memakai WebRTC — teknologi yang sama yang dipakai peramban Anda untuk panggilan video — sehingga kedua perangkat membuka jalur langsung dan terenkripsi satu sama lain. Kode ruang hanya membantu keduanya saling menemukan di awal, dan relai terenkripsi baru ikut campur ketika jaringan Anda menghalangi jalur langsung; keduanya tidak bisa melihat atau mendengar aliran itu. Bedanya dalam praktik: jangkauan tidak lagi diukur dalam meter, tetapi kedua perangkat harus daring.",
  "vsH": "Aplikasi baby monitor atau perangkat khusus?",
  "vsLede": "Tidak ada yang menang mutlak — keduanya gagal dengan cara berbeda. Perbandingan yang jujur.",
  "vs": [
    {"n": "Jangkauan", "d": "Perangkat khusus bekerja di mana saja dalam jangkauan radionya dan sama sekali tidak perlu internet. Aplikasi praktis tanpa batas jarak, tetapi kedua perangkat harus daring."},
    {"n": "Biaya", "d": "Monitor video berbiaya nyata dan menjadi limbah elektronik ketika anak sudah besar. Ini tidak berbiaya dan memanfaatkan perangkat yang sudah Anda punya."},
    {"n": "Bepergian", "d": "Stasiun induk, kamera, dan dua pengisi daya memenuhi separuh tas. Dua ponsel yang memang Anda bawa tidak memakan tempat sama sekali."},
    {"n": "Keandalan", "d": "Perangkat khusus mengerjakan satu tugas, tanpa gangguan pembaruan sistem atau telepon masuk. Ponsel butuh perhatian: biarkan mengisi daya, layar tetap menyala, aplikasi lain ditutup."},
    {"n": "Privasi", "d": "Kamera awan menyimpan rekaman di server produsen; monitor analog murah bisa ditangkap penerima di dekatnya. Sambungan langsung antar-perangkat menghindari keduanya — tetapi Andalah yang menentukan siapa mendapat kode ruang."},
    {"n": "Penglihatan malam", "d": "Perangkat khusus punya LED inframerah; kamera ponsel tidak bisa. Di kamar yang gelap gulita Anda akan mendengar segalanya dan melihat sedikit — lampu malam bawaan membantu."}
  ],
  "faqH": "Pertanyaan yang sering diajukan",
  "faq": [
    {"n": "Apakah aplikasi baby monitor aman?", "d": "Tergantung ke mana videonya pergi dan siapa yang bisa bergabung. Di sini aliran berjalan langsung antara dua perangkat Anda dan terenkripsi di perjalanan, jadi tidak ada akun awan yang bisa dibobol dan tidak ada rekaman di server orang lain. Unit bayi juga tidak menjawab otomatis: perangkat yang memindai QR membawa kunci sekali pakai, dan siapa pun yang mengetik kode secara manual harus disetujui di layar perangkat bayi sendiri."},
    {"n": "Apakah baby monitor bisa jalan tanpa Wi-Fi?", "d": "Yang ini perlu internet di kedua perangkat — tetapi tidak harus Wi-Fi, dan tidak harus jaringan yang sama: perangkat bayi bisa di Wi-Fi sementara Anda di 4G atau 5G. Kalau sama sekali tidak ada internet di kedua sisi, kedua perangkat tidak bisa saling menemukan, dan monitor radio klasik adalah pilihan yang lebih tepat."},
    {"n": "Berapa biayanya?", "d": "Tidak ada. Semua fitur gratis, tidak ada versi berbayar dan tidak ada akun, serta situsnya tanpa iklan dan tanpa pelacak."},
    {"n": "Bisakah saya memakai ponsel lama?", "d": "Bisa, dan memang itu idenya. Ponsel atau tablet cadangan apa pun dengan kamera, mikrofon, dan peramban mutakhir sudah cukup, dengan atau tanpa kartu SIM. Biarkan tetap tercolok — menyiarkan video semalaman menguras baterai."},
    {"n": "Apakah saya perlu memasang sesuatu?", "d": "Tidak. Kedua perangkat cukup membuka situsnya. Tidak ada yang perlu diunduh, didaftarkan, atau dikonfigurasi."},
    {"n": "Berapa orang bisa menonton bersamaan?", "d": "Penonton kedua bisa bergabung dengan kode ruang yang sama, tetapi unit bayi lebih dulu meminta persetujuan di layarnya sendiri — jadi tidak ada yang menonton tanpa persetujuan seseorang di ruangan itu."}
  ],
  "ctaH": "Coba malam ini",
  "ctaP": "Ambil dua perangkat, buka situsnya di keduanya, dan lihat betapa cepatnya.",
  "ctaBtn": "Buka BabyPhone.online",
  "shotHome": "Buka situsnya di perangkat apa pun — tanpa pemasangan, tanpa akun.",
  "shotParent": "Unit orang tua: tampilan langsung dengan bicara balik, nina bobo, lampu malam, peringatan tangis, dan perekaman — semua dari ponsel Anda.",
  "shotBaby": "Unit bayi: kamera langsung, kode ruang dan QR untuk memasangkan, dengan kendali kamera, mikrofon, mode hanya suara, dan tirai privasi.",
  "backToApp": "← Kembali ke aplikasi",
  "readTime": "Baca 4 menit",
  "updated": "Diperbarui Juli 2026",
}

T['vi'] = {
  "title": "Biến hai điện thoại thành máy theo dõi em bé miễn phí | Hướng dẫn",
  "desc": "Cách tạo máy theo dõi em bé miễn phí từ điện thoại dự phòng hay máy tính bảng cũ: máy theo dõi qua Wi-Fi hoạt động ra sao, khác gì thiết bị chuyên dụng, và từng tính năng dùng để làm gì.",
  "kicker": "HƯỚNG DẪN",
  "h1": "Hai điện thoại, một máy theo dõi em bé miễn phí: tất cả những gì BabyPhone.online làm được",
  "lede": "Không phải mua hộp thiết bị, không phải cài ứng dụng, không cần tài khoản. Mở trang web trên hai thiết bị bạn đã có, và bạn có ngay một máy theo dõi riêng tư với hình ảnh và âm thanh trực tiếp — ở nhà hay khi đi nghỉ.",
  "introP": "Máy theo dõi truyền thống là thêm một món đồ phải mua, phải sạc và phải mang theo. BabyPhone.online chọn hướng khác: chính những thiết bị bạn đang có trở thành camera và màn hình theo dõi, ngay trong trình duyệt. Dưới đây là lý do vì sao điều đó tiện — và mỗi nút bấm làm gì.",
  "reuseH": "Cho điện thoại hay máy tính bảng cũ một đời sống thứ hai",
  "reuseP": "Chiếc điện thoại nằm trong ngăn kéo từ hai lần đổi máy trước, hay chiếc máy tính bảng bọn trẻ ít dùng — cái nào cũng thành camera cho bé được. Dựng nó cạnh cũi, mở babyphone.online, chạm „Thiết bị bé\", và nó truyền hình ảnh cùng âm thanh trực tiếp sang điện thoại của bạn. Không cần SIM: Wi-Fi ở nhà là đủ. Một camera cho bé thực thụ, mà không phải mua — hay vứt bỏ — thứ gì.",
  "travelH": "Sinh ra cho kỳ nghỉ và những đêm xa nhà",
  "travelP": "Đây mới là lúc nó tỏa sáng. Đi nghỉ, bạn đâu muốn mang theo một chiếc máy cồng kềnh với sóng ngắn của riêng nó. Với BabyPhone.online, bạn chỉ dùng hai chiếc điện thoại vốn đã mang theo: một chiếc để lại trong phòng khách sạn hay lều cùng bé, chiếc kia mang ra ban công hoặc phòng bên. Vì kết nối chạy qua Internet (Wi-Fi hoặc 4G/5G), phạm vi không bị giới hạn trong một tòa nhà và bạn không lệ thuộc vào sóng của trạm phát. Hai chiếc điện thoại, thế là xong — ở bất cứ đâu.",
  "setupH": "Kết nối trong chưa đầy một phút",
  "setupP": "Việc ghép đôi được làm cho thật đơn giản, để bạn vẫn làm được lúc ba giờ sáng khi còn ngái ngủ.",
  "steps": [
    "Trên thiết bị đặt cạnh bé, chạm „Thiết bị bé\". Máy hiện một mã 6 ký tự và một mã QR.",
    "Trên điện thoại của bạn, chạm „Thiết bị bố mẹ\".",
    "Nhập mã hoặc quét QR — bạn thấy và nghe được bé ngay lập tức."
  ],
  "featH": "Mọi tính năng và công dụng của chúng",
  "featLede": "Mọi thứ điều khiển từ điện thoại của bố mẹ, còn thiết bị ở chỗ bé chỉ việc truyền. Đây là danh sách đầy đủ.",
  "features": [
    {"n": "Hình ảnh & âm thanh trực tiếp", "d": "Thấy và nghe bé theo thời gian thực, độ trễ thấp — kể cả qua 4G/5G chứ không chỉ Wi-Fi ở nhà."},
    {"n": "Nói lại với bé", "d": "Chạm và nói: giọng bạn phát ra ở thiết bị của bé, nên bạn dỗ bé mà không cần bước vào phòng."},
    {"n": "Hát ru & nhạc", "d": "Phát âm thanh êm dịu hoặc file MP3 của riêng bạn trên thiết bị của bé, ngay từ điện thoại."},
    {"n": "Đèn ngủ", "d": "Bật ánh sáng ấm dịu trên màn hình thiết bị của bé, từ phía bạn."},
    {"n": "Báo bé khóc", "d": "Nhận cảnh báo khi bé khóc, với độ nhạy do bạn tự đặt, kèm nhật ký sự kiện."},
    {"n": "Hẹn giờ ngủ", "d": "Để bài hát ru phát rồi tự dừng sau khoảng thời gian bạn chọn."},
    {"n": "Chỉ âm thanh & màn che riêng tư", "d": "Giữ tiếng nhưng ẩn hình, những lúc bạn muốn tắt hình mà vẫn nghe."},
    {"n": "Tình trạng pin", "d": "Thấy mức pin của thiết bị bên bé ngay trên màn hình của bạn, để nó không hết pin mà bạn không hay."},
    {"n": "Ghi một đoạn", "d": "Lưu một khoảnh khắc có hình và tiếng thẳng vào thiết bị của bạn. Không có gì được tải lên đâu cả."},
    {"n": "Luôn kết nối lại", "d": "Vượt qua việc chuyển Wi-Fi/di động và tắt màn hình, và báo cho bạn ngay khi kết nối rớt."},
    {"n": "30 ngôn ngữ", "d": "Toàn bộ giao diện bằng tiếng của bạn — chọn một lần là được ghi nhớ."},
    {"n": "Miễn phí, không tài khoản", "d": "Chức năng theo dõi cốt lõi miễn phí và không cần đăng ký. Mở trang web rồi dùng thôi."}
  ],
  "privacyH": "Riêng tư từ trong thiết kế",
  "privacyP": "Hình ảnh và âm thanh đi thẳng giữa hai thiết bị của bạn, trực tiếp giữa hai máy và được mã hóa trên đường truyền. Không có gì được ghi lại, và không máy chủ nào xem cùng. Không tài khoản, không quảng cáo, không theo dõi — chỉ có thiết bị của bạn trò chuyện với nhau.",
  "worksH": "Chạy trên chính những thiết bị bạn đang có",
  "worksP": "Bất kỳ điện thoại, máy tính bảng hay laptop nào có trình duyệt đời mới (Chrome, Safari, Firefox, Edge) đều dùng được — kể cả máy cũ, miễn là trình duyệt còn tương đối mới. Thiết bị phía bé cần camera và micrô; cứ cắm sạc là đủ dùng cả đêm.",
  "wifiH": "Máy theo dõi em bé qua Wi-Fi thật ra hoạt động thế nào",
  "wifiP": "Máy theo dõi cổ điển là một cặp bộ đàm tầm ngắn: bộ camera phát, bộ của bố mẹ thu, và một bức tường dày là kết thúc câu chuyện. Máy theo dõi qua Wi-Fi thì gửi hình và tiếng dưới dạng dữ liệu qua Internet. BabyPhone.online dùng WebRTC — đúng công nghệ mà trình duyệt của bạn dùng cho cuộc gọi video — nên hai thiết bị mở một đường truyền trực tiếp, được mã hóa, tới nhau. Mã phòng chỉ giúp chúng tìm thấy nhau lúc ban đầu, còn máy chủ trung chuyển được mã hóa chỉ vào cuộc khi mạng của bạn chặn đường trực tiếp; cả hai đều không thể xem hay nghe luồng dữ liệu. Khác biệt thực tế: phạm vi không còn đo bằng mét nữa, nhưng cả hai thiết bị đều phải trực tuyến.",
  "vsH": "Ứng dụng theo dõi hay máy chuyên dụng?",
  "vsLede": "Không cái nào thắng tuyệt đối — chúng hỏng theo những cách khác nhau. Một so sánh thẳng thắn.",
  "vs": [
    {"n": "Phạm vi", "d": "Máy chuyên dụng chạy trong tầm sóng của nó và hoàn toàn không cần Internet. Ứng dụng thì gần như không giới hạn khoảng cách, nhưng cả hai thiết bị đều phải trực tuyến."},
    {"n": "Chi phí", "d": "Máy theo dõi có hình tốn tiền thật và thành rác điện tử khi con lớn. Cái này không tốn gì và tận dụng thiết bị bạn đã có."},
    {"n": "Đi lại", "d": "Một trạm gốc, một camera và hai củ sạc chiếm nửa cái túi. Hai chiếc điện thoại vốn đã mang theo thì chẳng chiếm chỗ nào."},
    {"n": "Độ tin cậy", "d": "Máy chuyên dụng chỉ làm một việc, không bị bản cập nhật hệ điều hành hay cuộc gọi đến chen ngang. Điện thoại thì cần chăm: cắm sạc, giữ màn hình sáng, đóng các ứng dụng khác."},
    {"n": "Riêng tư", "d": "Camera đám mây giữ hình ảnh trên máy chủ của hãng; máy analog rẻ tiền có thể bị một đầu thu gần đó bắt sóng. Kết nối trực tiếp giữa hai máy tránh được cả hai — nhưng bạn là người quyết định ai được biết mã phòng."},
    {"n": "Nhìn đêm", "d": "Máy chuyên dụng có đèn LED hồng ngoại; camera điện thoại thì không. Trong phòng tối om bạn sẽ nghe được mọi thứ mà thấy rất ít — đèn ngủ tích hợp giúp ích ở đây."}
  ],
  "faqH": "Câu hỏi thường gặp",
  "faq": [
    {"n": "Ứng dụng theo dõi em bé có an toàn không?", "d": "Còn tùy video đi đâu và ai có thể tham gia. Ở đây luồng chạy thẳng giữa hai thiết bị của bạn và được mã hóa trên đường truyền, nên không có tài khoản đám mây nào để bị đột nhập và không có đoạn hình nào nằm trên máy chủ của người khác. Thiết bị bé cũng không tự động trả lời: máy đã quét QR mang theo một khóa dùng một lần, còn ai nhập mã bằng tay thì phải được phê duyệt ngay trên màn hình của thiết bị bé."},
    {"n": "Máy theo dõi có chạy được khi không có Wi-Fi không?", "d": "Cái này cần Internet ở cả hai thiết bị — nhưng không nhất thiết là Wi-Fi, và cũng không cần cùng một mạng: thiết bị của bé có thể dùng Wi-Fi trong khi bạn dùng 4G hay 5G. Nếu cả hai bên đều không có Internet thì hai máy không tìm thấy nhau, và lúc đó máy vô tuyến cổ điển là lựa chọn hợp lý hơn."},
    {"n": "Chi phí bao nhiêu?", "d": "Không đồng nào. Mọi tính năng đều miễn phí, không có gói trả tiền và không cần tài khoản, trang web cũng không có quảng cáo hay mã theo dõi."},
    {"n": "Tôi dùng điện thoại cũ được không?", "d": "Được, và đó chính là ý tưởng. Bất kỳ điện thoại hay máy tính bảng dự phòng nào có camera, micrô và trình duyệt còn được cập nhật đều dùng được, có SIM hay không cũng vậy. Nhớ cắm sạc — truyền video cả đêm sẽ làm cạn pin."},
    {"n": "Tôi có phải cài gì không?", "d": "Không. Hai thiết bị chỉ việc mở trang web. Không có gì để tải, không phải đăng ký và không phải thiết lập gì."},
    {"n": "Cùng lúc bao nhiêu người xem được?", "d": "Người xem thứ hai có thể vào bằng cùng mã phòng, nhưng thiết bị bé sẽ hỏi phê duyệt trên màn hình của nó trước — nên không ai xem được nếu người trong phòng không đồng ý."}
  ],
  "ctaH": "Thử ngay tối nay",
  "ctaP": "Lấy hai thiết bị, mở trang web trên cả hai, và xem nó nhanh đến mức nào.",
  "ctaBtn": "Mở BabyPhone.online",
  "shotHome": "Mở trang web trên bất kỳ thiết bị nào — không cài đặt, không tài khoản.",
  "shotParent": "Thiết bị bố mẹ: xem trực tiếp kèm nói lại với bé, hát ru, đèn ngủ, báo bé khóc và ghi hình — tất cả từ điện thoại của bạn.",
  "shotBaby": "Thiết bị bé: camera trực tiếp, mã phòng và QR để ghép đôi, cùng các nút điều khiển camera, micrô, chế độ chỉ âm thanh và màn che riêng tư.",
  "backToApp": "← Quay lại ứng dụng",
  "readTime": "Đọc 4 phút",
  "updated": "Cập nhật tháng 7 năm 2026",
}
