# -*- coding: utf-8 -*-
T = {}

T['pa'] = {
  "title": "ਦੋ ਫ਼ੋਨਾਂ ਤੋਂ ਮੁਫ਼ਤ ਬੇਬੀ ਮਾਨੀਟਰ | ਗਾਈਡ",
  "desc": "ਵਾਧੂ ਫ਼ੋਨ ਜਾਂ ਪੁਰਾਣੇ ਟੈਬਲੇਟ ਤੋਂ ਮੁਫ਼ਤ ਬੇਬੀ ਮਾਨੀਟਰ ਕਿਵੇਂ ਬਣਾਈਏ: ਵਾਈ-ਫਾਈ ਵਾਲਾ ਬੇਬੀ ਮਾਨੀਟਰ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ, ਵੱਖਰੇ ਯੰਤਰ ਨਾਲੋਂ ਕੀ ਫ਼ਰਕ ਹੈ, ਅਤੇ ਹਰ ਸਹੂਲਤ ਕਿਸ ਕੰਮ ਦੀ ਹੈ।",
  "kicker": "ਗਾਈਡ",
  "h1": "ਦੋ ਫ਼ੋਨ, ਇੱਕ ਮੁਫ਼ਤ ਬੇਬੀ ਮਾਨੀਟਰ: BabyPhone.online ਕੀ-ਕੀ ਕਰ ਸਕਦਾ ਹੈ",
  "lede": "ਨਾ ਕੋਈ ਡੱਬਾ ਖ਼ਰੀਦਣਾ, ਨਾ ਐਪ ਪਾਉਣੀ, ਨਾ ਖਾਤਾ ਬਣਾਉਣਾ। ਆਪਣੇ ਕੋਲ ਪਹਿਲਾਂ ਤੋਂ ਮੌਜੂਦ ਦੋ ਡਿਵਾਈਸਾਂ ਉੱਤੇ ਸਾਈਟ ਖੋਲ੍ਹੋ ਅਤੇ ਸਿੱਧੀ ਤਸਵੀਰ ਤੇ ਆਵਾਜ਼ ਵਾਲਾ ਨਿੱਜੀ ਬੇਬੀ ਮਾਨੀਟਰ ਤਿਆਰ — ਘਰ ਵੀ, ਛੁੱਟੀਆਂ ਵਿੱਚ ਵੀ।",
  "introP": "ਰਵਾਇਤੀ ਬੇਬੀ ਮਾਨੀਟਰ ਦਾ ਮਤਲਬ ਹੈ ਇੱਕ ਹੋਰ ਚੀਜ਼ ਜੋ ਖ਼ਰੀਦਣੀ, ਚਾਰਜ ਕਰਨੀ ਤੇ ਨਾਲ ਲੈ ਕੇ ਜਾਣੀ ਪੈਂਦੀ ਹੈ। BabyPhone.online ਵੱਖਰਾ ਰਾਹ ਚੁਣਦਾ ਹੈ: ਤੁਹਾਡੇ ਮੌਜੂਦਾ ਡਿਵਾਈਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਹੀ ਕੈਮਰਾ ਤੇ ਮਾਨੀਟਰ ਬਣ ਜਾਂਦੇ ਹਨ। ਅੱਗੇ ਪੜ੍ਹੋ ਕਿ ਇਹ ਏਨਾ ਕੰਮ ਦਾ ਕਿਉਂ ਹੈ — ਤੇ ਹਰ ਬਟਨ ਕੀ ਕਰਦਾ ਹੈ।",
  "reuseH": "ਪੁਰਾਣੇ ਫ਼ੋਨ ਜਾਂ ਟੈਬਲੇਟ ਨੂੰ ਦੂਜੀ ਜ਼ਿੰਦਗੀ ਦਿਓ",
  "reuseP": "ਦੋ ਮਾਡਲ ਪਹਿਲਾਂ ਵਾਲਾ ਉਹ ਫ਼ੋਨ ਜੋ ਦਰਾਜ਼ ਵਿੱਚ ਪਿਆ ਹੈ, ਜਾਂ ਉਹ ਟੈਬਲੇਟ ਜਿਸ ਨੂੰ ਬੱਚੇ ਘੱਟ ਹੀ ਵਰਤਦੇ ਹਨ — ਦੋਵਾਂ ਵਿੱਚੋਂ ਕੋਈ ਵੀ ਬੱਚੇ ਦਾ ਕੈਮਰਾ ਬਣ ਸਕਦਾ ਹੈ। ਉਸ ਨੂੰ ਪੰਘੂੜੇ ਕੋਲ ਟਿਕਾ ਦਿਓ, babyphone.online ਖੋਲ੍ਹੋ, «ਬੇਬੀ ਯੂਨਿਟ» ਦਬਾਓ, ਤੇ ਉਹ ਸਿੱਧੀ ਤਸਵੀਰ ਤੇ ਆਵਾਜ਼ ਤੁਹਾਡੇ ਆਪਣੇ ਫ਼ੋਨ ਉੱਤੇ ਭੇਜਣ ਲੱਗੇਗਾ। ਸਿਮ ਕਾਰਡ ਦੀ ਲੋੜ ਨਹੀਂ: ਘਰ ਦਾ ਵਾਈ-ਫਾਈ ਕਾਫ਼ੀ ਹੈ। ਕੁਝ ਖ਼ਰੀਦੇ ਬਿਨਾਂ — ਤੇ ਕੁਝ ਸੁੱਟੇ ਬਿਨਾਂ — ਇੱਕ ਸੱਚਾ ਬੱਚਾ ਕੈਮਰਾ।",
  "travelH": "ਛੁੱਟੀਆਂ ਤੇ ਘਰੋਂ ਬਾਹਰ ਬਿਤਾਈਆਂ ਰਾਤਾਂ ਲਈ",
  "travelP": "ਅਸਲ ਕਮਾਲ ਇੱਥੇ ਹੀ ਦਿਸਦਾ ਹੈ। ਛੁੱਟੀ ਉੱਤੇ ਤੁਸੀਂ ਘੱਟ ਦੂਰੀ ਦੇ ਸਿਗਨਲ ਵਾਲਾ ਭਾਰਾ ਮਾਨੀਟਰ ਨਾਲ ਨਹੀਂ ਲਿਜਾਣਾ ਚਾਹੁੰਦੇ। BabyPhone.online ਨਾਲ ਤੁਸੀਂ ਉਹੀ ਦੋ ਫ਼ੋਨ ਵਰਤਦੇ ਹੋ ਜੋ ਵੈਸੇ ਵੀ ਨਾਲ ਹੁੰਦੇ ਹਨ: ਇੱਕ ਹੋਟਲ ਦੇ ਕਮਰੇ ਜਾਂ ਤੰਬੂ ਵਿੱਚ ਬੱਚੇ ਕੋਲ ਛੱਡ ਦਿਓ, ਦੂਜਾ ਵਿਹੜੇ ਜਾਂ ਨਾਲ ਵਾਲੇ ਕਮਰੇ ਵਿੱਚ ਲੈ ਜਾਓ। ਜੋੜ ਇੰਟਰਨੈੱਟ (ਵਾਈ-ਫਾਈ ਜਾਂ 4G/5G) ਰਾਹੀਂ ਚੱਲਦਾ ਹੈ, ਇਸ ਲਈ ਪਹੁੰਚ ਇੱਕ ਇਮਾਰਤ ਤੱਕ ਸੀਮਤ ਨਹੀਂ ਰਹਿੰਦੀ ਤੇ ਤੁਸੀਂ ਕਿਸੇ ਬੇਸ ਸਟੇਸ਼ਨ ਦੇ ਸਿਗਨਲ ਨਾਲ ਬੱਝੇ ਨਹੀਂ। ਦੋ ਫ਼ੋਨ, ਤੇ ਬੱਸ — ਕਿਤੇ ਵੀ।",
  "setupH": "ਇੱਕ ਮਿੰਟ ਤੋਂ ਵੀ ਘੱਟ ਵਿੱਚ ਜੋੜ",
  "setupP": "ਜੋੜਨਾ ਜਾਣ-ਬੁੱਝ ਕੇ ਸੌਖਾ ਰੱਖਿਆ ਹੈ, ਤਾਂ ਜੋ ਰਾਤ ਤਿੰਨ ਵਜੇ ਅੱਧੀ ਨੀਂਦ ਵਿੱਚ ਵੀ ਹੋ ਜਾਵੇ।",
  "steps": [
    "ਬੱਚੇ ਕੋਲ ਵਾਲੇ ਡਿਵਾਈਸ ਉੱਤੇ «ਬੇਬੀ ਯੂਨਿਟ» ਦਬਾਓ। ਉਹ 6 ਅੱਖਰਾਂ ਦਾ ਕੋਡ ਤੇ ਇੱਕ QR ਕੋਡ ਵਿਖਾਏਗਾ।",
    "ਆਪਣੇ ਫ਼ੋਨ ਉੱਤੇ «ਪੇਰੈਂਟ ਯੂਨਿਟ» ਦਬਾਓ।",
    "ਕੋਡ ਲਿਖੋ ਜਾਂ QR ਸਕੈਨ ਕਰੋ — ਤੁਰੰਤ ਹੀ ਬੱਚਾ ਦਿਸੇਗਾ ਤੇ ਸੁਣੇਗਾ।"
  ],
  "featH": "ਹਰ ਸਹੂਲਤ, ਤੇ ਉਹ ਕਿਸ ਲਈ ਹੈ",
  "featLede": "ਸਭ ਕੁਝ ਮਾਪਿਆਂ ਦੇ ਫ਼ੋਨ ਤੋਂ ਚੱਲਦਾ ਹੈ, ਜਦਕਿ ਬੱਚੇ ਦਾ ਡਿਵਾਈਸ ਸਿਰਫ਼ ਭੇਜਦਾ ਹੈ। ਇਹ ਰਹੀ ਪੂਰੀ ਸੂਚੀ।",
  "features": [
    {"n": "ਸਿੱਧੀ ਤਸਵੀਰ ਤੇ ਆਵਾਜ਼", "d": "ਘੱਟ ਦੇਰੀ ਨਾਲ ਅਸਲ ਸਮੇਂ ਵਿੱਚ ਬੱਚੇ ਨੂੰ ਵੇਖੋ ਤੇ ਸੁਣੋ — ਸਿਰਫ਼ ਘਰ ਦੇ ਵਾਈ-ਫਾਈ ਉੱਤੇ ਨਹੀਂ, 4G/5G ਉੱਤੇ ਵੀ।"},
    {"n": "ਜਵਾਬ ਦੇਣਾ", "d": "ਦਬਾਓ ਤੇ ਬੋਲੋ: ਤੁਹਾਡੀ ਆਵਾਜ਼ ਬੱਚੇ ਦੇ ਡਿਵਾਈਸ ਤੋਂ ਆਉਂਦੀ ਹੈ, ਸੋ ਕਮਰੇ ਵਿੱਚ ਗਏ ਬਿਨਾਂ ਹੀ ਵਰਾ ਸਕਦੇ ਹੋ।"},
    {"n": "ਲੋਰੀਆਂ ਤੇ ਸੰਗੀਤ", "d": "ਸ਼ਾਂਤ ਕਰਨ ਵਾਲੀਆਂ ਆਵਾਜ਼ਾਂ ਜਾਂ ਆਪਣੀਆਂ MP3 ਫ਼ਾਈਲਾਂ ਆਪਣੇ ਫ਼ੋਨ ਤੋਂ ਬੱਚੇ ਦੇ ਡਿਵਾਈਸ ਉੱਤੇ ਚਲਾਓ।"},
    {"n": "ਰਾਤ ਦੀ ਬੱਤੀ", "d": "ਆਪਣੇ ਪਾਸਿਓਂ ਬੱਚੇ ਦੇ ਡਿਵਾਈਸ ਦੀ ਸਕਰੀਨ ਉੱਤੇ ਨਰਮ, ਨਿੱਘੀ ਰੌਸ਼ਨੀ ਜਗਾਓ।"},
    {"n": "ਰੋਣ ਦੀ ਚੇਤਾਵਨੀ", "d": "ਬੱਚਾ ਰੋਵੇ ਤਾਂ ਸੂਚਨਾ ਪਾਓ, ਸੰਵੇਦਨਸ਼ੀਲਤਾ ਤੁਸੀਂ ਆਪ ਤੈਅ ਕਰੋ, ਨਾਲ ਘਟਨਾਵਾਂ ਦਾ ਵੇਰਵਾ ਵੀ।"},
    {"n": "ਨੀਂਦ ਦਾ ਟਾਈਮਰ", "d": "ਲੋਰੀ ਵੱਜਦੀ ਰਹੇ ਤੇ ਤੁਹਾਡੇ ਚੁਣੇ ਸਮੇਂ ਮਗਰੋਂ ਆਪੇ ਬੰਦ ਹੋ ਜਾਵੇ।"},
    {"n": "ਸਿਰਫ਼ ਆਵਾਜ਼ ਤੇ ਨਿੱਜਤਾ ਦਾ ਪਰਦਾ", "d": "ਜਦੋਂ ਵੀਡੀਓ ਨਹੀਂ ਚਾਹੀਦੀ ਪਰ ਕੰਨ ਖੁੱਲ੍ਹੇ ਰੱਖਣੇ ਹਨ, ਆਵਾਜ਼ ਰੱਖੋ ਤੇ ਤਸਵੀਰ ਲੁਕਾ ਦਿਓ।"},
    {"n": "ਬੈਟਰੀ ਦੀ ਹਾਲਤ", "d": "ਬੱਚੇ ਦੇ ਡਿਵਾਈਸ ਦੀ ਬੈਟਰੀ ਆਪਣੀ ਸਕਰੀਨ ਉੱਤੇ ਵੇਖੋ, ਤਾਂ ਜੋ ਉਹ ਚੁੱਪ-ਚਾਪ ਮੁੱਕ ਨਾ ਜਾਵੇ।"},
    {"n": "ਕਲਿੱਪ ਰਿਕਾਰਡ ਕਰੋ", "d": "ਤਸਵੀਰ ਤੇ ਆਵਾਜ਼ ਦਾ ਇੱਕ ਪਲ ਸਿੱਧਾ ਆਪਣੇ ਡਿਵਾਈਸ ਉੱਤੇ ਸਾਂਭੋ। ਕੁਝ ਵੀ ਕਿਤੇ ਅੱਪਲੋਡ ਨਹੀਂ ਹੁੰਦਾ।"},
    {"n": "ਹਮੇਸ਼ਾ ਮੁੜ ਜੁੜਦਾ ਹੈ", "d": "ਵਾਈ-ਫਾਈ ਤੇ ਮੋਬਾਈਲ ਦੇ ਬਦਲਾਅ ਤੇ ਸਕਰੀਨ ਬੰਦ ਹੋਣਾ ਝੱਲ ਲੈਂਦਾ ਹੈ, ਤੇ ਜੋੜ ਟੁੱਟਦੇ ਹੀ ਤੁਹਾਨੂੰ ਦੱਸ ਦਿੰਦਾ ਹੈ।"},
    {"n": "30 ਭਾਸ਼ਾਵਾਂ", "d": "ਪੂਰਾ ਇੰਟਰਫ਼ੇਸ ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਵਿੱਚ — ਇੱਕ ਵਾਰ ਚੁਣੋ, ਯਾਦ ਰੱਖ ਲਿਆ ਜਾਵੇਗਾ।"},
    {"n": "ਮੁਫ਼ਤ, ਖਾਤੇ ਬਿਨਾਂ", "d": "ਮੁੱਖ ਨਿਗਰਾਨੀ ਮੁਫ਼ਤ ਹੈ ਤੇ ਰਜਿਸਟਰੇਸ਼ਨ ਨਹੀਂ ਮੰਗਦੀ। ਸਾਈਟ ਖੋਲ੍ਹੋ ਤੇ ਤੁਰ ਪਓ।"}
  ],
  "privacyH": "ਬਣਤਰ ਤੋਂ ਹੀ ਨਿੱਜੀ",
  "privacyP": "ਤਸਵੀਰ ਤੇ ਆਵਾਜ਼ ਤੁਹਾਡੇ ਦੋਵਾਂ ਡਿਵਾਈਸਾਂ ਵਿਚਕਾਰ ਸਿੱਧੀ ਜਾਂਦੀ ਹੈ, ਡਿਵਾਈਸ ਤੋਂ ਡਿਵਾਈਸ ਤੇ ਰਾਹ ਵਿੱਚ ਐਨਕ੍ਰਿਪਟਡ। ਕੁਝ ਵੀ ਰਿਕਾਰਡ ਨਹੀਂ ਹੁੰਦਾ, ਤੇ ਕੋਈ ਸਰਵਰ ਵੇਖ ਨਹੀਂ ਸਕਦਾ। ਨਾ ਖਾਤਾ, ਨਾ ਇਸ਼ਤਿਹਾਰ, ਨਾ ਟਰੈਕਿੰਗ — ਬੱਸ ਤੁਹਾਡੇ ਆਪਣੇ ਡਿਵਾਈਸ ਆਪਸ ਵਿੱਚ ਗੱਲ ਕਰ ਰਹੇ ਹਨ।",
  "worksH": "ਉਨ੍ਹਾਂ ਹੀ ਡਿਵਾਈਸਾਂ ਉੱਤੇ ਚੱਲਦਾ ਹੈ ਜੋ ਤੁਹਾਡੇ ਕੋਲ ਹਨ",
  "worksP": "ਕੋਈ ਵੀ ਫ਼ੋਨ, ਟੈਬਲੇਟ ਜਾਂ ਲੈਪਟਾਪ ਜਿਸ ਵਿੱਚ ਮੁਕਾਬਲਤਨ ਨਵਾਂ ਬ੍ਰਾਊਜ਼ਰ (Chrome, Safari, Firefox, Edge) ਹੋਵੇ, ਕੰਮ ਕਰੇਗਾ — ਪੁਰਾਣੇ ਮਾਡਲ ਵੀ, ਬਸ਼ਰਤੇ ਬ੍ਰਾਊਜ਼ਰ ਠੀਕ-ਠਾਕ ਨਵਾਂ ਹੋਵੇ। ਬੱਚੇ ਵਾਲੇ ਪਾਸੇ ਦੇ ਡਿਵਾਈਸ ਵਿੱਚ ਕੈਮਰਾ ਤੇ ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਚਾਹੀਦਾ ਹੈ; ਉਸ ਨੂੰ ਚਾਰਜਰ ਉੱਤੇ ਲੱਗਾ ਰਹਿਣ ਦਿਓ ਤਾਂ ਸਾਰੀ ਰਾਤ ਲੰਘ ਜਾਵੇਗੀ।",
  "wifiH": "ਵਾਈ-ਫਾਈ ਉੱਤੇ ਬੇਬੀ ਮਾਨੀਟਰ ਅਸਲ ਵਿੱਚ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ",
  "wifiP": "ਰਵਾਇਤੀ ਬੇਬੀ ਮਾਨੀਟਰ ਘੱਟ ਦੂਰੀ ਦੇ ਦੋ ਰੇਡੀਓ ਹੁੰਦੇ ਹਨ: ਕੈਮਰਾ ਯੂਨਿਟ ਭੇਜਦਾ ਹੈ, ਮਾਪਿਆਂ ਦਾ ਯੂਨਿਟ ਪਾਉਂਦਾ ਹੈ, ਤੇ ਇੱਕ ਮੋਟੀ ਕੰਧ ਗੱਲ ਮੁਕਾ ਦਿੰਦੀ ਹੈ। ਵਾਈ-ਫਾਈ ਵਾਲਾ ਮਾਨੀਟਰ ਤਸਵੀਰ ਤੇ ਆਵਾਜ਼ ਨੂੰ ਡਾਟੇ ਵਜੋਂ ਇੰਟਰਨੈੱਟ ਰਾਹੀਂ ਭੇਜਦਾ ਹੈ। BabyPhone.online WebRTC ਵਰਤਦਾ ਹੈ — ਉਹੀ ਤਕਨਾਲੋਜੀ ਜੋ ਤੁਹਾਡਾ ਬ੍ਰਾਊਜ਼ਰ ਵੀਡੀਓ ਕਾਲਾਂ ਲਈ ਵਰਤਦਾ ਹੈ — ਜਿਸ ਨਾਲ ਦੋਵੇਂ ਡਿਵਾਈਸ ਆਪਸ ਵਿੱਚ ਸਿੱਧਾ, ਐਨਕ੍ਰਿਪਟਡ ਰਾਹ ਖੋਲ੍ਹ ਲੈਂਦੇ ਹਨ। ਕਮਰਾ ਕੋਡ ਸਿਰਫ਼ ਸ਼ੁਰੂ ਵਿੱਚ ਉਨ੍ਹਾਂ ਨੂੰ ਇੱਕ-ਦੂਜੇ ਨੂੰ ਲੱਭਣ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ, ਤੇ ਐਨਕ੍ਰਿਪਟਡ ਰਿਲੇ ਤਾਂ ਹੀ ਵਿਚਾਲੇ ਆਉਂਦਾ ਹੈ ਜਦੋਂ ਤੁਹਾਡਾ ਨੈੱਟਵਰਕ ਸਿੱਧਾ ਰਾਹ ਰੋਕ ਦੇਵੇ; ਇਨ੍ਹਾਂ ਵਿੱਚੋਂ ਕੋਈ ਵੀ ਧਾਰਾ ਵੇਖ ਜਾਂ ਸੁਣ ਨਹੀਂ ਸਕਦਾ। ਅਮਲੀ ਫ਼ਰਕ ਇਹ ਹੈ: ਪਹੁੰਚ ਹੁਣ ਮੀਟਰਾਂ ਵਿੱਚ ਨਹੀਂ ਮਿਣੀ ਜਾਂਦੀ, ਪਰ ਦੋਵੇਂ ਡਿਵਾਈਸ ਆਨਲਾਈਨ ਹੋਣੇ ਜ਼ਰੂਰੀ ਹਨ।",
  "vsH": "ਬੇਬੀ ਮਾਨੀਟਰ ਐਪ ਜਾਂ ਵੱਖਰਾ ਯੰਤਰ?",
  "vsLede": "ਕੋਈ ਵੀ ਪੂਰੀ ਤਰ੍ਹਾਂ ਨਹੀਂ ਜਿੱਤਦਾ — ਦੋਵੇਂ ਵੱਖੋ-ਵੱਖਰੇ ਢੰਗ ਨਾਲ ਘੱਟ ਪੈਂਦੇ ਹਨ। ਇੱਕ ਖਰੀ ਤੁਲਨਾ।",
  "vs": [
    {"n": "ਪਹੁੰਚ", "d": "ਵੱਖਰਾ ਯੰਤਰ ਆਪਣੀ ਰੇਡੀਓ ਹੱਦ ਵਿੱਚ ਕਿਤੇ ਵੀ ਚੱਲਦਾ ਹੈ ਤੇ ਉਸ ਨੂੰ ਇੰਟਰਨੈੱਟ ਦੀ ਲੋੜ ਹੀ ਨਹੀਂ। ਐਪ ਦੀ ਪਹੁੰਚ ਅਮਲ ਵਿੱਚ ਬੇਹੱਦ ਹੈ, ਪਰ ਦੋਵੇਂ ਡਿਵਾਈਸ ਆਨਲਾਈਨ ਚਾਹੀਦੇ ਹਨ।"},
    {"n": "ਖ਼ਰਚ", "d": "ਤਸਵੀਰ ਵਾਲੇ ਮਾਨੀਟਰ ਉੱਤੇ ਅਸਲ ਪੈਸਾ ਲੱਗਦਾ ਹੈ ਤੇ ਬੱਚਾ ਵੱਡਾ ਹੋਣ ਉੱਤੇ ਉਹ ਇਲੈਕਟ੍ਰਾਨਿਕ ਕੂੜਾ ਬਣ ਜਾਂਦਾ ਹੈ। ਇਸ ਵਿੱਚ ਖ਼ਰਚ ਕੋਈ ਨਹੀਂ ਤੇ ਤੁਹਾਡੇ ਮੌਜੂਦਾ ਯੰਤਰ ਹੀ ਮੁੜ ਕੰਮ ਆਉਂਦੇ ਹਨ।"},
    {"n": "ਸਫ਼ਰ", "d": "ਇੱਕ ਬੇਸ ਸਟੇਸ਼ਨ, ਇੱਕ ਕੈਮਰਾ ਤੇ ਦੋ ਚਾਰਜਰ ਅੱਧਾ ਬੈਗ ਭਰ ਦਿੰਦੇ ਹਨ। ਜੋ ਦੋ ਫ਼ੋਨ ਵੈਸੇ ਵੀ ਨਾਲ ਸਨ, ਉਹ ਕੋਈ ਥਾਂ ਨਹੀਂ ਘੇਰਦੇ।"},
    {"n": "ਭਰੋਸਾ", "d": "ਵੱਖਰਾ ਯੰਤਰ ਇੱਕੋ ਕੰਮ ਕਰਦਾ ਹੈ, ਨਾ ਸਿਸਟਮ ਅੱਪਡੇਟ ਵਿਚਾਲੇ ਆਉਂਦੀ ਹੈ ਨਾ ਆਉਂਦੀ ਕਾਲ। ਫ਼ੋਨ ਨੂੰ ਧਿਆਨ ਚਾਹੀਦਾ ਹੈ: ਚਾਰਜਰ ਉੱਤੇ ਰੱਖੋ, ਸਕਰੀਨ ਜਾਗਦੀ ਰਹੇ, ਬਾਕੀ ਐਪਾਂ ਬੰਦ ਰੱਖੋ।"},
    {"n": "ਨਿੱਜਤਾ", "d": "ਕਲਾਊਡ ਕੈਮਰੇ ਰਿਕਾਰਡਿੰਗ ਕੰਪਨੀ ਦੇ ਸਰਵਰਾਂ ਉੱਤੇ ਰੱਖਦੇ ਹਨ; ਸਸਤੇ ਐਨਾਲਾਗ ਮਾਨੀਟਰ ਨੇੜੇ ਦਾ ਕੋਈ ਰਿਸੀਵਰ ਫੜ ਸਕਦਾ ਹੈ। ਡਿਵਾਈਸ-ਤੋਂ-ਡਿਵਾਈਸ ਜੋੜ ਦੋਵਾਂ ਤੋਂ ਬਚਾਉਂਦਾ ਹੈ — ਪਰ ਕਮਰਾ ਕੋਡ ਕਿਸ ਨੂੰ ਦੇਣਾ ਹੈ, ਇਹ ਤੁਸੀਂ ਤੈਅ ਕਰਦੇ ਹੋ।"},
    {"n": "ਰਾਤ ਦੀ ਨਜ਼ਰ", "d": "ਵੱਖਰੇ ਯੰਤਰਾਂ ਵਿੱਚ ਇਨਫ਼ਰਾਰੈੱਡ ਐਲਈਡੀ ਹੁੰਦੀਆਂ ਹਨ; ਫ਼ੋਨ ਦਾ ਕੈਮਰਾ ਇਹ ਨਹੀਂ ਕਰ ਸਕਦਾ। ਘੁੱਪ ਹਨੇਰੇ ਕਮਰੇ ਵਿੱਚ ਤੁਹਾਨੂੰ ਸਭ ਸੁਣੇਗਾ ਪਰ ਦਿਸੇਗਾ ਘੱਟ — ਅੰਦਰਲੀ ਰਾਤ ਦੀ ਬੱਤੀ ਮਦਦ ਕਰਦੀ ਹੈ।"}
  ],
  "faqH": "ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ",
  "faq": [
    {"n": "ਕੀ ਬੇਬੀ ਮਾਨੀਟਰ ਐਪ ਸੁਰੱਖਿਅਤ ਹੈ?", "d": "ਇਹ ਇਸ ਗੱਲ ਉੱਤੇ ਨਿਰਭਰ ਹੈ ਕਿ ਵੀਡੀਓ ਕਿੱਥੇ ਜਾਂਦੀ ਹੈ ਤੇ ਕੌਣ ਜੁੜ ਸਕਦਾ ਹੈ। ਇੱਥੇ ਧਾਰਾ ਸਿੱਧੀ ਤੁਹਾਡੇ ਦੋਵਾਂ ਡਿਵਾਈਸਾਂ ਵਿਚਕਾਰ ਚੱਲਦੀ ਹੈ ਤੇ ਰਾਹ ਵਿੱਚ ਐਨਕ੍ਰਿਪਟਡ ਰਹਿੰਦੀ ਹੈ, ਸੋ ਨਾ ਕੋਈ ਕਲਾਊਡ ਖਾਤਾ ਹੈ ਜਿਸ ਵਿੱਚ ਸੰਨ੍ਹ ਲੱਗੇ, ਨਾ ਕਿਸੇ ਹੋਰ ਦੇ ਸਰਵਰ ਉੱਤੇ ਕੋਈ ਰਿਕਾਰਡਿੰਗ। ਬੇਬੀ ਯੂਨਿਟ ਆਪੇ ਜਵਾਬ ਵੀ ਨਹੀਂ ਦਿੰਦਾ: ਜਿਸ ਡਿਵਾਈਸ ਨੇ QR ਸਕੈਨ ਕੀਤਾ ਉਸ ਕੋਲ ਇੱਕ ਵਾਰੀ ਦੀ ਕੁੰਜੀ ਹੁੰਦੀ ਹੈ, ਤੇ ਜੋ ਕੋਡ ਹੱਥੀਂ ਲਿਖੇ ਉਸ ਨੂੰ ਬੱਚੇ ਦੇ ਡਿਵਾਈਸ ਦੀ ਆਪਣੀ ਸਕਰੀਨ ਉੱਤੇ ਮਨਜ਼ੂਰੀ ਲੈਣੀ ਪੈਂਦੀ ਹੈ।"},
    {"n": "ਕੀ ਵਾਈ-ਫਾਈ ਬਿਨਾਂ ਚੱਲਦਾ ਹੈ?", "d": "ਇਸ ਨੂੰ ਦੋਵਾਂ ਡਿਵਾਈਸਾਂ ਉੱਤੇ ਇੰਟਰਨੈੱਟ ਚਾਹੀਦਾ ਹੈ — ਪਰ ਖ਼ਾਸ ਵਾਈ-ਫਾਈ ਨਹੀਂ, ਤੇ ਨਾ ਹੀ ਇੱਕੋ ਨੈੱਟਵਰਕ: ਬੱਚੇ ਦਾ ਡਿਵਾਈਸ ਵਾਈ-ਫਾਈ ਉੱਤੇ ਹੋਵੇ ਤੇ ਤੁਸੀਂ 4G ਜਾਂ 5G ਉੱਤੇ, ਇਹ ਵੀ ਚੱਲਦਾ ਹੈ। ਦੋਵੇਂ ਪਾਸੇ ਇੰਟਰਨੈੱਟ ਬਿਲਕੁਲ ਨਾ ਹੋਵੇ ਤਾਂ ਡਿਵਾਈਸ ਇੱਕ-ਦੂਜੇ ਨੂੰ ਨਹੀਂ ਲੱਭ ਸਕਦੇ, ਤੇ ਉਦੋਂ ਰਵਾਇਤੀ ਰੇਡੀਓ ਮਾਨੀਟਰ ਬਿਹਤਰ ਹੈ।"},
    {"n": "ਖ਼ਰਚ ਕਿੰਨਾ ਹੈ?", "d": "ਕੁਝ ਵੀ ਨਹੀਂ। ਸਾਰੀਆਂ ਸਹੂਲਤਾਂ ਮੁਫ਼ਤ ਹਨ, ਨਾ ਕੋਈ ਅਦਾਇਗੀ ਵਾਲਾ ਦਰਜਾ ਹੈ ਨਾ ਖਾਤਾ, ਤੇ ਸਾਈਟ ਉੱਤੇ ਨਾ ਇਸ਼ਤਿਹਾਰ ਹਨ ਨਾ ਟਰੈਕਰ।"},
    {"n": "ਕੀ ਪੁਰਾਣਾ ਫ਼ੋਨ ਵਰਤ ਸਕਦਾ ਹਾਂ?", "d": "ਹਾਂ, ਤੇ ਮਕਸਦ ਹੀ ਇਹੀ ਹੈ। ਕੈਮਰਾ, ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਤੇ ਨਵਾਂ ਬ੍ਰਾਊਜ਼ਰ ਵਾਲਾ ਕੋਈ ਵੀ ਵਾਧੂ ਫ਼ੋਨ ਜਾਂ ਟੈਬਲੇਟ ਚੱਲ ਜਾਵੇਗਾ, ਸਿਮ ਹੋਵੇ ਜਾਂ ਨਾ। ਉਸ ਨੂੰ ਬਿਜਲੀ ਨਾਲ ਲੱਗਾ ਰੱਖੋ — ਸਾਰੀ ਰਾਤ ਵੀਡੀਓ ਭੇਜਣ ਨਾਲ ਬੈਟਰੀ ਮੁੱਕ ਜਾਂਦੀ ਹੈ।"},
    {"n": "ਕੀ ਕੁਝ ਇੰਸਟਾਲ ਕਰਨਾ ਪਵੇਗਾ?", "d": "ਨਹੀਂ। ਦੋਵੇਂ ਡਿਵਾਈਸ ਬੱਸ ਵੈੱਬਸਾਈਟ ਖੋਲ੍ਹਦੇ ਹਨ। ਨਾ ਕੁਝ ਡਾਊਨਲੋਡ ਕਰਨਾ, ਨਾ ਰਜਿਸਟਰੇਸ਼ਨ, ਨਾ ਕੋਈ ਸੈਟਿੰਗ।"},
    {"n": "ਇੱਕੋ ਵੇਲੇ ਕਿੰਨੇ ਜਣੇ ਵੇਖ ਸਕਦੇ ਹਨ?", "d": "ਦੂਜਾ ਵੇਖਣ ਵਾਲਾ ਉਸੇ ਕਮਰਾ ਕੋਡ ਨਾਲ ਜੁੜ ਸਕਦਾ ਹੈ, ਪਰ ਬੇਬੀ ਯੂਨਿਟ ਪਹਿਲਾਂ ਆਪਣੀ ਸਕਰੀਨ ਉੱਤੇ ਮਨਜ਼ੂਰੀ ਮੰਗਦਾ ਹੈ — ਯਾਨੀ ਕਮਰੇ ਵਿੱਚ ਮੌਜੂਦ ਕਿਸੇ ਦੀ ਸਹਿਮਤੀ ਬਿਨਾਂ ਕੋਈ ਨਹੀਂ ਵੇਖ ਸਕਦਾ।"}
  ],
  "ctaH": "ਅੱਜ ਰਾਤ ਹੀ ਅਜ਼ਮਾਓ",
  "ctaP": "ਦੋ ਡਿਵਾਈਸ ਲਓ, ਦੋਵਾਂ ਉੱਤੇ ਸਾਈਟ ਖੋਲ੍ਹੋ, ਤੇ ਵੇਖੋ ਇਹ ਕਿੰਨੀ ਛੇਤੀ ਹੋ ਜਾਂਦਾ ਹੈ।",
  "ctaBtn": "BabyPhone.online ਖੋਲ੍ਹੋ",
  "shotHome": "ਕਿਸੇ ਵੀ ਡਿਵਾਈਸ ਉੱਤੇ ਸਾਈਟ ਖੋਲ੍ਹੋ — ਨਾ ਇੰਸਟਾਲ, ਨਾ ਖਾਤਾ।",
  "shotParent": "ਪੇਰੈਂਟ ਯੂਨਿਟ: ਜਵਾਬ ਦੇਣ, ਲੋਰੀਆਂ, ਰਾਤ ਦੀ ਬੱਤੀ, ਰੋਣ ਦੀ ਚੇਤਾਵਨੀ ਤੇ ਰਿਕਾਰਡਿੰਗ ਸਮੇਤ ਸਿੱਧਾ ਦ੍ਰਿਸ਼ — ਸਭ ਤੁਹਾਡੇ ਫ਼ੋਨ ਤੋਂ।",
  "shotBaby": "ਬੇਬੀ ਯੂਨਿਟ: ਸਿੱਧਾ ਕੈਮਰਾ, ਕਮਰਾ ਕੋਡ ਤੇ ਜੋੜਨ ਲਈ QR, ਨਾਲ ਕੈਮਰਾ, ਮਾਈਕ, ਸਿਰਫ਼-ਆਵਾਜ਼ ਤੇ ਨਿੱਜਤਾ-ਪਰਦੇ ਦੇ ਕੰਟਰੋਲ।",
  "backToApp": "← ਐਪ ਉੱਤੇ ਵਾਪਸ",
  "readTime": "4 ਮਿੰਟ ਦਾ ਪਾਠ",
  "updated": "ਜੁਲਾਈ 2026 ਵਿੱਚ ਅੱਪਡੇਟ",
}

T['th'] = {
  "title": "เปลี่ยนโทรศัพท์สองเครื่องเป็นเครื่องเฝ้าดูทารกฟรี | คู่มือ",
  "desc": "วิธีทำเครื่องเฝ้าดูทารกฟรีจากโทรศัพท์สำรองหรือแท็บเล็ตเก่า: เครื่องเฝ้าดูผ่าน Wi-Fi ทำงานอย่างไร ต่างจากอุปกรณ์เฉพาะทางอย่างไร และแต่ละฟีเจอร์มีไว้ทำอะไร",
  "kicker": "คู่มือ",
  "h1": "โทรศัพท์สองเครื่อง เครื่องเฝ้าดูทารกฟรีหนึ่งชุด: ทุกอย่างที่ BabyPhone.online ทำได้",
  "lede": "ไม่มีกล่องให้ซื้อ ไม่มีแอปให้ติดตั้ง ไม่มีบัญชีให้สมัคร เปิดเว็บไซต์บนอุปกรณ์สองเครื่องที่คุณมีอยู่แล้ว แล้วคุณก็จะได้เครื่องเฝ้าดูทารกส่วนตัวพร้อมภาพและเสียงสด ทั้งที่บ้านและตอนไปเที่ยว",
  "introP": "เครื่องเฝ้าดูทารกแบบเดิมคือของอีกชิ้นที่ต้องซื้อ ต้องชาร์จ และต้องขนไป BabyPhone.online เลือกอีกเส้นทาง คือเปลี่ยนอุปกรณ์ที่คุณมีอยู่แล้วให้เป็นกล้องและจอมอนิเตอร์ในเบราว์เซอร์ทันที ต่อไปนี้คือเหตุผลว่าทำไมจึงสะดวก และแต่ละปุ่มทำอะไรบ้าง",
  "reuseH": "ให้ชีวิตที่สองแก่โทรศัพท์หรือแท็บเล็ตเครื่องเก่า",
  "reuseP": "โทรศัพท์ที่นอนอยู่ในลิ้นชักตั้งแต่เปลี่ยนรุ่นเมื่อสองครั้งก่อน หรือแท็บเล็ตที่เด็ก ๆ แทบไม่ได้ใช้ ทั้งคู่เป็นกล้องดูลูกได้ วางพิงไว้ข้างเปล เปิด babyphone.online แตะ „เครื่องฝั่งทารก\" แล้วมันจะส่งภาพและเสียงสดมายังโทรศัพท์ของคุณ ไม่ต้องใช้ซิม แค่ Wi-Fi ที่บ้านก็พอ กล้องดูลูกของจริง โดยไม่ต้องซื้อ และไม่ต้องทิ้งอะไรเลย",
  "travelH": "ทำมาเพื่อการเดินทางและคืนที่ไม่ได้นอนบ้าน",
  "travelP": "จุดนี้แหละที่มันโดดเด่น เวลาไปเที่ยวคุณคงไม่อยากขนเครื่องเฝ้าดูตัวใหญ่ที่สัญญาณไปได้ไม่ไกล กับ BabyPhone.online คุณใช้แค่โทรศัพท์สองเครื่องที่พกอยู่แล้ว วางเครื่องหนึ่งไว้ในห้องพักหรือเต็นท์กับลูก อีกเครื่องถือไปที่ระเบียงหรือห้องข้าง ๆ เพราะการเชื่อมต่อวิ่งผ่านอินเทอร์เน็ต (Wi-Fi หรือ 4G/5G) ระยะจึงไม่ได้จำกัดอยู่แค่ในอาคารเดียว และคุณไม่ต้องพึ่งสัญญาณจากตัวแม่ข่าย โทรศัพท์สองเครื่อง เท่านี้ก็พร้อม ไม่ว่าจะอยู่ที่ไหน",
  "setupH": "เชื่อมต่อได้ในเวลาไม่ถึงหนึ่งนาที",
  "setupP": "การจับคู่ถูกทำให้ง่ายโดยตั้งใจ เพื่อให้ทำได้แม้ตอนตีสามที่ยังครึ่งหลับครึ่งตื่น",
  "steps": [
    "บนอุปกรณ์ที่อยู่ข้างลูก แตะ „เครื่องฝั่งทารก\" ระบบจะแสดงรหัส 6 ตัวอักษรและคิวอาร์โค้ด",
    "บนโทรศัพท์ของคุณเอง แตะ „เครื่องฝั่งผู้ปกครอง\"",
    "พิมพ์รหัสหรือสแกนคิวอาร์ แล้วคุณจะเห็นและได้ยินลูกทันที"
  ],
  "featH": "ทุกฟีเจอร์ และมีไว้ทำอะไร",
  "featLede": "ทุกอย่างสั่งงานจากโทรศัพท์ฝั่งผู้ปกครอง ส่วนเครื่องฝั่งทารกมีหน้าที่ส่งอย่างเดียว นี่คือรายการทั้งหมด",
  "features": [
    {"n": "ภาพและเสียงสด", "d": "เห็นและได้ยินลูกแบบเรียลไทม์ ดีเลย์ต่ำ ใช้ได้ทั้งบน 4G/5G ไม่ใช่แค่ Wi-Fi ที่บ้าน"},
    {"n": "พูดตอบกลับ", "d": "แตะแล้วพูด เสียงของคุณจะดังจากเครื่องฝั่งทารก ปลอบลูกได้โดยไม่ต้องเดินเข้าไปในห้อง"},
    {"n": "เพลงกล่อมและดนตรี", "d": "เปิดเสียงผ่อนคลายหรือไฟล์ MP3 ของคุณเองบนเครื่องฝั่งทารก สั่งจากโทรศัพท์ได้เลย"},
    {"n": "ไฟกลางคืน", "d": "เปิดแสงนวลอบอุ่นบนหน้าจอเครื่องฝั่งทารกจากฝั่งของคุณ"},
    {"n": "แจ้งเตือนเสียงร้อง", "d": "รับแจ้งเตือนเมื่อลูกร้อง ตั้งความไวได้เอง พร้อมบันทึกเหตุการณ์"},
    {"n": "ตั้งเวลาปิด", "d": "ให้เพลงกล่อมเล่นไป แล้วหยุดเองเมื่อครบเวลาที่คุณเลือก"},
    {"n": "เสียงอย่างเดียวและม่านความเป็นส่วนตัว", "d": "เก็บเสียงไว้แต่ซ่อนภาพ เวลาที่อยากปิดวิดีโอแต่ยังอยากฟัง"},
    {"n": "สถานะแบตเตอรี่", "d": "ดูระดับแบตเตอรี่ของเครื่องฝั่งทารกบนหน้าจอของคุณ จะได้ไม่ดับไปโดยไม่รู้ตัว"},
    {"n": "บันทึกคลิป", "d": "เก็บช่วงเวลาที่มีทั้งภาพและเสียงลงในอุปกรณ์ของคุณโดยตรง ไม่มีการอัปโหลดไปไหน"},
    {"n": "เชื่อมต่อใหม่เสมอ", "d": "ทนต่อการสลับ Wi-Fi กับเน็ตมือถือและการปิดหน้าจอ และแจ้งคุณทันทีที่การเชื่อมต่อหลุด"},
    {"n": "30 ภาษา", "d": "หน้าจอทั้งหมดเป็นภาษาของคุณ เลือกครั้งเดียวแล้วระบบจะจำไว้"},
    {"n": "ฟรี ไม่ต้องมีบัญชี", "d": "การเฝ้าดูหลักใช้ฟรีและไม่ต้องสมัคร เปิดเว็บไซต์แล้วใช้ได้เลย"}
  ],
  "privacyH": "เป็นส่วนตัวตั้งแต่การออกแบบ",
  "privacyP": "ภาพและเสียงเดินทางตรงระหว่างอุปกรณ์สองเครื่องของคุณ จากเครื่องถึงเครื่อง และเข้ารหัสระหว่างทาง ไม่มีการบันทึก และไม่มีเซิร์ฟเวอร์ใดดูได้ ไม่มีบัญชี ไม่มีโฆษณา ไม่มีการติดตาม มีแค่อุปกรณ์ของคุณเองที่คุยกัน",
  "worksH": "ใช้ได้กับอุปกรณ์ที่คุณมีอยู่แล้ว",
  "worksP": "โทรศัพท์ แท็บเล็ต หรือแล็ปท็อปเครื่องใดก็ได้ที่มีเบราว์เซอร์ค่อนข้างใหม่ (Chrome, Safari, Firefox, Edge) รวมถึงรุ่นเก่า ตราบใดที่เบราว์เซอร์อัปเดตพอสมควร เครื่องฝั่งทารกต้องมีกล้องและไมโครโฟน เสียบสายชาร์จไว้ก็อยู่ได้ทั้งคืน",
  "wifiH": "เครื่องเฝ้าดูทารกผ่าน Wi-Fi ทำงานอย่างไรกันแน่",
  "wifiP": "เครื่องเฝ้าดูแบบคลาสสิกคือวิทยุระยะสั้นสองตัว ตัวกล้องส่ง ตัวผู้ปกครองรับ และกำแพงหนา ๆ ก็จบบทสนทนา ส่วนเครื่องที่ใช้ Wi-Fi จะส่งภาพและเสียงเป็นข้อมูลผ่านอินเทอร์เน็ต BabyPhone.online ใช้ WebRTC ซึ่งเป็นเทคโนโลยีเดียวกับที่เบราว์เซอร์ใช้โทรวิดีโอ อุปกรณ์ทั้งสองจึงเปิดช่องทางตรงที่เข้ารหัสถึงกัน รหัสห้องมีไว้ช่วยให้ทั้งคู่หากันเจอในตอนเริ่มเท่านั้น ส่วนตัวรีเลย์ที่เข้ารหัสจะเข้ามาก็ต่อเมื่อเครือข่ายของคุณปิดกั้นเส้นทางตรง และทั้งสองอย่างมองไม่เห็นและฟังไม่ได้ ข้อแตกต่างในทางปฏิบัติคือ ระยะไม่ได้วัดเป็นเมตรอีกต่อไป แต่ทั้งสองเครื่องต้องออนไลน์",
  "vsH": "แอปเฝ้าดูทารก หรืออุปกรณ์เฉพาะทาง",
  "vsLede": "ไม่มีฝ่ายไหนชนะขาด ต่างก็มีจุดอ่อนคนละแบบ นี่คือการเปรียบเทียบอย่างตรงไปตรงมา",
  "vs": [
    {"n": "ระยะ", "d": "อุปกรณ์เฉพาะทางใช้ได้ทุกที่ในระยะคลื่นของมันและไม่ต้องใช้อินเทอร์เน็ตเลย ส่วนแอปแทบไม่จำกัดระยะ แต่ทั้งสองเครื่องต้องออนไลน์"},
    {"n": "ค่าใช้จ่าย", "d": "เครื่องเฝ้าดูแบบมีภาพต้องจ่ายเงินจริง และกลายเป็นขยะอิเล็กทรอนิกส์เมื่อลูกโตขึ้น ส่วนแบบนี้ไม่มีค่าใช้จ่ายและได้ใช้อุปกรณ์ที่มีอยู่แล้วซ้ำ"},
    {"n": "การเดินทาง", "d": "ตัวแม่ข่าย กล้อง และที่ชาร์จสองอัน กินพื้นที่ครึ่งกระเป๋า ส่วนโทรศัพท์สองเครื่องที่พกอยู่แล้วไม่กินที่เลย"},
    {"n": "ความน่าเชื่อถือ", "d": "อุปกรณ์เฉพาะทางทำงานเดียว ไม่มีอัปเดตระบบหรือสายเรียกเข้ามาขัด ส่วนโทรศัพท์ต้องดูแล เสียบชาร์จไว้ อย่าให้จอดับ และปิดแอปอื่น"},
    {"n": "ความเป็นส่วนตัว", "d": "กล้องบนคลาวด์เก็บภาพไว้บนเซิร์ฟเวอร์ของผู้ผลิต ส่วนเครื่องอนาล็อกราคาถูกอาจถูกเครื่องรับใกล้ ๆ ดักได้ การเชื่อมต่อตรงระหว่างอุปกรณ์เลี่ยงได้ทั้งสองอย่าง แต่คุณเป็นคนตัดสินว่าจะให้รหัสห้องแก่ใคร"},
    {"n": "การมองในที่มืด", "d": "อุปกรณ์เฉพาะทางมีไฟอินฟราเรด กล้องโทรศัพท์ทำไม่ได้ ในห้องที่มืดสนิทคุณจะได้ยินทุกอย่างแต่เห็นน้อย ไฟกลางคืนที่มีมาให้ช่วยได้"}
  ],
  "faqH": "คำถามที่พบบ่อย",
  "faq": [
    {"n": "แอปเฝ้าดูทารกปลอดภัยไหม", "d": "ขึ้นอยู่กับว่าวิดีโอไปที่ไหนและใครเข้าร่วมได้ ที่นี่สตรีมวิ่งตรงระหว่างอุปกรณ์สองเครื่องของคุณและเข้ารหัสระหว่างทาง จึงไม่มีบัญชีคลาวด์ให้เจาะและไม่มีภาพเก็บอยู่บนเซิร์ฟเวอร์ของคนอื่น เครื่องฝั่งทารกก็ไม่รับสายอัตโนมัติ อุปกรณ์ที่สแกนคิวอาร์จะถือกุญแจใช้ครั้งเดียว ส่วนใครที่พิมพ์รหัสเองต้องได้รับอนุมัติบนหน้าจอของเครื่องฝั่งทารก"},
    {"n": "ใช้ได้ไหมถ้าไม่มี Wi-Fi", "d": "แบบนี้ต้องมีอินเทอร์เน็ตทั้งสองเครื่อง แต่ไม่จำเป็นต้องเป็น Wi-Fi และไม่ต้องเป็นเครือข่ายเดียวกัน เครื่องฝั่งทารกอยู่บน Wi-Fi ส่วนคุณใช้ 4G หรือ 5G ก็ได้ ถ้าทั้งสองฝั่งไม่มีอินเทอร์เน็ตเลย อุปกรณ์จะหากันไม่เจอ กรณีนั้นเครื่องวิทยุแบบคลาสสิกเหมาะกว่า"},
    {"n": "ราคาเท่าไร", "d": "ไม่มีค่าใช้จ่าย ทุกฟีเจอร์ฟรี ไม่มีแบบเสียเงินและไม่มีบัญชี เว็บไซต์ก็ไม่มีโฆษณาและไม่มีตัวติดตาม"},
    {"n": "ใช้โทรศัพท์เครื่องเก่าได้ไหม", "d": "ได้ และนั่นคือจุดประสงค์ โทรศัพท์หรือแท็บเล็ตสำรองเครื่องไหนก็ได้ที่มีกล้อง ไมโครโฟน และเบราว์เซอร์ที่อัปเดต จะมีซิมหรือไม่ก็ได้ เสียบชาร์จไว้ด้วย เพราะการส่งวิดีโอทั้งคืนกินแบตเตอรี่"},
    {"n": "ต้องติดตั้งอะไรไหม", "d": "ไม่ต้อง ทั้งสองเครื่องแค่เปิดเว็บไซต์ ไม่มีอะไรให้ดาวน์โหลด ไม่ต้องสมัคร และไม่ต้องตั้งค่า"},
    {"n": "ดูพร้อมกันได้กี่คน", "d": "ผู้ชมคนที่สองเข้าร่วมด้วยรหัสห้องเดียวกันได้ แต่เครื่องฝั่งทารกจะขออนุมัติบนหน้าจอของตัวเองก่อน จึงไม่มีใครดูได้ถ้าคนที่อยู่ในห้องไม่ยินยอม"}
  ],
  "ctaH": "ลองคืนนี้เลย",
  "ctaP": "หยิบอุปกรณ์สองเครื่อง เปิดเว็บไซต์บนทั้งสอง แล้วดูว่าเร็วแค่ไหน",
  "ctaBtn": "เปิด BabyPhone.online",
  "shotHome": "เปิดเว็บไซต์บนอุปกรณ์ใดก็ได้ ไม่ต้องติดตั้ง ไม่ต้องมีบัญชี",
  "shotParent": "เครื่องฝั่งผู้ปกครอง: ดูสดพร้อมพูดตอบกลับ เพลงกล่อม ไฟกลางคืน แจ้งเตือนเสียงร้อง และการบันทึก ทั้งหมดจากโทรศัพท์ของคุณ",
  "shotBaby": "เครื่องฝั่งทารก: กล้องสด รหัสห้องและคิวอาร์สำหรับจับคู่ พร้อมปุ่มควบคุมกล้อง ไมโครโฟน โหมดเสียงอย่างเดียว และม่านความเป็นส่วนตัว",
  "backToApp": "← กลับไปที่แอป",
  "readTime": "อ่าน 4 นาที",
  "updated": "อัปเดตกรกฎาคม 2026",
}

T['sw'] = {
  "title": "Geuza simu mbili kuwa kifaa cha bure cha kufuatilia mtoto | Mwongozo",
  "desc": "Jinsi ya kutengeneza kifaa cha bure cha kufuatilia mtoto kwa simu ya ziada au kompyuta kibao ya zamani: jinsi kifuatiliaji cha Wi-Fi kinavyofanya kazi, tofauti yake na kifaa maalum, na kila kipengele kinafanya nini.",
  "kicker": "MWONGOZO",
  "h1": "Simu mbili, kifuatiliaji kimoja cha bure: kila kitu BabyPhone.online inachoweza",
  "lede": "Hakuna kifaa cha kununua, hakuna programu ya kusakinisha, hakuna akaunti ya kufungua. Fungua tovuti kwenye vifaa viwili ulivyo navyo tayari, na utapata kifuatiliaji cha faragha chenye picha na sauti ya moja kwa moja — nyumbani na likizoni.",
  "introP": "Kifuatiliaji cha kawaida ni kifaa kingine cha kununua, kuchaji na kubeba. BabyPhone.online huchukua njia nyingine: vifaa ulivyo navyo vinakuwa kamera na kioo cha kufuatilia, moja kwa moja kwenye kivinjari. Hapa ni kwa nini hilo ni rahisi sana — na kila kitufe kinafanya nini.",
  "reuseH": "Ipe simu au kompyuta kibao ya zamani maisha ya pili",
  "reuseP": "Ile simu iliyo droo tangu ubadilishe mara mbili zilizopita, au kompyuta kibao ambayo watoto hawaitumii sana — yoyote kati yake inaweza kuwa kamera ya mtoto. Iegemeze kando ya kitanda cha mtoto, fungua babyphone.online, gusa „Kifaa cha mtoto\", nayo itatuma picha na sauti ya moja kwa moja kwenye simu yako. Hakuna haja ya kadi ya SIM: Wi-Fi ya nyumbani inatosha. Kamera halisi ya mtoto, bila kununua — wala kutupa — chochote.",
  "travelH": "Imeundwa kwa likizo na usiku wa mbali na nyumbani",
  "travelP": "Hapa ndipo inapong'aa zaidi. Ukiwa likizoni hutaki kubeba kifuatiliaji kikubwa chenye mawimbi ya umbali mfupi. Kwa BabyPhone.online unatumia tu simu mbili ambazo tayari unazibeba: acha moja chumbani hotelini au hemani pamoja na mtoto, chukua nyingine kwenda ukumbini au chumba cha jirani. Kwa kuwa muunganisho hupita kwenye intaneti (Wi-Fi au 4G/5G), umbali haukomei kwenye jengo moja na hufungwi na mawimbi ya kituo kikuu. Simu mbili, na umemaliza — popote ulipo.",
  "setupH": "Kuunganishwa ndani ya chini ya dakika moja",
  "setupP": "Kuunganisha kumefanywa rahisi kwa makusudi, ili uweze kufanya hata saa tisa usiku ukiwa nusu usingizi.",
  "steps": [
    "Kwenye kifaa kilicho karibu na mtoto, gusa „Kifaa cha mtoto\". Kitaonyesha msimbo wa herufi 6 na msimbo wa QR.",
    "Kwenye simu yako mwenyewe, gusa „Kifaa cha mzazi\".",
    "Andika msimbo au skani QR — utamwona na kumsikia mtoto papo hapo."
  ],
  "featH": "Kila kipengele, na kinatumika kwa nini",
  "featLede": "Kila kitu huendeshwa kutoka simu ya mzazi, huku kifaa cha mtoto kikituma tu. Hii ndiyo orodha kamili.",
  "features": [
    {"n": "Picha na sauti ya moja kwa moja", "d": "Mwone na msikie mtoto wako kwa wakati halisi, kwa ucheleweshaji mdogo — pia kwa 4G/5G, si Wi-Fi ya nyumbani tu."},
    {"n": "Kujibu kwa sauti", "d": "Gusa na useme: sauti yako husikika kwenye kifaa cha mtoto, hivyo unaweza kumtuliza bila kuingia chumbani."},
    {"n": "Nyimbo za kubembeleza na muziki", "d": "Cheza sauti tulivu au faili zako za MP3 kwenye kifaa cha mtoto, moja kwa moja kutoka simu yako."},
    {"n": "Taa ya usiku", "d": "Washa mwanga laini na wa joto kwenye skrini ya kifaa cha mtoto ukiwa upande wako wa muunganisho."},
    {"n": "Tahadhari ya kilio", "d": "Pata taarifa mtoto anapolia, kwa usikivu unaouweka mwenyewe, pamoja na kumbukumbu ya matukio."},
    {"n": "Kipima muda cha usingizi", "d": "Acha wimbo wa kubembeleza ucheze, kisha usimame wenyewe baada ya muda unaouchagua."},
    {"n": "Sauti pekee na pazia la faragha", "d": "Bakisha sauti lakini ufiche picha wakati wowote unapotaka video izimwe lakini masikio yabaki wazi."},
    {"n": "Hali ya betri", "d": "Ona kiwango cha betri ya kifaa cha mtoto kwenye skrini yako, ili kisizimike bila kutambuliwa."},
    {"n": "Rekodi kipande", "d": "Hifadhi kipande cha picha na sauti moja kwa moja kwenye kifaa chako. Hakuna kinachopakiwa popote."},
    {"n": "Huunganisha upya kila wakati", "d": "Hustahimili mabadiliko ya Wi-Fi na mtandao wa simu na skrini kuzimika, na hukujulisha mara muunganisho unapokatika."},
    {"n": "Lugha 30", "d": "Kiolesura chote kwa lugha yako — chagua mara moja na itakumbukwa."},
    {"n": "Bure, bila akaunti", "d": "Ufuatiliaji wa msingi ni bure na hauhitaji usajili. Fungua tovuti na uanze."}
  ],
  "privacyH": "Faragha tangu mwanzo wa muundo",
  "privacyP": "Picha na sauti husafiri moja kwa moja kati ya vifaa vyako viwili, kifaa hadi kifaa na vikiwa vimesimbwa njiani. Hakuna kinachorekodiwa, na hakuna seva inayoweza kutazama. Hakuna akaunti, hakuna matangazo, hakuna ufuatiliaji — ni vifaa vyako tu vinavyozungumza vyenyewe.",
  "worksH": "Hufanya kazi kwenye vifaa ulivyo navyo tayari",
  "worksP": "Simu, kompyuta kibao au kompyuta ndogo yoyote yenye kivinjari cha kisasa kiasi (Chrome, Safari, Firefox, Edge) itafaa — hata modeli za zamani, mradi kivinjari kimesasishwa vya kutosha. Kifaa cha upande wa mtoto kinahitaji kamera na maikrofoni; kiache kikiwa kwenye chaja na kitakutosha usiku mzima.",
  "wifiH": "Kifuatiliaji cha mtoto kupitia Wi-Fi hufanya kazi vipi hasa",
  "wifiP": "Kifuatiliaji cha kawaida ni jozi ya redio za masafa mafupi: kitengo cha kamera hutuma, kitengo cha mzazi hupokea, na ukuta mnene humaliza mazungumzo. Kifuatiliaji cha Wi-Fi hutuma picha na sauti kama data kupitia intaneti. BabyPhone.online hutumia WebRTC — teknolojia ileile ambayo kivinjari chako hutumia kwa simu za video — hivyo vifaa viwili hufungua njia ya moja kwa moja iliyosimbwa kati yao. Msimbo wa chumba husaidia tu kupatana mwanzoni, na kipitishio kilichosimbwa huingilia pale tu mtandao wako unapozuia njia ya moja kwa moja; hakuna kati yao kinachoweza kuona wala kusikia mtiririko. Tofauti ya kiutendaji: umbali haupimwi tena kwa mita, lakini vifaa vyote viwili lazima viwe mtandaoni.",
  "vsH": "Programu ya kufuatilia mtoto au kifaa maalum?",
  "vsLede": "Hakuna kinachoshinda moja kwa moja — vinashindwa kwa njia tofauti. Ulinganisho wa kweli.",
  "vs": [
    {"n": "Umbali", "d": "Kifaa maalum hufanya kazi popote ndani ya masafa yake ya redio na hakihitaji intaneti kabisa. Programu ina umbali usio na kikomo kiutendaji, lakini vifaa vyote viwili lazima viwe mtandaoni."},
    {"n": "Gharama", "d": "Kifuatiliaji chenye picha kinagharimu pesa halisi na kinakuwa taka ya kielektroniki mtoto anapokua. Hiki hakigharimu chochote na hutumia tena vifaa ulivyo navyo."},
    {"n": "Safari", "d": "Kituo kikuu, kamera na chaja mbili hujaza nusu ya begi. Simu mbili ambazo ulikuwa unazibeba tayari hazichukui nafasi yoyote."},
    {"n": "Kutegemewa", "d": "Kifaa maalum hufanya kazi moja, bila sasisho la mfumo wala simu inayoingia kuingilia. Simu inahitaji uangalifu: iache kwenye chaja, skrini iwe macho, programu nyingine zimefungwa."},
    {"n": "Faragha", "d": "Kamera za wingu huhifadhi picha kwenye seva za mtengenezaji; vifuatiliaji vya bei nafuu vya analogi vinaweza kunaswa na kipokezi cha karibu. Muunganisho wa kifaa hadi kifaa huepuka vyote viwili — lakini wewe ndiye unayeamua nani apate msimbo wa chumba."},
    {"n": "Kuona gizani", "d": "Vifaa maalum vina taa za infrared; kamera ya simu haiwezi hivyo. Katika chumba chenye giza totoro utasikia kila kitu lakini utaona kidogo — taa ya usiku iliyomo husaidia."}
  ],
  "faqH": "Maswali yanayoulizwa mara kwa mara",
  "faq": [
    {"n": "Je, programu ya kufuatilia mtoto ni salama?", "d": "Inategemea video inakwenda wapi na nani anaweza kujiunga. Hapa mtiririko hupita moja kwa moja kati ya vifaa vyako viwili na husimbwa njiani, hivyo hakuna akaunti ya wingu ya kuvunjwa wala picha kwenye seva ya mtu mwingine. Kifaa cha mtoto pia hakijibu chenyewe: kifaa kilichoskani QR hubeba ufunguo wa matumizi moja, na yeyote aliyeandika msimbo kwa mkono lazima aidhinishwe kwenye skrini ya kifaa cha mtoto."},
    {"n": "Je, hufanya kazi bila Wi-Fi?", "d": "Hiki kinahitaji intaneti kwenye vifaa vyote viwili — lakini si lazima Wi-Fi, wala si lazima mtandao uleule: kifaa cha mtoto kinaweza kuwa kwenye Wi-Fi wakati wewe uko kwenye 4G au 5G. Kama hakuna intaneti kabisa pande zote mbili, vifaa haviwezi kupatana, na hapo kifuatiliaji cha redio cha kawaida ndicho bora zaidi."},
    {"n": "Gharama ni kiasi gani?", "d": "Hakuna. Vipengele vyote ni bure, hakuna kiwango cha malipo wala akaunti, na tovuti haina matangazo wala vifuatiliaji."},
    {"n": "Je, naweza kutumia simu ya zamani?", "d": "Ndiyo, na hilo ndilo lengo. Simu au kompyuta kibao yoyote ya ziada yenye kamera, maikrofoni na kivinjari kilichosasishwa itatosha, ikiwa na kadi ya SIM au bila. Iache imeunganishwa kwenye umeme — kutuma video usiku mzima kunamaliza betri."},
    {"n": "Je, ninahitaji kusakinisha kitu?", "d": "Hapana. Vifaa vyote viwili hufungua tovuti tu. Hakuna cha kupakua, cha kujisajili wala cha kusanidi."},
    {"n": "Watu wangapi wanaweza kutazama kwa wakati mmoja?", "d": "Mtazamaji wa pili anaweza kujiunga kwa msimbo uleule wa chumba, lakini kifaa cha mtoto huomba idhini kwenye skrini yake kwanza — hivyo hakuna anayetazama bila mtu aliye chumbani kukubali."}
  ],
  "ctaH": "Jaribu usiku wa leo",
  "ctaP": "Chukua vifaa viwili, fungua tovuti kwenye vyote viwili, na uone jinsi ilivyo haraka.",
  "ctaBtn": "Fungua BabyPhone.online",
  "shotHome": "Fungua tovuti kwenye kifaa chochote — hakuna usakinishaji, hakuna akaunti.",
  "shotParent": "Kifaa cha mzazi: mwonekano wa moja kwa moja pamoja na kujibu kwa sauti, nyimbo za kubembeleza, taa ya usiku, tahadhari ya kilio na kurekodi — vyote kutoka simu yako.",
  "shotBaby": "Kifaa cha mtoto: kamera ya moja kwa moja, msimbo wa chumba na QR ya kuunganisha, pamoja na vidhibiti vya kamera, maikrofoni, sauti-pekee na pazia la faragha.",
  "backToApp": "← Rudi kwenye programu",
  "readTime": "Dakika 4 za kusoma",
  "updated": "Imesasishwa Julai 2026",
}
