# -*- coding: utf-8 -*-
T = {}

T['ha'] = {
  "title": "Mayar da wayoyi biyu zuwa na'urar sa ido kan jariri kyauta | Jagora",
  "desc": "Yadda ake yin na'urar sa ido kan jariri kyauta daga waya ta ajiya ko kwamfutar hannu tsohuwa: yadda na'urar sa ido ta Wi-Fi ke aiki, bambancinta da na'ura ta musamman, da abin da kowane fasali ke yi.",
  "kicker": "JAGORA",
  "h1": "Wayoyi biyu, na'urar sa ido kyauta guda: duk abin da BabyPhone.online ke iyawa",
  "lede": "Babu na'urar da za a saya, babu manhajar da za a sanya, babu asusun da za a buɗe. Buɗe gidan yanar gizon a kan na'urori biyu da kake da su tuni, sai ka sami na'urar sa ido ta sirri mai hoto da sauti kai tsaye — a gida da kuma lokacin hutu.",
  "introP": "Na'urar sa ido ta gargajiya na nufin ƙarin abu ɗaya da za ka saya, ka caja, ka kuma ɗauka. BabyPhone.online ya bi wata hanya dabam: na'urorin da kake da su su kansu su zama kyamara da allon sa ido, kai tsaye a cikin burauza. Ga dalilin da ya sa hakan yake da amfani sosai — da abin da kowane maɓalli ke yi.",
  "reuseH": "Ba tsohuwar waya ko kwamfutar hannu rai na biyu",
  "reuseP": "Wayar da ke kwance a aljihun tebur tun canji biyu da suka wuce, ko kwamfutar hannu da yara ba sa amfani da ita sosai — kowace daga cikinsu za ta iya zama kyamarar jariri. Ka jingina ta kusa da gadon jariri, ka buɗe babyphone.online, ka danna „Na'urar jariri\", sai ta fara aika hoto da sauti kai tsaye zuwa wayarka. Ba a buƙatar katin SIM: Wi-Fi na gida ya isa. Kyamarar jariri ta gaskiya, ba tare da sayen — ko zubar da — komai ba.",
  "travelH": "An yi shi don hutu da darare a wajen gida",
  "travelP": "Nan ne yake haskakawa. A lokacin hutu ba za ka so ka ɗauki babbar na'ura mai sigina na ɗan gajeren zango ba. Da BabyPhone.online kana amfani da wayoyi biyu da tuni kake ɗauke da su: ka bar ɗaya a ɗakin otel ko tanti tare da jaririn, ka ɗauki ɗayan zuwa baranda ko ɗakin makwabci. Tunda haɗin yana ratsa Intanet (Wi-Fi ko 4G/5G), zangon bai tsaya kan gini ɗaya ba kuma ba ka ɗaure da siginar tashar tushe. Wayoyi biyu, shi ke nan — a duk inda kake.",
  "setupH": "Haɗi cikin ƙasa da minti ɗaya",
  "setupP": "An sauƙaƙa haɗawa da gangan, don ka iya yin sa da ƙarfe uku na dare kana rabin barci.",
  "steps": [
    "A kan na'urar da ke kusa da jaririn, ka danna „Na'urar jariri\". Za ta nuna lamba mai haruffa 6 da lambar QR.",
    "A kan wayarka, ka danna „Na'urar iyaye\".",
    "Ka rubuta lambar ko ka duba QR — nan take za ka ga jaririn ka kuma ji shi."
  ],
  "featH": "Kowane fasali, da abin da yake yi",
  "featLede": "Komai ana sarrafa shi daga wayar iyaye, yayin da na'urar jariri kawai take aikawa. Ga cikakken jerin.",
  "features": [
    {"n": "Hoto da sauti kai tsaye", "d": "Ka ga jaririnka ka kuma ji shi a lokaci guda da ɗan jinkiri kaɗan — haka ma ta 4G/5G, ba Wi-Fi na gida kaɗai ba."},
    {"n": "Amsawa da murya", "d": "Ka danna ka yi magana: muryarka na fitowa daga na'urar jariri, don haka za ka iya kwantar da hankalinsa ba tare da shiga ɗakin ba."},
    {"n": "Waƙoƙin bacci da kiɗa", "d": "Ka kunna sautuka masu sanyaya rai ko fayilolin MP3 naka a na'urar jariri, kai tsaye daga wayarka."},
    {"n": "Fitilar dare", "d": "Ka kunna haske mai laushi da ɗumi a allon na'urar jariri daga gefenka na haɗin."},
    {"n": "Faɗakarwar kuka", "d": "Ka sami sanarwa idan jaririn ya yi kuka, da matakin ji da kai kanka ka saita, tare da tarihin abubuwan da suka faru."},
    {"n": "Agogon bacci", "d": "Bar waƙar bacci ta kunna sannan ta tsaya da kanta bayan lokacin da ka zaɓa."},
    {"n": "Sauti kaɗai da labulen sirri", "d": "Ka riƙe sautin amma ka ɓoye hoton duk lokacin da kake son kashe bidiyo amma kunnenka a buɗe."},
    {"n": "Halin baturi", "d": "Ka ga matakin baturin na'urar jariri a allonka, don kada ya mutu ba tare da ka sani ba."},
    {"n": "Yi rikodin ɗan lokaci", "d": "Ka adana wani lokaci na hoto da sauti kai tsaye a na'urarka. Ba a ɗora komai a ko'ina."},
    {"n": "Kullum yana sake haɗuwa", "d": "Yana jure canjin Wi-Fi da na'urar sadarwa da kashe allo, kuma yana sanar da kai nan take idan haɗin ya yanke."},
    {"n": "Harsuna 30", "d": "Duk fuskar shirin da harshenka — ka zaɓa sau ɗaya sai a tuna."},
    {"n": "Kyauta, babu asusu", "d": "Sa ido na asali kyauta ne kuma ba ya buƙatar rajista. Ka buɗe gidan yanar gizon ka fara."}
  ],
  "privacyH": "Sirri tun daga ƙira",
  "privacyP": "Hoto da sauti suna tafiya kai tsaye tsakanin na'urorinka biyu, daga na'ura zuwa na'ura kuma a ɓoye a hanya. Ba a yin rikodin komai, kuma babu uwar garken da za ta iya kallo. Babu asusu, babu tallace-tallace, babu bin diddigi — na'urorinka kawai suna magana da juna.",
  "worksH": "Yana aiki a kan na'urorin da kake da su tuni",
  "worksP": "Duk wata waya, kwamfutar hannu ko kwamfutar tafi-da-gidanka mai burauza mai sabo kaɗan (Chrome, Safari, Firefox, Edge) za ta yi aiki — har da tsofaffin samfura, muddin burauzar tana da sabuntawa isasshe. Na'urar gefen jariri tana buƙatar kyamara da makurufo; ka bar ta a caja sai ta isar da dare gaba ɗaya.",
  "wifiH": "Yadda na'urar sa ido kan jariri ta Wi-Fi ke aiki da gaske",
  "wifiP": "Na'urar sa ido ta gargajiya rediyo biyu ne masu ɗan gajeren zango: sashen kyamara yana aikawa, sashen iyaye yana karɓa, kuma bango mai kauri yana kawo ƙarshen zance. Na'urar Wi-Fi kuwa tana aika hoto da sauti a matsayin bayanai ta Intanet. BabyPhone.online yana amfani da WebRTC — fasaha ɗaya da burauzarka ke amfani da ita don kiran bidiyo — don haka na'urorin biyu suna buɗe hanya kai tsaye kuma a ɓoye tsakaninsu. Lambar ɗaki tana taimaka musu su gano juna a farkon kawai, kuma na'urar juyawa da aka ɓoye tana shigowa ne kawai idan hanyar sadarwarka ta toshe hanyar kai tsaye; babu ɗaya daga cikinsu da zai iya gani ko jin abin da ke tafiya. Bambancin aiki: zango ba a auna shi da mita kuma, amma dole na'urorin biyu su kasance a kan layi.",
  "vsH": "Manhajar sa ido ko na'ura ta musamman?",
  "vsLede": "Babu wanda ya yi nasara gaba ɗaya — kowanne yana gazawa ta hanya dabam. Kwatanci na gaskiya.",
  "vs": [
    {"n": "Zango", "d": "Na'ura ta musamman tana aiki a duk inda take cikin zangon rediyonta kuma ba ta buƙatar Intanet ko kaɗan. Manhaja tana da zango marar iyaka a aikace, amma dole na'urorin biyu su kasance a kan layi."},
    {"n": "Kuɗi", "d": "Na'urar sa ido mai hoto tana ci kuɗi na gaske kuma ta zama sharar lantarki idan yaro ya girma. Wannan ba ya ci komai kuma yana sake amfani da na'urorin da kake da su."},
    {"n": "Tafiya", "d": "Tashar tushe, kyamara da caja biyu suna cika rabin jaka. Wayoyi biyu da tuni kake ɗauke da su ba sa ɗaukar wuri ko kaɗan."},
    {"n": "Aminci", "d": "Na'ura ta musamman tana aiki ɗaya, babu sabunta tsarin ko kiran shigowa da zai katse. Waya tana buƙatar kulawa: ka bar ta a caja, allo a farke, sauran manhajoji a rufe."},
    {"n": "Sirri", "d": "Kyamarorin girgije suna ajiye hotuna a uwayen garken masana'anta; na'urorin analog masu arha wani mai karɓa da ke kusa zai iya kama su. Haɗin na'ura-zuwa-na'ura yana guje wa duka biyu — amma kai ne ka yanke shawarar wa zai sami lambar ɗaki."},
    {"n": "Gani cikin duhu", "d": "Na'urori na musamman suna da fitilun infrared; kyamarar waya ba ta iya hakan. A cikin ɗaki mai duhu ƙirin za ka ji komai amma ka gani kaɗan — fitilar dare da ke ciki tana taimakawa."}
  ],
  "faqH": "Tambayoyin da ake yawan yi",
  "faq": [
    {"n": "Shin manhajar sa ido kan jariri tana da tsaro?", "d": "Ya danganta da inda bidiyon zai je da kuma wanda zai iya shiga. Anan rafin yana tafiya kai tsaye tsakanin na'urorinka biyu kuma an ɓoye shi a hanya, don haka babu asusun girgije da za a fasa, babu kuma hoton da ke uwar garken wani. Na'urar jariri ba ta amsawa da kanta: na'urar da ta duba QR tana ɗauke da maɓalli na amfani sau ɗaya, kuma duk wanda ya rubuta lambar da hannu dole a amince da shi a kan allon na'urar jariri."},
    {"n": "Shin yana aiki ba tare da Wi-Fi ba?", "d": "Wannan yana buƙatar Intanet a kan na'urorin biyu — amma ba dole ba ne Wi-Fi, kuma ba dole ba ne hanyar sadarwa ɗaya: na'urar jariri na iya kasancewa a Wi-Fi yayin da kai kake a 4G ko 5G. Idan babu Intanet ko kaɗan a bangarorin biyu, na'urorin ba za su iya gano juna ba, kuma a nan na'urar rediyo ta gargajiya ita ce mafi dacewa."},
    {"n": "Nawa ne kuɗinsa?", "d": "Babu ko sisi. Duk fasalolin kyauta ne, babu matakin biya kuma babu asusu, kuma gidan yanar gizon ba shi da tallace-tallace ko na'urorin bin diddigi."},
    {"n": "Zan iya amfani da tsohuwar waya?", "d": "Eh, kuma hakan ne manufar. Duk wata waya ko kwamfutar hannu ta ajiya mai kyamara, makurufo da burauza mai sabuntawa za ta yi, ko da tana da katin SIM ko babu. Ka bar ta a haɗe da wutar lantarki — aika bidiyo dukan dare yana cinye baturi."},
    {"n": "Ina buƙatar sanya wani abu?", "d": "A'a. Na'urorin biyu suna buɗe gidan yanar gizon kawai. Babu abin saukewa, babu rajista, babu kuma saitin komai."},
    {"n": "Mutane nawa za su iya kallo a lokaci guda?", "d": "Mai kallo na biyu zai iya shiga da lambar ɗaki ɗaya, amma na'urar jariri tana neman izini a kan allonta da farko — don haka babu wanda zai kalla ba tare da wani da ke cikin ɗakin ya amince ba."}
  ],
  "ctaH": "Gwada shi yau da dare",
  "ctaP": "Ka ɗauki na'urori biyu, ka buɗe gidan yanar gizon a kansu duka, ka ga yadda yake da sauri.",
  "ctaBtn": "Buɗe BabyPhone.online",
  "shotHome": "Buɗe gidan yanar gizon a kowace na'ura — babu shigarwa, babu asusu.",
  "shotParent": "Na'urar iyaye: kallo kai tsaye tare da amsawa da murya, waƙoƙin bacci, fitilar dare, faɗakarwar kuka da rikodi — duka daga wayarka.",
  "shotBaby": "Na'urar jariri: kyamara kai tsaye, lambar ɗaki da QR na haɗawa, tare da sarrafa kyamara, makurufo, sauti-kaɗai da labulen sirri.",
  "backToApp": "← Koma zuwa manhajar",
  "readTime": "Karatun minti 4",
  "updated": "An sabunta Yuli 2026",
}

T['ro'] = {
  "title": "Transformă două telefoane într-un monitor gratuit pentru bebeluși | Ghid",
  "desc": "Cum faci un monitor gratuit pentru bebeluși dintr-un telefon de rezervă sau o tabletă veche: cum funcționează un monitor prin Wi-Fi, prin ce diferă de un aparat dedicat și la ce folosește fiecare funcție.",
  "kicker": "GHID",
  "h1": "Două telefoane, un monitor gratuit: tot ce poate face BabyPhone.online",
  "lede": "Nicio cutie de cumpărat, nicio aplicație de instalat, niciun cont de creat. Deschide site-ul pe două dispozitive pe care le ai deja și ai un monitor privat cu imagine și sunet live — acasă sau în vacanță.",
  "introP": "Un monitor clasic înseamnă încă un aparat de cumpărat, de încărcat și de cărat. BabyPhone.online alege alt drum: dispozitivele pe care le ai deja devin camera și monitorul, direct în browser. Iată de ce e atât de practic — și ce face fiecare buton.",
  "reuseH": "Dă-i telefonului sau tabletei vechi o a doua viață",
  "reuseP": "Telefonul rămas în sertar de două schimbări încoace sau tableta pe care copiii abia o folosesc — oricare dintre ele devine camera bebelușului. Sprijină-l lângă pătuț, deschide babyphone.online, apasă „Unitatea bebelușului\", iar el transmite imagine și sunet live pe telefonul tău. Nu e nevoie de cartelă SIM: Wi-Fi-ul de acasă e de ajuns. O cameră adevărată pentru bebeluș, fără să cumperi — sau să arunci — nimic.",
  "travelH": "Făcut pentru vacanțe și nopți departe de casă",
  "travelP": "Aici strălucește cu adevărat. În vacanță nu vrei să cari un monitor voluminos cu semnalul lui de rază scurtă. Cu BabyPhone.online folosești pur și simplu cele două telefoane pe care oricum le ai la tine: unul rămâne în camera de hotel sau în cort, lângă bebeluș, celălalt merge cu tine pe terasă sau în camera alăturată. Fiindcă legătura trece prin internet (Wi-Fi sau 4G/5G), raza nu se oprește la pereții unei clădiri și nu depinzi de semnalul unei stații de bază. Două telefoane și ești gata — oriunde.",
  "setupH": "Conectat în mai puțin de un minut",
  "setupP": "Asocierea e făcută intenționat simplă, ca s-o poți face și la trei dimineața, pe jumătate adormit.",
  "steps": [
    "Pe dispozitivul de lângă bebeluș, apasă „Unitatea bebelușului\". Afișează un cod de 6 caractere și un cod QR.",
    "Pe telefonul tău, apasă „Unitatea părintelui\".",
    "Scrie codul sau scanează QR-ul — vezi și auzi imediat bebelușul."
  ],
  "featH": "Fiecare funcție și la ce folosește",
  "featLede": "Totul se comandă de pe telefonul părintelui, în timp ce dispozitivul bebelușului doar transmite. Iată lista completă.",
  "features": [
    {"n": "Imagine și sunet live", "d": "Vezi și auzi bebelușul în timp real, cu întârziere mică — și pe 4G/5G, nu doar pe Wi-Fi-ul de acasă."},
    {"n": "Vorbește înapoi", "d": "Apeși și vorbești: vocea ta se aude pe dispozitivul bebelușului, așa că îl liniștești fără să intri în cameră."},
    {"n": "Cântece de leagăn și muzică", "d": "Pornește sunete liniștitoare sau propriile fișiere MP3 pe dispozitivul bebelușului, direct de pe telefon."},
    {"n": "Lumină de noapte", "d": "Aprinde o lumină caldă și blândă pe ecranul dispozitivului bebelușului, din partea ta a legăturii."},
    {"n": "Alertă de plâns", "d": "Primești alertă când bebelușul plânge, cu o sensibilitate pe care o alegi tu, plus un jurnal al evenimentelor."},
    {"n": "Cronometru de somn", "d": "Lasă cântecul de leagăn să meargă și să se oprească singur după timpul ales de tine."},
    {"n": "Doar sunet și perdea de intimitate", "d": "Păstrează sunetul și ascunde imaginea ori de câte ori vrei video oprit, dar urechile deschise."},
    {"n": "Starea bateriei", "d": "Vezi nivelul bateriei dispozitivului bebelușului pe ecranul tău, ca să nu se descarce pe neobservate."},
    {"n": "Înregistrează un fragment", "d": "Salvează un moment cu imagine și sunet direct pe dispozitivul tău. Nimic nu se încarcă nicăieri."},
    {"n": "Se reconectează mereu", "d": "Trece peste comutarea Wi-Fi/mobil și peste ecranul stins, și te anunță în clipa în care legătura cade."},
    {"n": "30 de limbi", "d": "Toată interfața în limba ta — alegi o dată și se ține minte."},
    {"n": "Gratuit, fără cont", "d": "Monitorizarea de bază e gratuită și nu cere înregistrare. Deschizi site-ul și pornești."}
  ],
  "privacyH": "Privat prin construcție",
  "privacyP": "Imaginea și sunetul circulă direct între cele două dispozitive ale tale, de la dispozitiv la dispozitiv și criptate pe drum. Nu se înregistrează nimic și niciun server nu poate privi. Fără cont, fără reclame, fără urmărire — doar dispozitivele tale care vorbesc între ele.",
  "worksH": "Merge pe dispozitivele pe care le ai deja",
  "worksP": "Orice telefon, tabletă sau laptop cu un browser relativ recent (Chrome, Safari, Firefox, Edge) e suficient — inclusiv modele mai vechi, atâta timp cât browserul e rezonabil de actualizat. Dispozitivul din partea bebelușului are nevoie de cameră și microfon; lasă-l pe încărcător și îți ajunge toată noaptea.",
  "wifiH": "Cum funcționează de fapt un monitor pentru bebeluși prin Wi-Fi",
  "wifiP": "Un monitor clasic e o pereche de stații radio cu rază scurtă: unitatea cu cameră emite, unitatea părintelui recepționează, iar un perete gros încheie conversația. Un monitor prin Wi-Fi trimite imaginea și sunetul ca date prin internet. BabyPhone.online folosește WebRTC — aceeași tehnologie pe care browserul o folosește pentru apeluri video — așa că cele două dispozitive deschid între ele o legătură directă și criptată. Codul camerei le ajută doar să se găsească la început, iar un releu criptat intervine numai când rețeaua ta blochează calea directă; niciunul nu poate vedea sau auzi fluxul. Diferența practică: raza nu se mai măsoară în metri, dar ambele dispozitive trebuie să fie online.",
  "vsH": "Aplicație de monitorizare sau aparat dedicat?",
  "vsLede": "Niciunul nu câștigă clar — dau greș în moduri diferite. O comparație onestă.",
  "vs": [
    {"n": "Rază", "d": "Un aparat dedicat merge oriunde în raza lui radio și nu are nevoie deloc de internet. O aplicație are rază practic nelimitată, dar ambele dispozitive trebuie să fie online."},
    {"n": "Cost", "d": "Un monitor video costă bani reali și devine deșeu electronic când copilul crește. Acesta nu costă nimic și refolosește aparatura pe care o ai deja."},
    {"n": "Călătorii", "d": "O stație de bază, o cameră și două încărcătoare umplu jumătate de geantă. Două telefoane pe care oricum le cărai nu ocupă nimic."},
    {"n": "Fiabilitate", "d": "Un aparat dedicat face un singur lucru, fără actualizări de sistem sau apeluri care să intervină. Telefonul cere grijă: ține-l pe încărcător, ecranul treaz, celelalte aplicații închise."},
    {"n": "Confidențialitate", "d": "Camerele din cloud păstrează înregistrările pe serverele producătorului; monitoarele analogice ieftine pot fi prinse de un receptor din apropiere. O legătură directă între dispozitive le evită pe amândouă — dar tu decizi cui îi dai codul camerei."},
    {"n": "Vedere pe timp de noapte", "d": "Aparatele dedicate au LED-uri infraroșu; camera telefonului nu poate face asta. Într-o cameră complet întunecată vei auzi totul și vei vedea puțin — lumina de noapte inclusă ajută."}
  ],
  "faqH": "Întrebări frecvente",
  "faq": [
    {"n": "Este sigură o aplicație de monitorizare?", "d": "Depinde unde ajunge imaginea și cine se poate conecta. Aici fluxul merge direct între cele două dispozitive ale tale și e criptat pe drum, așa că nu există un cont în cloud care să fie spart și nicio înregistrare pe serverul altcuiva. Nici unitatea bebelușului nu răspunde automat: dispozitivul care a scanat QR-ul poartă o cheie de unică folosință, iar oricine scrie codul manual trebuie aprobat pe ecranul dispozitivului bebelușului."},
    {"n": "Funcționează fără Wi-Fi?", "d": "Acesta are nevoie de internet pe ambele dispozitive — dar nu neapărat Wi-Fi și nici aceeași rețea: dispozitivul bebelușului poate fi pe Wi-Fi în timp ce tu ești pe 4G sau 5G. Dacă nu există deloc internet de nicio parte, dispozitivele nu se pot găsi, iar atunci un monitor radio clasic e unealta potrivită."},
    {"n": "Cât costă?", "d": "Nimic. Toate funcțiile sunt gratuite, nu există variantă cu plată și nici cont, iar site-ul nu are reclame și nici urmăritoare."},
    {"n": "Pot folosi un telefon vechi?", "d": "Da, tocmai asta e ideea. Orice telefon sau tabletă de rezervă cu cameră, microfon și un browser actualizat e suficient, cu sau fără cartelă SIM. Ține-l în priză — transmisia video toată noaptea consumă bateria."},
    {"n": "Trebuie să instalez ceva?", "d": "Nu. Ambele dispozitive doar deschid site-ul. Nu e nimic de descărcat, nimic la care să te înscrii și nimic de configurat."},
    {"n": "Câți oameni pot privi în același timp?", "d": "Un al doilea privitor se poate conecta cu același cod al camerei, dar unitatea bebelușului cere mai întâi aprobare pe propriul ecran — așa că nimeni nu privește fără acordul cuiva aflat în cameră."}
  ],
  "ctaH": "Încearcă diseară",
  "ctaP": "Ia două dispozitive, deschide site-ul pe amândouă și vezi cât de repede merge.",
  "ctaBtn": "Deschide BabyPhone.online",
  "shotHome": "Deschide site-ul pe orice dispozitiv — fără instalare, fără cont.",
  "shotParent": "Unitatea părintelui: vizualizare live cu vorbit înapoi, cântece de leagăn, lumină de noapte, alertă de plâns și înregistrare — toate de pe telefonul tău.",
  "shotBaby": "Unitatea bebelușului: cameră live, codul camerei și QR pentru asociere, cu comenzi pentru cameră, microfon, mod doar-sunet și perdea de intimitate.",
  "backToApp": "← Înapoi la aplicație",
  "readTime": "4 min de citit",
  "updated": "Actualizat în iulie 2026",
}
