# -*- coding: utf-8 -*-
T = {}

T['pt'] = {
  "title": "Como é protegido o seu intercomunicador para bebé? | BabyPhone.online",
  "desc": "Como funciona o BabyPhone.online e como o vídeo e o som em direto entre os seus dispositivos são protegidos pela tecnologia moderna do navegador e pelo WebRTC.",
  "kicker": "SEGURANÇA E PRIVACIDADE",
  "h1": "Como funciona o BabyPhone.online — e como a sua ligação se mantém privada",
  "lede": "O BabyPhone.online transforma dois dispositivos que já tem num intercomunicador para bebé. Um fica junto do bebé, o outro vai consigo. Aqui explicamos como a ligação é feita e como a segurança moderna do navegador protege o seu vídeo e som em direto — em linguagem simples, sem jargão.",
  "readTime": "5 min de leitura",
  "updated": "Atualizado em agosto de 2026",
  "cardH": "A privacidade começa no desenho",
  "cardP": "O objetivo é simples: só os dois dispositivos que emparelhou participam na sessão em direto.",
  "cardList": [
    "O seu navegador pede ele próprio permissão para a câmara e o microfone.",
    "O WebRTC cifra o vídeo e o som em direto enquanto viajam.",
    "Emparelhar por código QR evita copiar códigos longos."
  ],
  "introP": "Um intercomunicador clássico são dois rádios de curto alcance que é preciso comprar, carregar e levar. O BabyPhone.online segue outro caminho: os seus próprios dispositivos passam a ser a câmara e o monitor, diretamente no navegador. Isso levanta uma pergunta justa — se funciona pela Internet, quem mais pode ver?",
  "stepsH": "De dois dispositivos a um intercomunicador em quatro passos",
  "stepsP": "Não é preciso hardware especial. Basta um telemóvel, um tablet ou um portátil com um navegador atual.",
  "steps": [
    "Abra o site no dispositivo que quer colocar junto do bebé.",
    "O navegador pede permissão para a câmara e o microfone. Sem a sua permissão, o site não lhes acede.",
    "Use o código QR para ligar o segundo dispositivo à mesma sessão.",
    "Os dois navegadores criam uma ligação direta em tempo real para imagem e som."
  ],
  "flowH": "A sua imagem em direto não é enviada como vídeo comum e desprotegido",
  "flowP": "O BabyPhone.online usa WebRTC: a tecnologia do navegador criada para áudio e vídeo em tempo real — a mesma que o navegador usa para videochamadas.",
  "flowBaby": "Dispositivo do bebé",
  "flowBabySub": "câmara + microfone",
  "flowLink": "WebRTC",
  "flowLinkSub": "ligação de média cifrada",
  "flowParent": "Dispositivo dos pais",
  "flowParentSub": "monitor em direto",
  "flowNote": "Consoante a rede, o WebRTC liga os dois dispositivos diretamente ou faz passar o tráfego cifrado por um servidor de retransmissão (TURN) quando o caminho direto está bloqueado.",
  "layersH": "Quatro camadas de proteção, explicadas de forma simples",
  "layers": [
    {"n": "1. O HTTPS protege a ligação ao site",
     "d": "O seu navegador chega ao BabyPhone.online por HTTPS. Isso ajuda a impedir que outros na rede leiam ou alterem a página pelo caminho."},
    {"n": "2. O WebRTC protege o vídeo e o som em direto",
     "d": "O WebRTC usa transporte seguro para média em tempo real, por isso o fluxo não atravessa a Internet como dados legíveis e desprotegidos."},
    {"n": "3. É você que autoriza a câmara e o microfone",
     "d": "O site não pode ligar a câmara em silêncio. O navegador mostra o seu próprio pedido de permissão, e pode retirá-la mais tarde."},
    {"n": "4. O código QR liga a sessão certa",
     "d": "Ler o código evita erros de escrita e o dispositivo que lê recebe uma chave de utilização única. Quem escrever o código à mão tem ainda de ser aprovado no ecrã do próprio dispositivo do bebé."}
  ],
  "honestH": "O que significa realmente «cifrado»?",
  "honestP": "A cifragem importa, mas segurança a sério é mais do que um cadeado. Por isso, eis o que a tecnologia faz — e o que não faz.",
  "doesH": "O que o WebRTC faz",
  "does": [
    "Cifra o vídeo e o som em direto enquanto viajam.",
    "Liga os seus dispositivos diretamente sempre que a rede o permita.",
    "Faz passar média cifrada por um retransmissor quando não é possível uma ligação direta."
  ],
  "youH": "O que também deve fazer",
  "you": [
    "Não partilhe o seu código QR. Quem vir um código de emparelhamento ativo pode tentar entrar nessa sessão.",
    "Bloqueie os seus dispositivos. Um telemóvel desbloqueado é um risco maior do que a própria ligação à Internet.",
    "Mantenha o navegador atualizado. As atualizações de segurança do iOS, do Android e do navegador continuam a ser importantes."
  ],
  "noticeLead": "Vale a pena saber:",
  "notice": " «cifrado» não significa automaticamente que todas as aplicações usam o mesmo modelo de segurança. O WhatsApp tem o seu próprio protocolo ponta a ponta com chaves de identidade. O BabyPhone.online usa a segurança integrada no WebRTC para média em direto no navegador. O objetivo — nunca enviar imagem ou som desprotegidos pela Internet — é comparável, mas a arquitetura é diferente. Preferimos dizê-lo com clareza a pedir emprestada a afirmação de outros.",
  "designH": "Um intercomunicador deve saber o mínimo possível sobre a sua família",
  "designP": "É esse o princípio do BabyPhone.online: o menor número de passos possível, nenhum acesso desnecessário ao seu dispositivo, sem conta, sem publicidade, sem rastreio, e uma ligação temporária entre os dois dispositivos que emparelhou. Nada é gravado e nenhum servidor assiste.",
  "faqH": "Segurança em resumo",
  "faq": [
    {"n": "Alguém pode simplesmente ligar a minha câmara?",
     "d": "Não sem a permissão de câmara do seu navegador. Além disso, entrar numa sessão em direto exige o emparelhamento correto, e um segundo espetador tem de ser aprovado no ecrã do dispositivo do bebé. Por isso, nunca partilhe publicamente um código QR ou código de sala ativo."},
    {"n": "O BabyPhone.online pode ver a minha imagem pelo caminho?",
     "d": "O WebRTC cifra a média em direto enquanto viaja. Quando é preciso um servidor de retransmissão porque a sua rede bloqueia o caminho direto, ele apenas deixa passar a média protegida — não a consegue ver nem ouvir."},
    {"n": "Isto é o mesmo que o WhatsApp?",
     "d": "Não literalmente. O WhatsApp usa o seu próprio protocolo ponta a ponta com chaves de identidade; o BabyPhone.online usa WebRTC para média segura em tempo real no navegador. O propósito é comparável, a arquitetura técnica não."},
    {"n": "O que posso fazer para máxima segurança?",
     "d": "Use um dispositivo e um navegador atualizados, mantenha privados o código de sala e o QR, ative o bloqueio de ecrã, feche a sessão quando terminar e abra o BabyPhone.online apenas pelo endereço HTTPS oficial."}
  ],
  "ctaH": "Quer experimentar?",
  "ctaP": "Dois dispositivos, sem instalação, sem conta. Abra o site em ambos e emparelhe-os.",
  "ctaBtn": "Abrir o BabyPhone.online",
  "toBlog": "Leia o guia completo: tudo o que o BabyPhone.online faz →",
  "backToApp": "← Voltar à aplicação",
}

T['it'] = {
  "title": "Come è protetto il tuo baby monitor? | BabyPhone.online",
  "desc": "Come funziona BabyPhone.online e come video e audio in diretta tra i tuoi dispositivi sono protetti dalla moderna tecnologia del browser e da WebRTC.",
  "kicker": "SICUREZZA E PRIVACY",
  "h1": "Come funziona BabyPhone.online — e come la tua connessione resta privata",
  "lede": "BabyPhone.online trasforma due dispositivi che hai già in un baby monitor. Uno resta vicino al bambino, l'altro va con te. Qui spieghiamo come nasce la connessione e come la sicurezza moderna del browser protegge video e audio in diretta — in parole semplici, senza gergo tecnico.",
  "readTime": "5 min di lettura",
  "updated": "Aggiornato ad agosto 2026",
  "cardH": "La privacy parte dal progetto",
  "cardP": "L'obiettivo è semplice: solo i due dispositivi che hai associato tu partecipano alla sessione in diretta.",
  "cardList": [
    "È il browser stesso a chiedere il permesso per fotocamera e microfono.",
    "WebRTC cifra video e audio in diretta mentre viaggiano.",
    "L'associazione con codice QR evita di ricopiare codici lunghi."
  ],
  "introP": "Un baby monitor classico è una coppia di radio a corto raggio da comprare, ricaricare e portarsi dietro. BabyPhone.online sceglie un'altra strada: i tuoi dispositivi diventano la telecamera e il monitor, direttamente nel browser. È lecito chiedersi — se passa da Internet, chi altro può guardare?",
  "stepsH": "Da due dispositivi a un baby monitor in quattro passi",
  "stepsP": "Non serve hardware dedicato. Bastano uno smartphone, un tablet o un portatile con un browser recente.",
  "steps": [
    "Apri il sito sul dispositivo che vuoi mettere vicino al bambino.",
    "Il browser chiede il permesso per fotocamera e microfono. Senza il tuo consenso il sito non vi accede.",
    "Usa il codice QR per collegare il secondo dispositivo alla stessa sessione.",
    "I due browser creano un collegamento diretto in tempo reale per video e audio."
  ],
  "flowH": "La tua immagine in diretta non viaggia come un video normale e non protetto",
  "flowP": "BabyPhone.online usa WebRTC: la tecnologia del browser nata per audio e video in tempo reale — la stessa delle videochiamate.",
  "flowBaby": "Dispositivo bambino",
  "flowBabySub": "fotocamera + microfono",
  "flowLink": "WebRTC",
  "flowLinkSub": "collegamento media cifrato",
  "flowParent": "Dispositivo genitore",
  "flowParentSub": "monitor in diretta",
  "flowNote": "A seconda della rete, WebRTC collega i due dispositivi direttamente oppure fa passare il traffico cifrato attraverso un server di inoltro (TURN) quando la via diretta è bloccata.",
  "layersH": "Quattro livelli di protezione, spiegati semplicemente",
  "layers": [
    {"n": "1. HTTPS protegge la connessione al sito",
     "d": "Il browser raggiunge BabyPhone.online tramite HTTPS. Questo aiuta a impedire che altri sulla rete leggano o modifichino la pagina lungo il percorso."},
    {"n": "2. WebRTC protegge video e audio in diretta",
     "d": "WebRTC usa un trasporto sicuro per i media in tempo reale, così il flusso non attraversa Internet come dati leggibili e non protetti."},
    {"n": "3. Sei tu ad autorizzare fotocamera e microfono",
     "d": "Il sito non può accendere la fotocamera di nascosto. È il browser a mostrare la propria richiesta, e puoi revocare il permesso in seguito."},
    {"n": "4. Il codice QR collega la sessione giusta",
     "d": "La scansione elimina gli errori di battitura e il dispositivo che scansiona riceve una chiave monouso. Chi digita il codice a mano deve comunque essere approvato sullo schermo del dispositivo del bambino."}
  ],
  "honestH": "Che cosa significa davvero «cifrato»?",
  "honestP": "La cifratura conta, ma la sicurezza vera è più di un lucchetto. Ecco quindi che cosa fa la tecnologia — e che cosa non fa.",
  "doesH": "Che cosa fa WebRTC",
  "does": [
    "Cifra video e audio in diretta mentre viaggiano.",
    "Collega i dispositivi direttamente ogni volta che la rete lo consente.",
    "Fa passare i media cifrati da un inoltro quando una connessione diretta non è possibile."
  ],
  "youH": "Che cosa devi fare anche tu",
  "you": [
    "Non condividere il codice QR. Chi vede un codice di associazione attivo può provare a entrare nella sessione.",
    "Blocca i dispositivi. Un telefono sbloccato è un rischio maggiore della connessione Internet stessa.",
    "Tieni aggiornato il browser. Gli aggiornamenti di sicurezza di iOS, Android e del browser restano importanti."
  ],
  "noticeLead": "Da sapere:",
  "notice": " «cifrato» non significa automaticamente che ogni app usi lo stesso modello di sicurezza. WhatsApp ha un proprio protocollo end-to-end con chiavi di identità. BabyPhone.online usa la sicurezza integrata in WebRTC per i media in diretta nel browser. L'obiettivo — non inviare mai audio o video non protetti su Internet — è paragonabile, ma l'architettura è diversa. Preferiamo dirlo chiaramente piuttosto che prendere in prestito l'affermazione di altri.",
  "designH": "Un baby monitor dovrebbe sapere il meno possibile della tua famiglia",
  "designP": "È questo il principio di BabyPhone.online: meno passaggi possibile, nessun accesso inutile al dispositivo, nessun account, nessuna pubblicità, nessun tracciamento e un collegamento temporaneo tra i due dispositivi che hai associato tu. Non viene registrato nulla e nessun server guarda.",
  "faqH": "La sicurezza in breve",
  "faq": [
    {"n": "Qualcuno può accendere la mia fotocamera così, senza altro?",
     "d": "Non senza il permesso della fotocamera dato al browser. Inoltre, per entrare in una sessione in diretta serve l'associazione corretta, e un secondo spettatore deve essere approvato sullo schermo del dispositivo del bambino. Quindi non condividere mai pubblicamente un codice QR o un codice stanza attivo."},
    {"n": "BabyPhone.online può vedere il mio video lungo il percorso?",
     "d": "WebRTC cifra i media in diretta mentre viaggiano. Quando serve un server di inoltro perché la rete blocca la via diretta, questo si limita a far passare i media protetti: non può vederli né ascoltarli."},
    {"n": "È la stessa cosa di WhatsApp?",
     "d": "Non alla lettera. WhatsApp usa un proprio protocollo end-to-end con chiavi di identità; BabyPhone.online usa WebRTC per media sicuri in tempo reale nel browser. Lo scopo è paragonabile, l'architettura tecnica no."},
    {"n": "Che cosa posso fare io per la massima sicurezza?",
     "d": "Usa un dispositivo e un browser aggiornati, tieni privati il codice stanza e il QR, attiva il blocco schermo, chiudi la sessione quando hai finito e apri BabyPhone.online solo dal suo indirizzo HTTPS ufficiale."}
  ],
  "ctaH": "Vuoi provarlo?",
  "ctaP": "Due dispositivi, nessuna installazione, nessun account. Apri il sito su entrambi e associali.",
  "ctaBtn": "Apri BabyPhone.online",
  "toBlog": "Leggi la guida completa: tutto quello che BabyPhone.online sa fare →",
  "backToApp": "← Torna all'app",
}

T['pl'] = {
  "title": "Jak zabezpieczona jest twoja niania elektroniczna? | BabyPhone.online",
  "desc": "Jak działa BabyPhone.online i w jaki sposób obraz oraz dźwięk na żywo między twoimi urządzeniami są chronione przez nowoczesną technologię przeglądarki i WebRTC.",
  "kicker": "BEZPIECZEŃSTWO I PRYWATNOŚĆ",
  "h1": "Jak działa BabyPhone.online — i dlaczego twoje połączenie pozostaje prywatne",
  "lede": "BabyPhone.online zamienia dwa urządzenia, które już masz, w nianię elektroniczną. Jedno zostaje przy dziecku, drugie bierzesz ze sobą. Poniżej wyjaśniamy, jak powstaje połączenie i jak nowoczesne zabezpieczenia przeglądarki chronią obraz i dźwięk na żywo — prostym językiem, bez żargonu.",
  "readTime": "5 min czytania",
  "updated": "Zaktualizowano w sierpniu 2026",
  "cardH": "Prywatność zaczyna się od projektu",
  "cardP": "Cel jest prosty: w sesji na żywo biorą udział tylko te dwa urządzenia, które sam sparowałeś.",
  "cardList": [
    "To przeglądarka sama prosi o zgodę na kamerę i mikrofon.",
    "WebRTC szyfruje obraz i dźwięk na żywo w drodze.",
    "Parowanie kodem QR oszczędza przepisywania długich kodów."
  ],
  "introP": "Klasyczna niania to para krótkozasięgowych radiotelefonów, które trzeba kupić, ładować i wozić ze sobą. BabyPhone.online idzie inną drogą: twoje własne urządzenia stają się kamerą i odbiornikiem, wprost w przeglądarce. Rodzi to uzasadnione pytanie — skoro działa przez internet, kto jeszcze może podglądać?",
  "stepsH": "Od dwóch urządzeń do niani w czterech krokach",
  "stepsP": "Nie potrzebujesz specjalnego sprzętu. Wystarczy telefon, tablet lub laptop z nowoczesną przeglądarką.",
  "steps": [
    "Otwórz stronę na urządzeniu, które chcesz postawić przy dziecku.",
    "Przeglądarka poprosi o zgodę na kamerę i mikrofon. Bez twojej zgody strona nie ma do nich dostępu.",
    "Użyj kodu QR, aby połączyć drugie urządzenie z tą samą sesją.",
    "Obie przeglądarki tworzą bezpośrednie połączenie w czasie rzeczywistym dla obrazu i dźwięku."
  ],
  "flowH": "Twój obraz na żywo nie jest przesyłany jako zwykłe, niezabezpieczone wideo",
  "flowP": "BabyPhone.online korzysta z WebRTC: technologii przeglądarki stworzonej do dźwięku i obrazu w czasie rzeczywistym — tej samej, której przeglądarka używa do rozmów wideo.",
  "flowBaby": "Urządzenie przy dziecku",
  "flowBabySub": "kamera + mikrofon",
  "flowLink": "WebRTC",
  "flowLinkSub": "szyfrowane połączenie multimedialne",
  "flowParent": "Urządzenie rodzica",
  "flowParentSub": "podgląd na żywo",
  "flowNote": "Zależnie od sieci WebRTC łączy oba urządzenia bezpośrednio albo przepuszcza zaszyfrowany ruch przez serwer przekaźnikowy (TURN), gdy droga bezpośrednia jest zablokowana.",
  "layersH": "Cztery warstwy ochrony, wyjaśnione prosto",
  "layers": [
    {"n": "1. HTTPS chroni połączenie ze stroną",
     "d": "Przeglądarka łączy się z BabyPhone.online przez HTTPS. Utrudnia to innym w sieci podglądanie treści i zmienianie strony po drodze."},
    {"n": "2. WebRTC chroni obraz i dźwięk na żywo",
     "d": "WebRTC używa bezpiecznego transportu dla mediów czasu rzeczywistego, więc strumień nie wędruje przez internet jako czytelne, niezabezpieczone dane."},
    {"n": "3. To ty udzielasz dostępu do kamery i mikrofonu",
     "d": "Strona nie włączy kamery po cichu. Przeglądarka pokazuje własne pytanie o zgodę, a zgodę możesz później cofnąć."},
    {"n": "4. Kod QR łączy właściwą sesję",
     "d": "Skanowanie eliminuje pomyłki przy przepisywaniu, a skanujące urządzenie dostaje jednorazowy klucz. Kto wpisze kod ręcznie, i tak musi zostać zatwierdzony na ekranie urządzenia przy dziecku."}
  ],
  "honestH": "Co właściwie znaczy „szyfrowane”?",
  "honestP": "Szyfrowanie jest ważne, ale prawdziwe bezpieczeństwo to coś więcej niż kłódka. Oto więc, co technologia robi — i czego nie robi.",
  "doesH": "Co robi WebRTC",
  "does": [
    "Szyfruje obraz i dźwięk na żywo w drodze.",
    "Łączy urządzenia bezpośrednio, gdy tylko sieć na to pozwala.",
    "Przepuszcza zaszyfrowane media przez przekaźnik, gdy połączenie bezpośrednie nie jest możliwe."
  ],
  "youH": "Co powinieneś zrobić także ty",
  "you": [
    "Nie udostępniaj kodu QR. Kto zobaczy aktywny kod parowania, może spróbować dołączyć do sesji.",
    "Blokuj urządzenia. Odblokowany telefon to większe ryzyko niż samo połączenie internetowe.",
    "Aktualizuj przeglądarkę. Poprawki bezpieczeństwa iOS, Androida i przeglądarki wciąż mają znaczenie."
  ],
  "noticeLead": "Warto wiedzieć:",
  "notice": " „szyfrowane” nie oznacza automatycznie, że każda aplikacja stosuje ten sam model bezpieczeństwa. WhatsApp ma własny protokół end-to-end z kluczami tożsamości. BabyPhone.online korzysta z zabezpieczeń wbudowanych w WebRTC dla mediów na żywo w przeglądarce. Cel — nigdy nie wysyłać niezabezpieczonego obrazu ani dźwięku przez internet — jest porównywalny, ale architektura jest inna. Wolimy powiedzieć to wprost, niż pożyczać cudze deklaracje.",
  "designH": "Niania elektroniczna powinna wiedzieć o twojej rodzinie jak najmniej",
  "designP": "To zasada, na której opiera się BabyPhone.online: jak najmniej kroków, żadnego zbędnego dostępu do urządzenia, bez konta, bez reklam, bez śledzenia i tymczasowe połączenie między dwoma urządzeniami, które sam sparowałeś. Nic nie jest nagrywane i żaden serwer nie podgląda.",
  "faqH": "Bezpieczeństwo w skrócie",
  "faq": [
    {"n": "Czy ktoś może po prostu włączyć moją kamerę?",
     "d": "Nie bez zgody na kamerę udzielonej przeglądarce. Poza tym dołączenie do sesji na żywo wymaga właściwego sparowania, a drugi widz musi zostać zatwierdzony na ekranie urządzenia przy dziecku. Nigdy nie udostępniaj publicznie aktywnego kodu QR ani kodu pokoju."},
    {"n": "Czy BabyPhone.online może podejrzeć mój obraz po drodze?",
     "d": "WebRTC szyfruje media na żywo w drodze. Gdy potrzebny jest serwer przekaźnikowy, bo sieć blokuje drogę bezpośrednią, jedynie przepuszcza chronione media — nie może ich zobaczyć ani usłyszeć."},
    {"n": "Czy to to samo co WhatsApp?",
     "d": "Nie dosłownie. WhatsApp używa własnego protokołu end-to-end z kluczami tożsamości; BabyPhone.online używa WebRTC do bezpiecznych mediów czasu rzeczywistego w przeglądarce. Cel jest porównywalny, architektura techniczna nie."},
    {"n": "Co sam mogę zrobić dla maksymalnego bezpieczeństwa?",
     "d": "Używaj aktualnego urządzenia i przeglądarki, trzymaj kod pokoju i QR dla siebie, włącz blokadę ekranu, zamykaj sesję po zakończeniu i otwieraj BabyPhone.online wyłącznie pod oficjalnym adresem HTTPS."}
  ],
  "ctaH": "Chcesz spróbować?",
  "ctaP": "Dwa urządzenia, bez instalacji, bez konta. Otwórz stronę na obu i sparuj je.",
  "ctaBtn": "Otwórz BabyPhone.online",
  "toBlog": "Przeczytaj pełny przewodnik: wszystko, co potrafi BabyPhone.online →",
  "backToApp": "← Powrót do aplikacji",
}

T['ro'] = {
  "title": "Cum este securizat monitorul tău pentru bebeluși? | BabyPhone.online",
  "desc": "Cum funcționează BabyPhone.online și cum sunt protejate imaginea și sunetul live dintre dispozitivele tale prin tehnologia modernă a browserului și WebRTC.",
  "kicker": "SECURITATE ȘI CONFIDENȚIALITATE",
  "h1": "Cum funcționează BabyPhone.online — și cum rămâne privată conexiunea ta",
  "lede": "BabyPhone.online transformă două dispozitive pe care le ai deja într-un monitor pentru bebeluși. Unul rămâne lângă copil, celălalt merge cu tine. Mai jos afli cum se stabilește conexiunea și cum securitatea modernă a browserului îți protejează imaginea și sunetul live — pe înțelesul tuturor, fără jargon.",
  "readTime": "5 min de citit",
  "updated": "Actualizat în august 2026",
  "cardH": "Confidențialitatea începe din proiectare",
  "cardP": "Scopul e simplu: doar cele două dispozitive pe care le-ai asociat tu participă la sesiunea live.",
  "cardList": [
    "Browserul îți cere el însuși permisiunea pentru cameră și microfon.",
    "WebRTC criptează imaginea și sunetul live pe drum.",
    "Asocierea prin cod QR îți scutește tastarea unor coduri lungi."
  ],
  "introP": "Un monitor clasic înseamnă două stații radio cu rază scurtă, pe care trebuie să le cumperi, să le încarci și să le cari. BabyPhone.online merge pe altă cale: propriile tale dispozitive devin camera și monitorul, direct în browser. De aici o întrebare firească — dacă merge prin internet, cine altcineva mai poate privi?",
  "stepsH": "De la două dispozitive la un monitor, în patru pași",
  "stepsP": "Nu ai nevoie de echipament special. Un telefon, o tabletă sau un laptop cu un browser recent sunt de ajuns.",
  "steps": [
    "Deschide site-ul pe dispozitivul pe care vrei să-l pui lângă copil.",
    "Browserul cere permisiunea pentru cameră și microfon. Fără acordul tău, site-ul nu ajunge la ele.",
    "Folosește codul QR pentru a conecta al doilea dispozitiv la aceeași sesiune.",
    "Cele două browsere creează o legătură directă, în timp real, pentru imagine și sunet."
  ],
  "flowH": "Imaginea ta live nu este trimisă ca un videoclip obișnuit, neprotejat",
  "flowP": "BabyPhone.online folosește WebRTC: tehnologia de browser creată pentru audio și video în timp real — aceeași folosită de browser pentru apeluri video.",
  "flowBaby": "Dispozitivul bebelușului",
  "flowBabySub": "cameră + microfon",
  "flowLink": "WebRTC",
  "flowLinkSub": "legătură media criptată",
  "flowParent": "Dispozitivul părintelui",
  "flowParentSub": "monitor live",
  "flowNote": "În funcție de rețea, WebRTC conectează direct cele două dispozitive sau trece traficul criptat printr-un server releu (TURN) atunci când calea directă este blocată.",
  "layersH": "Patru straturi de protecție, explicate simplu",
  "layers": [
    {"n": "1. HTTPS protejează conexiunea cu site-ul",
     "d": "Browserul ajunge la BabyPhone.online prin HTTPS. Asta împiedică alte persoane din rețea să citească sau să modifice pagina pe drum."},
    {"n": "2. WebRTC protejează imaginea și sunetul live",
     "d": "WebRTC folosește transport securizat pentru media în timp real, așa că fluxul nu circulă pe internet ca date lizibile și neprotejate."},
    {"n": "3. Tu acorzi accesul la cameră și microfon",
     "d": "Site-ul nu îți poate porni camera pe tăcute. Browserul afișează propria solicitare, iar permisiunea poate fi retrasă ulterior."},
    {"n": "4. Codul QR conectează sesiunea corectă",
     "d": "Scanarea elimină greșelile de tastare, iar dispozitivul care scanează primește o cheie de unică folosință. Cine tastează codul manual trebuie totuși aprobat pe ecranul dispozitivului bebelușului."}
  ],
  "honestH": "Ce înseamnă, de fapt, „criptat”?",
  "honestP": "Criptarea contează, dar siguranța reală înseamnă mai mult decât un lacăt. Iată deci ce face tehnologia — și ce nu face.",
  "doesH": "Ce face WebRTC",
  "does": [
    "Criptează imaginea și sunetul live pe drum.",
    "Conectează dispozitivele direct ori de câte ori rețeaua permite.",
    "Trece media criptată printr-un releu când o conexiune directă nu este posibilă."
  ],
  "youH": "Ce trebuie să faci și tu",
  "you": [
    "Nu împărtăși codul QR. Cine vede un cod de asociere activ poate încerca să intre în sesiune.",
    "Blochează-ți dispozitivele. Un telefon deblocat este un risc mai mare decât conexiunea la internet.",
    "Ține browserul la zi. Actualizările de securitate pentru iOS, Android și browser rămân importante."
  ],
  "noticeLead": "Bine de știut:",
  "notice": " „criptat” nu înseamnă automat că orice aplicație folosește același model de securitate. WhatsApp are propriul protocol end-to-end cu chei de identitate. BabyPhone.online folosește securitatea integrată în WebRTC pentru media live din browser. Scopul — să nu trimită niciodată imagine sau sunet neprotejate pe internet — este comparabil, dar arhitectura diferă. Preferăm să spunem asta clar decât să împrumutăm afirmația altcuiva.",
  "designH": "Un monitor pentru bebeluși ar trebui să știe cât mai puțin despre familia ta",
  "designP": "Acesta este principiul din spatele BabyPhone.online: cât mai puțini pași, niciun acces inutil la dispozitiv, fără cont, fără reclame, fără urmărire și o legătură temporară între cele două dispozitive pe care le-ai asociat tu. Nu se înregistrează nimic și niciun server nu privește.",
  "faqH": "Securitatea pe scurt",
  "faq": [
    {"n": "Poate cineva să-mi pornească pur și simplu camera?",
     "d": "Nu fără permisiunea de cameră dată browserului. În plus, intrarea într-o sesiune live cere asocierea corectă, iar un al doilea privitor trebuie aprobat pe ecranul dispozitivului bebelușului. Așa că nu împărtăși niciodată public un cod QR sau un cod de cameră activ."},
    {"n": "Poate BabyPhone.online să-mi vadă imaginea pe drum?",
     "d": "WebRTC criptează media live pe drum. Când e nevoie de un server releu pentru că rețeaua blochează calea directă, acesta doar transmite mai departe media protejată — nu o poate vedea și nici auzi."},
    {"n": "Este același lucru cu WhatsApp?",
     "d": "Nu la propriu. WhatsApp folosește propriul protocol end-to-end cu chei de identitate; BabyPhone.online folosește WebRTC pentru media securizată în timp real în browser. Scopul e comparabil, arhitectura tehnică nu."},
    {"n": "Ce pot face eu pentru siguranță maximă?",
     "d": "Folosește un dispozitiv și un browser actualizate, păstrează privat codul camerei și QR-ul, activează blocarea ecranului, închide sesiunea când ai terminat și deschide BabyPhone.online doar de la adresa HTTPS oficială."}
  ],
  "ctaH": "Vrei să încerci?",
  "ctaP": "Două dispozitive, fără instalare, fără cont. Deschide site-ul pe amândouă și asociază-le.",
  "ctaBtn": "Deschide BabyPhone.online",
  "toBlog": "Citește ghidul complet: tot ce poate face BabyPhone.online →",
  "backToApp": "← Înapoi la aplicație",
}
