# -*- coding: utf-8 -*-
T = {}

T['nl'] = {
  "title": "Hoe is je babyfoon beveiligd? | BabyPhone.online",
  "desc": "Hoe BabyPhone.online werkt en hoe live beeld en geluid tussen je apparaten beschermd worden door moderne browsertechnologie en WebRTC.",
  "kicker": "VEILIGHEID & PRIVACY",
  "h1": "Hoe BabyPhone.online werkt — en hoe je verbinding privé blijft",
  "lede": "BabyPhone.online maakt van twee apparaten die je al hebt een babyfoon. Eén blijft bij je baby, de andere neem je mee. Hieronder lees je hoe de verbinding tot stand komt en hoe moderne browserbeveiliging je live beeld en geluid beschermt — in gewone taal, zonder jargon.",
  "readTime": "5 min lezen",
  "updated": "Bijgewerkt augustus 2026",
  "cardH": "Privacy begint bij het ontwerp",
  "cardP": "Het doel is simpel: alleen de twee apparaten die je zelf koppelt doen mee aan de live sessie.",
  "cardList": [
    "Je browser vraagt zelf toestemming voor camera en microfoon.",
    "WebRTC versleutelt live beeld en geluid onderweg.",
    "Koppelen met een QR-code scheelt het overtypen van lange codes."
  ],
  "introP": "Een klassieke babyfoon is een setje zendertjes met beperkt bereik die je moet kopen, opladen en meenemen. BabyPhone.online kiest een andere weg: je eigen apparaten worden de camera en de monitor, gewoon in de browser. Dat roept een terechte vraag op — als het over internet gaat, wie kan er dan meekijken?",
  "stepsH": "Van twee apparaten naar een babyfoon in vier stappen",
  "stepsP": "Je hebt geen speciale babyfoonhardware nodig. Een telefoon, tablet of laptop met een moderne browser is genoeg.",
  "steps": [
    "Open de website op het apparaat dat je bij je baby wilt zetten.",
    "Je browser vraagt toestemming voor de camera en microfoon. Zonder jouw toestemming komt de website er niet bij.",
    "Gebruik de QR-code om je tweede apparaat met dezelfde sessie te verbinden.",
    "De twee browsers bouwen een directe verbinding op voor beeld en geluid."
  ],
  "flowH": "Je live beeld gaat niet als gewone, onbeveiligde video over internet",
  "flowP": "BabyPhone.online gebruikt WebRTC: de browsertechnologie die gemaakt is voor realtime beeld en geluid — dezelfde soort die je browser gebruikt voor videobellen.",
  "flowBaby": "Babyunit",
  "flowBabySub": "camera + microfoon",
  "flowLink": "WebRTC",
  "flowLinkSub": "versleutelde mediaverbinding",
  "flowParent": "Ouderunit",
  "flowParentSub": "live monitor",
  "flowNote": "Afhankelijk van het netwerk verbindt WebRTC de twee apparaten rechtstreeks, of gaat het versleutelde verkeer via een doorgeefserver (TURN) wanneer een directe route geblokkeerd is.",
  "layersH": "Vier beschermingslagen, in begrijpelijke taal",
  "layers": [
    {"n": "1. HTTPS beschermt de verbinding met de website",
     "d": "Je browser bereikt BabyPhone.online via HTTPS. Dat helpt voorkomen dat anderen op het netwerk meelezen of de pagina onderweg aanpassen."},
    {"n": "2. WebRTC beschermt live beeld en geluid",
     "d": "WebRTC gebruikt beveiligd transport voor realtime media, zodat de stream niet als leesbare, onbeveiligde data over internet reist."},
    {"n": "3. Jij geeft toegang tot camera en microfoon",
     "d": "De website kan je camera niet stiekem aanzetten. Je browser toont een eigen toestemmingsvraag, en je kunt die toestemming later weer intrekken."},
    {"n": "4. De QR-code koppelt de juiste sessie",
     "d": "Scannen voorkomt typefouten, en het scannende apparaat krijgt een eenmalige sleutel mee. Wie de code met de hand intypt, moet alsnog worden goedgekeurd op het scherm van de babyunit."}
  ],
  "honestH": "Wat betekent “versleuteld” precies?",
  "honestP": "Versleuteling is belangrijk, maar echte veiligheid is meer dan een slotje. Daarom hier wat de techniek wél doet — en wat niet.",
  "doesH": "Wat WebRTC wel doet",
  "does": [
    "Versleutelt live beeld en geluid onderweg.",
    "Verbindt je apparaten rechtstreeks zodra het netwerk dat toelaat.",
    "Geeft versleutelde media door via een relay als een directe verbinding niet lukt."
  ],
  "youH": "Wat je zelf ook moet doen",
  "you": [
    "Deel je QR-code niet. Wie een actieve koppelcode ziet, kan proberen aan die sessie mee te doen.",
    "Vergrendel je apparaten. Een ontgrendelde telefoon is een groter risico dan de internetverbinding zelf.",
    "Houd je browser actueel. Beveiligingsupdates van iOS, Android en je browser blijven belangrijk."
  ],
  "noticeLead": "Goed om te weten:",
  "notice": " “versleuteld” betekent niet automatisch dat elke app hetzelfde beveiligingsmodel gebruikt. WhatsApp heeft een eigen end-to-end protocol met identiteitssleutels. BabyPhone.online gebruikt de beveiliging die in WebRTC zit voor live browsermedia. Het doel — nooit onbeveiligd beeld of geluid over internet sturen — is vergelijkbaar, maar de architectuur is anders. Dat zeggen we liever eerlijk dan dat we andermans claim lenen.",
  "designH": "Een babyfoon hoort zo min mogelijk over je gezin te weten",
  "designP": "Dat is het uitgangspunt van BabyPhone.online: zo weinig mogelijk stappen, geen onnodige toegang tot je apparaat, geen account, geen advertenties, geen tracking, en een tijdelijke live verbinding tussen de twee apparaten die je zelf koppelt. Er wordt niets opgenomen en geen server kijkt mee.",
  "faqH": "Veiligheid in het kort",
  "faq": [
    {"n": "Kan iemand zomaar mijn camera aanzetten?",
     "d": "Niet zonder cameratoestemming van je browser. Daarnaast heb je de juiste koppeling nodig om mee te doen aan een live sessie, en een tweede kijker moet worden goedgekeurd op het scherm van de babyunit. Deel dus nooit een actieve QR-code of kamercode openbaar."},
    {"n": "Kan BabyPhone.online mijn beeld onderweg bekijken?",
     "d": "WebRTC versleutelt live media onderweg. Is er een doorgeefserver nodig omdat je netwerk een directe route blokkeert, dan geeft die alleen de beveiligde media door — hij kan de stream niet zien of horen."},
    {"n": "Is dit hetzelfde als WhatsApp?",
     "d": "Niet letterlijk. WhatsApp gebruikt een eigen end-to-end protocol met identiteitssleutels; BabyPhone.online gebruikt WebRTC voor beveiligde realtime browsermedia. Het doel is vergelijkbaar, de technische architectuur niet."},
    {"n": "Wat kan ik zelf doen voor maximale veiligheid?",
     "d": "Gebruik een actueel apparaat en een actuele browser, houd je kamercode en QR privé, zet een schermvergrendeling aan, sluit de sessie als je klaar bent, en open BabyPhone.online alleen via het officiële HTTPS-adres."}
  ],
  "ctaH": "Zin om het te proberen?",
  "ctaP": "Twee apparaten, geen installatie, geen account. Open de site op allebei en koppel ze.",
  "ctaBtn": "Open BabyPhone.online",
  "toBlog": "Lees de volledige gids: alles wat BabyPhone.online kan →",
  "backToApp": "← Terug naar de app",
}

T['de'] = {
  "title": "Wie ist dein Babyfon gesichert? | BabyPhone.online",
  "desc": "Wie BabyPhone.online funktioniert und wie Live-Bild und -Ton zwischen deinen Geräten durch moderne Browsertechnik und WebRTC geschützt werden.",
  "kicker": "SICHERHEIT & PRIVATSPHÄRE",
  "h1": "Wie BabyPhone.online funktioniert — und wie deine Verbindung privat bleibt",
  "lede": "BabyPhone.online macht aus zwei Geräten, die du bereits hast, ein Babyfon. Eines bleibt beim Baby, das andere nimmst du mit. Hier liest du, wie die Verbindung entsteht und wie moderne Browsersicherheit dein Live-Bild und deinen Ton schützt — in klarer Sprache, ohne Fachjargon.",
  "readTime": "5 Min. Lesezeit",
  "updated": "Aktualisiert August 2026",
  "cardH": "Privatsphäre beginnt beim Entwurf",
  "cardP": "Das Ziel ist einfach: Nur die beiden Geräte, die du selbst verbunden hast, nehmen an der Live-Sitzung teil.",
  "cardList": [
    "Dein Browser fragt selbst nach der Erlaubnis für Kamera und Mikrofon.",
    "WebRTC verschlüsselt Live-Bild und -Ton auf dem Weg.",
    "Das Koppeln per QR-Code erspart dir das Abtippen langer Codes."
  ],
  "introP": "Ein klassisches Babyfon besteht aus zwei Funkgeräten mit kurzer Reichweite, die du kaufen, laden und einpacken musst. BabyPhone.online geht einen anderen Weg: Deine eigenen Geräte werden zur Kamera und zum Monitor, direkt im Browser. Das wirft eine berechtigte Frage auf — wenn es über das Internet läuft, wer kann dann mitsehen?",
  "stepsH": "In vier Schritten von zwei Geräten zum Babyfon",
  "stepsP": "Du brauchst keine spezielle Babyfon-Hardware. Ein Handy, Tablet oder Laptop mit einem aktuellen Browser genügt.",
  "steps": [
    "Öffne die Website auf dem Gerät, das du beim Baby aufstellen möchtest.",
    "Dein Browser fragt nach der Erlaubnis für Kamera und Mikrofon. Ohne deine Erlaubnis kommt die Website nicht daran.",
    "Verbinde dein zweites Gerät über den QR-Code mit derselben Sitzung.",
    "Die beiden Browser bauen eine direkte Echtzeitverbindung für Bild und Ton auf."
  ],
  "flowH": "Dein Live-Bild wird nicht als gewöhnliches, ungeschütztes Video übertragen",
  "flowP": "BabyPhone.online nutzt WebRTC: die Browsertechnik für Echtzeit-Audio und -Video — dieselbe Art, die dein Browser für Videoanrufe verwendet.",
  "flowBaby": "Babygerät",
  "flowBabySub": "Kamera + Mikrofon",
  "flowLink": "WebRTC",
  "flowLinkSub": "verschlüsselte Medienverbindung",
  "flowParent": "Elterngerät",
  "flowParentSub": "Live-Monitor",
  "flowNote": "Je nach Netzwerk verbindet WebRTC die beiden Geräte direkt oder leitet den verschlüsselten Datenstrom über einen Relay-Server (TURN), wenn der direkte Weg blockiert ist.",
  "layersH": "Vier Schutzschichten, einfach erklärt",
  "layers": [
    {"n": "1. HTTPS schützt die Verbindung zur Website",
     "d": "Dein Browser erreicht BabyPhone.online über HTTPS. Das hilft zu verhindern, dass andere im Netzwerk mitlesen oder die Seite unterwegs verändern."},
    {"n": "2. WebRTC schützt Live-Bild und -Ton",
     "d": "WebRTC nutzt gesicherten Transport für Echtzeitmedien, sodass der Datenstrom nicht als lesbare, ungeschützte Daten durchs Internet reist."},
    {"n": "3. Du gibst Kamera und Mikrofon frei",
     "d": "Die Website kann deine Kamera nicht heimlich einschalten. Dein Browser zeigt seine eigene Abfrage, und du kannst die Erlaubnis später wieder entziehen."},
    {"n": "4. Der QR-Code verbindet die richtige Sitzung",
     "d": "Scannen verhindert Tippfehler, und das scannende Gerät erhält einen einmaligen Schlüssel. Wer den Code von Hand eintippt, muss trotzdem auf dem Bildschirm des Babygeräts bestätigt werden."}
  ],
  "honestH": "Was bedeutet „verschlüsselt“ eigentlich?",
  "honestP": "Verschlüsselung ist wichtig, aber echte Sicherheit ist mehr als ein Schloss-Symbol. Deshalb hier, was die Technik leistet — und was nicht.",
  "doesH": "Was WebRTC leistet",
  "does": [
    "Verschlüsselt Live-Bild und -Ton auf dem Weg.",
    "Verbindet deine Geräte direkt, sobald das Netzwerk es zulässt.",
    "Leitet verschlüsselte Medien über ein Relay, wenn keine direkte Verbindung möglich ist."
  ],
  "youH": "Was du selbst tun solltest",
  "you": [
    "Teile deinen QR-Code nicht. Wer einen aktiven Kopplungscode sieht, kann versuchen, der Sitzung beizutreten.",
    "Sperre deine Geräte. Ein entsperrtes Handy ist ein größeres Risiko als die Internetverbindung selbst.",
    "Halte deinen Browser aktuell. Sicherheitsupdates für iOS, Android und den Browser bleiben wichtig."
  ],
  "noticeLead": "Gut zu wissen:",
  "notice": " „verschlüsselt“ bedeutet nicht automatisch, dass jede App dasselbe Sicherheitsmodell verwendet. WhatsApp hat ein eigenes Ende-zu-Ende-Protokoll mit Identitätsschlüsseln. BabyPhone.online nutzt für Live-Browsermedien die Sicherheit, die in WebRTC eingebaut ist. Das Ziel — niemals ungeschütztes Bild oder Ton durchs Internet zu schicken — ist vergleichbar, die Architektur ist es nicht. Das sagen wir lieber offen, als die Aussage eines anderen zu übernehmen.",
  "designH": "Ein Babyfon sollte so wenig wie möglich über deine Familie wissen müssen",
  "designP": "Das ist der Grundsatz hinter BabyPhone.online: so wenige Schritte wie möglich, kein unnötiger Zugriff auf dein Gerät, kein Konto, keine Werbung, kein Tracking und eine zeitlich begrenzte Live-Verbindung zwischen den beiden Geräten, die du selbst gekoppelt hast. Nichts wird aufgezeichnet, und kein Server schaut mit.",
  "faqH": "Sicherheit in Kürze",
  "faq": [
    {"n": "Kann jemand einfach meine Kamera einschalten?",
     "d": "Nicht ohne Kameraerlaubnis deines Browsers. Außerdem braucht man die richtige Kopplung, um an einer Live-Sitzung teilzunehmen, und ein zweiter Zuschauer muss auf dem Bildschirm des Babygeräts bestätigt werden. Teile also nie einen aktiven QR- oder Raumcode öffentlich."},
    {"n": "Kann BabyPhone.online mein Bild unterwegs ansehen?",
     "d": "WebRTC verschlüsselt Live-Medien auf dem Weg. Wird ein Relay-Server gebraucht, weil dein Netzwerk den direkten Weg blockiert, leitet er nur die geschützten Medien weiter — sehen oder hören kann er den Datenstrom nicht."},
    {"n": "Ist das dasselbe wie WhatsApp?",
     "d": "Nicht wörtlich. WhatsApp nutzt ein eigenes Ende-zu-Ende-Protokoll mit Identitätsschlüsseln; BabyPhone.online nutzt WebRTC für gesicherte Echtzeit-Browsermedien. Der Zweck ist vergleichbar, die technische Architektur nicht."},
    {"n": "Was kann ich selbst für maximale Sicherheit tun?",
     "d": "Nutze ein aktuelles Gerät und einen aktuellen Browser, halte Raumcode und QR privat, aktiviere eine Bildschirmsperre, beende die Sitzung, wenn du fertig bist, und öffne BabyPhone.online nur über die offizielle HTTPS-Adresse."}
  ],
  "ctaH": "Lust, es auszuprobieren?",
  "ctaP": "Zwei Geräte, keine Installation, kein Konto. Öffne die Seite auf beiden und koppele sie.",
  "ctaBtn": "BabyPhone.online öffnen",
  "toBlog": "Lies den ausführlichen Leitfaden: alles, was BabyPhone.online kann →",
  "backToApp": "← Zurück zur App",
}

T['fr'] = {
  "title": "Comment votre babyphone est-il sécurisé ? | BabyPhone.online",
  "desc": "Comment fonctionne BabyPhone.online et comment la vidéo et le son en direct entre vos appareils sont protégés par les technologies modernes du navigateur et WebRTC.",
  "kicker": "SÉCURITÉ & CONFIDENTIALITÉ",
  "h1": "Comment fonctionne BabyPhone.online — et comment votre connexion reste privée",
  "lede": "BabyPhone.online transforme deux appareils que vous possédez déjà en babyphone. L'un reste près de votre bébé, l'autre vous accompagne. Voici comment la connexion s'établit et comment la sécurité moderne des navigateurs protège votre vidéo et votre son en direct — en langage clair, sans jargon.",
  "readTime": "5 min de lecture",
  "updated": "Mis à jour en août 2026",
  "cardH": "La confidentialité commence dès la conception",
  "cardP": "L'objectif est simple : seuls les deux appareils que vous avez appairés vous-même participent à la session en direct.",
  "cardList": [
    "Votre navigateur demande lui-même l'autorisation pour la caméra et le micro.",
    "WebRTC chiffre la vidéo et le son en direct pendant leur transport.",
    "L'appairage par QR code évite de recopier de longs codes."
  ],
  "introP": "Un babyphone classique, ce sont deux émetteurs radio de faible portée qu'il faut acheter, recharger et emporter. BabyPhone.online prend une autre voie : vos propres appareils deviennent la caméra et le moniteur, directement dans le navigateur. Cela soulève une question légitime — si tout passe par Internet, qui d'autre peut regarder ?",
  "stepsH": "De deux appareils à un babyphone en quatre étapes",
  "stepsP": "Aucun matériel spécial n'est nécessaire. Un téléphone, une tablette ou un ordinateur portable avec un navigateur récent suffit.",
  "steps": [
    "Ouvrez le site sur l'appareil que vous voulez placer près de votre bébé.",
    "Votre navigateur demande l'autorisation d'accéder à la caméra et au micro. Sans votre accord, le site n'y accède pas.",
    "Utilisez le QR code pour connecter votre second appareil à la même session.",
    "Les deux navigateurs établissent une liaison directe en temps réel pour l'image et le son."
  ],
  "flowH": "Votre image en direct n'est pas transmise comme une vidéo ordinaire, non protégée",
  "flowP": "BabyPhone.online utilise WebRTC : la technologie de navigateur conçue pour l'audio et la vidéo en temps réel — la même que celle des appels vidéo.",
  "flowBaby": "Appareil bébé",
  "flowBabySub": "caméra + micro",
  "flowLink": "WebRTC",
  "flowLinkSub": "liaison média chiffrée",
  "flowParent": "Appareil parent",
  "flowParentSub": "moniteur en direct",
  "flowNote": "Selon le réseau, WebRTC relie les deux appareils directement, ou fait transiter le flux chiffré par un serveur relais (TURN) lorsque la voie directe est bloquée.",
  "layersH": "Quatre couches de protection, expliquées simplement",
  "layers": [
    {"n": "1. HTTPS protège la connexion au site",
     "d": "Votre navigateur atteint BabyPhone.online via HTTPS. Cela empêche d'autres personnes sur le réseau de lire ou de modifier la page en chemin."},
    {"n": "2. WebRTC protège la vidéo et le son en direct",
     "d": "WebRTC utilise un transport sécurisé pour les médias en temps réel : le flux ne circule pas sur Internet sous forme de données lisibles et non protégées."},
    {"n": "3. C'est vous qui autorisez la caméra et le micro",
     "d": "Le site ne peut pas allumer votre caméra en silence. Votre navigateur affiche sa propre demande, et vous pouvez retirer cette autorisation plus tard."},
    {"n": "4. Le QR code relie la bonne session",
     "d": "Le scan évite les fautes de frappe et l'appareil qui scanne reçoit une clé à usage unique. Celui qui saisit le code à la main doit tout de même être approuvé sur l'écran de l'appareil bébé."}
  ],
  "honestH": "Que veut dire « chiffré », au juste ?",
  "honestP": "Le chiffrement compte, mais la vraie sécurité ne se résume pas à un cadenas. Voici donc ce que la technologie fait — et ce qu'elle ne fait pas.",
  "doesH": "Ce que WebRTC fait",
  "does": [
    "Chiffre la vidéo et le son en direct pendant leur transport.",
    "Relie vos appareils directement dès que le réseau le permet.",
    "Fait transiter les médias chiffrés par un relais quand une liaison directe est impossible."
  ],
  "youH": "Ce que vous devez faire aussi",
  "you": [
    "Ne partagez pas votre QR code. Qui voit un code d'appairage actif peut tenter de rejoindre la session.",
    "Verrouillez vos appareils. Un téléphone déverrouillé est un risque plus grand que la connexion Internet elle-même.",
    "Gardez votre navigateur à jour. Les mises à jour de sécurité d'iOS, d'Android et du navigateur restent essentielles."
  ],
  "noticeLead": "Bon à savoir :",
  "notice": " « chiffré » ne signifie pas automatiquement que toutes les applications utilisent le même modèle de sécurité. WhatsApp dispose de son propre protocole de bout en bout avec des clés d'identité. BabyPhone.online s'appuie sur la sécurité intégrée à WebRTC pour les médias en direct dans le navigateur. L'objectif — ne jamais envoyer d'image ou de son non protégés sur Internet — est comparable, mais l'architecture est différente. Nous préférons le dire clairement plutôt que d'emprunter l'argument d'un autre.",
  "designH": "Un babyphone devrait en savoir le moins possible sur votre famille",
  "designP": "C'est le principe de BabyPhone.online : le moins d'étapes possible, aucun accès inutile à votre appareil, pas de compte, pas de publicité, pas de traçage, et une liaison temporaire entre les deux appareils que vous avez appairés vous-même. Rien n'est enregistré et aucun serveur ne regarde.",
  "faqH": "La sécurité en bref",
  "faq": [
    {"n": "Quelqu'un peut-il allumer ma caméra sans plus ?",
     "d": "Pas sans l'autorisation caméra de votre navigateur. De plus, rejoindre une session en direct exige le bon appairage, et un second spectateur doit être approuvé sur l'écran de l'appareil bébé. Ne partagez donc jamais publiquement un QR code ou un code de chambre actif."},
    {"n": "BabyPhone.online peut-il voir mon image en chemin ?",
     "d": "WebRTC chiffre les médias en direct pendant leur transport. Lorsqu'un serveur relais est nécessaire parce que votre réseau bloque la voie directe, il ne fait que transmettre les médias protégés — il ne peut ni les voir ni les entendre."},
    {"n": "Est-ce la même chose que WhatsApp ?",
     "d": "Pas littéralement. WhatsApp utilise son propre protocole de bout en bout avec des clés d'identité ; BabyPhone.online utilise WebRTC pour des médias sécurisés en temps réel dans le navigateur. L'objectif est comparable, l'architecture technique ne l'est pas."},
    {"n": "Que puis-je faire pour une sécurité maximale ?",
     "d": "Utilisez un appareil et un navigateur à jour, gardez votre code de chambre et votre QR privés, activez le verrouillage de l'écran, fermez la session quand vous avez terminé, et n'ouvrez BabyPhone.online que via son adresse HTTPS officielle."}
  ],
  "ctaH": "Envie d'essayer ?",
  "ctaP": "Deux appareils, aucune installation, aucun compte. Ouvrez le site sur les deux et appairez-les.",
  "ctaBtn": "Ouvrir BabyPhone.online",
  "toBlog": "Lire le guide complet : tout ce que BabyPhone.online peut faire →",
  "backToApp": "← Retour à l'application",
}

T['es'] = {
  "title": "¿Cómo está protegido tu vigilabebés? | BabyPhone.online",
  "desc": "Cómo funciona BabyPhone.online y cómo la imagen y el sonido en directo entre tus dispositivos están protegidos por la tecnología moderna del navegador y WebRTC.",
  "kicker": "SEGURIDAD Y PRIVACIDAD",
  "h1": "Cómo funciona BabyPhone.online — y cómo tu conexión sigue siendo privada",
  "lede": "BabyPhone.online convierte dos dispositivos que ya tienes en un vigilabebés. Uno se queda con tu bebé y el otro va contigo. Aquí te contamos cómo se establece la conexión y cómo la seguridad moderna del navegador protege tu vídeo y tu sonido en directo — en lenguaje claro, sin tecnicismos.",
  "readTime": "5 min de lectura",
  "updated": "Actualizado en agosto de 2026",
  "cardH": "La privacidad empieza en el diseño",
  "cardP": "El objetivo es simple: solo los dos dispositivos que has emparejado tú participan en la sesión en directo.",
  "cardList": [
    "Tu navegador pide él mismo permiso para la cámara y el micrófono.",
    "WebRTC cifra el vídeo y el sonido en directo mientras viajan.",
    "Emparejar con código QR evita tener que copiar códigos largos."
  ],
  "introP": "Un vigilabebés clásico son dos radios de corto alcance que hay que comprar, cargar y llevar encima. BabyPhone.online toma otro camino: tus propios dispositivos se convierten en la cámara y en el monitor, directamente en el navegador. Eso plantea una pregunta legítima: si funciona por Internet, ¿quién más puede mirar?",
  "stepsH": "De dos dispositivos a un vigilabebés en cuatro pasos",
  "stepsP": "No necesitas hardware especial. Basta con un móvil, una tableta o un portátil con un navegador actual.",
  "steps": [
    "Abre la web en el dispositivo que quieras dejar junto a tu bebé.",
    "Tu navegador pide permiso para la cámara y el micrófono. Sin tu permiso, la web no puede acceder a ellos.",
    "Usa el código QR para conectar tu segundo dispositivo a la misma sesión.",
    "Los dos navegadores crean un enlace directo en tiempo real para imagen y sonido."
  ],
  "flowH": "Tu imagen en directo no se envía como un vídeo normal y sin protección",
  "flowP": "BabyPhone.online usa WebRTC: la tecnología del navegador creada para audio y vídeo en tiempo real, la misma que usa tu navegador para videollamadas.",
  "flowBaby": "Dispositivo del bebé",
  "flowBabySub": "cámara + micrófono",
  "flowLink": "WebRTC",
  "flowLinkSub": "enlace multimedia cifrado",
  "flowParent": "Dispositivo de los padres",
  "flowParentSub": "monitor en directo",
  "flowNote": "Según la red, WebRTC conecta los dos dispositivos directamente o hace pasar el tráfico cifrado por un servidor de retransmisión (TURN) cuando la vía directa está bloqueada.",
  "layersH": "Cuatro capas de protección, explicadas de forma sencilla",
  "layers": [
    {"n": "1. HTTPS protege la conexión con la web",
     "d": "Tu navegador llega a BabyPhone.online mediante HTTPS. Eso ayuda a evitar que otros en la red lean o alteren la página por el camino."},
    {"n": "2. WebRTC protege el vídeo y el sonido en directo",
     "d": "WebRTC usa transporte seguro para los medios en tiempo real, así que el flujo no viaja por Internet como datos legibles y sin protección."},
    {"n": "3. Tú das acceso a la cámara y al micrófono",
     "d": "La web no puede encender tu cámara en silencio. Tu navegador muestra su propio aviso de permiso, y puedes retirarlo más adelante."},
    {"n": "4. El código QR enlaza la sesión correcta",
     "d": "Escanear evita errores al teclear, y el dispositivo que escanea recibe una clave de un solo uso. Quien teclee el código a mano deberá ser aprobado en la pantalla del propio dispositivo del bebé."}
  ],
  "honestH": "¿Qué significa realmente «cifrado»?",
  "honestP": "El cifrado importa, pero la seguridad real es más que un candado. Así que esto es lo que hace la tecnología — y lo que no hace.",
  "doesH": "Lo que WebRTC sí hace",
  "does": [
    "Cifra el vídeo y el sonido en directo mientras viajan.",
    "Conecta tus dispositivos directamente siempre que la red lo permita.",
    "Hace pasar los medios cifrados por un relé cuando no es posible una conexión directa."
  ],
  "youH": "Lo que también deberías hacer tú",
  "you": [
    "No compartas tu código QR. Quien vea un código de emparejamiento activo puede intentar unirse a esa sesión.",
    "Bloquea tus dispositivos. Un móvil desbloqueado es un riesgo mayor que la propia conexión a Internet.",
    "Mantén el navegador al día. Las actualizaciones de seguridad de iOS, Android y tu navegador siguen siendo importantes."
  ],
  "noticeLead": "Conviene saberlo:",
  "notice": " «cifrado» no significa automáticamente que todas las aplicaciones usen el mismo modelo de seguridad. WhatsApp tiene su propio protocolo de extremo a extremo con claves de identidad. BabyPhone.online usa la seguridad integrada en WebRTC para los medios en directo del navegador. El objetivo — no enviar nunca imagen o sonido sin proteger por Internet — es comparable, pero la arquitectura es distinta. Preferimos decirlo con claridad antes que tomar prestada la afirmación de otro.",
  "designH": "Un vigilabebés debería saber lo mínimo posible sobre tu familia",
  "designP": "Ese es el principio de BabyPhone.online: los menos pasos posibles, ningún acceso innecesario a tu dispositivo, sin cuenta, sin anuncios, sin rastreo, y un enlace temporal entre los dos dispositivos que has emparejado tú. No se graba nada y ningún servidor mira.",
  "faqH": "La seguridad en breve",
  "faq": [
    {"n": "¿Puede alguien encender mi cámara sin más?",
     "d": "No sin el permiso de cámara de tu navegador. Además, unirse a una sesión en directo exige el emparejamiento correcto, y un segundo espectador debe ser aprobado en la pantalla del dispositivo del bebé. Así que nunca compartas públicamente un código QR o un código de sala activo."},
    {"n": "¿Puede BabyPhone.online ver mi imagen por el camino?",
     "d": "WebRTC cifra los medios en directo mientras viajan. Cuando hace falta un servidor de retransmisión porque tu red bloquea la vía directa, este solo deja pasar los medios protegidos: no puede verlos ni oírlos."},
    {"n": "¿Es lo mismo que WhatsApp?",
     "d": "No literalmente. WhatsApp usa su propio protocolo de extremo a extremo con claves de identidad; BabyPhone.online usa WebRTC para medios seguros en tiempo real en el navegador. El propósito es comparable, la arquitectura técnica no."},
    {"n": "¿Qué puedo hacer yo para máxima seguridad?",
     "d": "Usa un dispositivo y un navegador actualizados, mantén en privado el código de sala y el QR, activa el bloqueo de pantalla, cierra la sesión cuando termines y abre BabyPhone.online solo desde su dirección HTTPS oficial."}
  ],
  "ctaH": "¿Te animas a probarlo?",
  "ctaP": "Dos dispositivos, sin instalación y sin cuenta. Abre la web en ambos y emparéjalos.",
  "ctaBtn": "Abrir BabyPhone.online",
  "toBlog": "Lee la guía completa: todo lo que puede hacer BabyPhone.online →",
  "backToApp": "← Volver a la aplicación",
}
