# -*- coding: utf-8 -*-
T = {}

T['ar'] = {
  "title": "كيف تُحمى جهاز مراقبة طفلك؟ | BabyPhone.online",
  "desc": "كيف يعمل BabyPhone.online وكيف تحمي تقنيات المتصفح الحديثة وWebRTC الصوت والصورة المباشرين بين أجهزتك.",
  "kicker": "الأمان والخصوصية",
  "h1": "كيف يعمل BabyPhone.online — وكيف يبقى اتصالك خاصًا",
  "lede": "يحوّل BabyPhone.online جهازين تملكهما بالفعل إلى جهاز مراقبة للطفل. يبقى أحدهما بجوار طفلك ويرافقك الآخر. فيما يلي شرح لكيفية إنشاء الاتصال، ولكيفية حماية أمان المتصفح الحديث للصوت والصورة المباشرين — بلغة بسيطة وبلا مصطلحات معقدة.",
  "readTime": "قراءة 5 دقائق",
  "updated": "آخر تحديث: أغسطس 2026",
  "cardH": "الخصوصية تبدأ من التصميم",
  "cardP": "الهدف بسيط: لا يشارك في الجلسة المباشرة سوى الجهازين اللذين أقرنتهما بنفسك.",
  "cardList": [
    "المتصفح نفسه هو من يطلب الإذن باستخدام الكاميرا والميكروفون.",
    "يشفّر WebRTC الصوت والصورة المباشرين أثناء انتقالهما.",
    "الاقتران برمز QR يغنيك عن كتابة رموز طويلة."
  ],
  "introP": "جهاز المراقبة التقليدي عبارة عن جهازي إرسال قصيري المدى عليك شراؤهما وشحنهما وحملهما معك. يسلك BabyPhone.online طريقًا آخر: تصبح أجهزتك أنت الكاميرا والشاشة، مباشرة داخل المتصفح. وهنا يبرز سؤال وجيه — ما دام يعمل عبر الإنترنت، فمن غيرك يمكنه المشاهدة؟",
  "stepsH": "من جهازين إلى جهاز مراقبة في أربع خطوات",
  "stepsP": "لا حاجة إلى عتاد خاص. يكفي هاتف أو جهاز لوحي أو حاسوب محمول بمتصفح حديث.",
  "steps": [
    "افتح الموقع على الجهاز الذي تريد وضعه بجوار طفلك.",
    "سيطلب المتصفح الإذن باستخدام الكاميرا والميكروفون. وبدون إذنك لا يستطيع الموقع الوصول إليهما.",
    "استخدم رمز QR لربط جهازك الثاني بالجلسة نفسها.",
    "ينشئ المتصفحان اتصالًا مباشرًا وفوريًا للصوت والصورة."
  ],
  "flowH": "صورتك المباشرة لا تُرسل كفيديو عادي غير محمي",
  "flowP": "يستخدم BabyPhone.online تقنية WebRTC: تقنية المتصفح المصممة للصوت والفيديو الفوريين — وهي النوع نفسه الذي يستخدمه متصفحك في مكالمات الفيديو.",
  "flowBaby": "جهاز الطفل",
  "flowBabySub": "كاميرا + ميكروفون",
  "flowLink": "WebRTC",
  "flowLinkSub": "وصلة وسائط مشفّرة",
  "flowParent": "جهاز الوالدين",
  "flowParentSub": "شاشة مباشرة",
  "flowNote": "بحسب الشبكة، يربط WebRTC الجهازين مباشرة، أو يمرّر البيانات المشفّرة عبر خادم ترحيل (TURN) عندما يكون المسار المباشر محجوبًا.",
  "layersH": "أربع طبقات حماية بلغة مفهومة",
  "layers": [
    {"n": "١. بروتوكول HTTPS يحمي الاتصال بالموقع",
     "d": "يصل متصفحك إلى BabyPhone.online عبر HTTPS، ما يساعد على منع الآخرين على الشبكة من قراءة الصفحة أو تعديلها في الطريق."},
    {"n": "٢. WebRTC يحمي الصوت والصورة المباشرين",
     "d": "يستخدم WebRTC نقلًا آمنًا للوسائط الفورية، فلا ينتقل البث عبر الإنترنت كبيانات مقروءة وغير محمية."},
    {"n": "٣. أنت من يمنح إذن الكاميرا والميكروفون",
     "d": "لا يستطيع الموقع تشغيل الكاميرا في صمت. يعرض المتصفح طلب الإذن الخاص به، ويمكنك سحب هذا الإذن لاحقًا."},
    {"n": "٤. رمز QR يربط الجلسة الصحيحة",
     "d": "المسح يلغي أخطاء الكتابة، ويحصل الجهاز الماسح على مفتاح لمرة واحدة. أما من يكتب الرمز يدويًا فيجب اعتماده على شاشة جهاز الطفل نفسه."}
  ],
  "honestH": "ماذا تعني كلمة «مشفّر» فعليًا؟",
  "honestP": "التشفير مهم، لكن الأمان الحقيقي أكثر من أيقونة قفل. لذا إليك ما تفعله هذه التقنية — وما لا تفعله.",
  "doesH": "ما يفعله WebRTC",
  "does": [
    "يشفّر الصوت والصورة المباشرين أثناء انتقالهما.",
    "يربط جهازيك مباشرة كلما سمحت الشبكة بذلك.",
    "يمرّر الوسائط المشفّرة عبر خادم ترحيل عندما يتعذر الاتصال المباشر."
  ],
  "youH": "ما ينبغي أن تفعله أنت أيضًا",
  "you": [
    "لا تشارك رمز QR الخاص بك. فمن يرى رمز اقتران نشطًا قد يحاول الانضمام إلى تلك الجلسة.",
    "اقفل أجهزتك. الهاتف غير المقفل خطر أكبر من اتصال الإنترنت نفسه.",
    "أبقِ متصفحك محدّثًا. تحديثات الأمان لنظامي iOS وAndroid وللمتصفح تظل مهمة."
  ],
  "noticeLead": "من المفيد أن تعرف:",
  "notice": " كلمة «مشفّر» لا تعني تلقائيًا أن كل تطبيق يستخدم نموذج الأمان نفسه. فلدى WhatsApp بروتوكول خاص من طرف إلى طرف بمفاتيح هوية. أما BabyPhone.online فيستخدم الأمان المدمج في WebRTC للوسائط المباشرة داخل المتصفح. الهدف — ألا يُرسل صوت أو صورة بلا حماية عبر الإنترنت — متقارب، لكن البنية مختلفة. ونفضّل قول ذلك بوضوح بدل استعارة ادعاء غيرنا.",
  "designH": "ينبغي لجهاز مراقبة الطفل أن يعرف أقل ما يمكن عن عائلتك",
  "designP": "هذا هو المبدأ وراء BabyPhone.online: أقل عدد ممكن من الخطوات، ولا وصول غير ضروري إلى جهازك، وبلا حساب ولا إعلانات ولا تتبّع، ومجرد اتصال مباشر مؤقت بين الجهازين اللذين أقرنتهما بنفسك. لا يُسجَّل شيء ولا يشاهد أي خادم ما يجري.",
  "faqH": "الأمان باختصار",
  "faq": [
    {"n": "هل يستطيع أحد تشغيل الكاميرا ببساطة؟",
     "d": "لا، ليس بدون إذن الكاميرا من متصفحك. كما أن الانضمام إلى جلسة مباشرة يتطلب الاقتران الصحيح، ويجب اعتماد أي مشاهد ثانٍ على شاشة جهاز الطفل. لذلك لا تشارك أبدًا رمز QR أو رمز الغرفة النشط علنًا."},
    {"n": "هل يستطيع BabyPhone.online مشاهدة صورتي أثناء انتقالها؟",
     "d": "يشفّر WebRTC الوسائط المباشرة أثناء انتقالها. وعند الحاجة إلى خادم ترحيل لأن شبكتك تحجب المسار المباشر، فإنه يمرّر الوسائط المحمية فحسب — ولا يمكنه رؤية البث أو سماعه."},
    {"n": "هل هذا مثل WhatsApp؟",
     "d": "ليس حرفيًا. يستخدم WhatsApp بروتوكولًا خاصًا من طرف إلى طرف بمفاتيح هوية، بينما يستخدم BabyPhone.online تقنية WebRTC لوسائط فورية آمنة في المتصفح. الغرض متقارب، أما البنية التقنية فليست نفسها."},
    {"n": "ماذا أفعل لأعلى درجة أمان؟",
     "d": "استخدم جهازًا ومتصفحًا محدّثين، واحتفظ برمز الغرفة ورمز QR لنفسك، وفعّل قفل الشاشة، وأغلق الجلسة عند الانتهاء، ولا تفتح BabyPhone.online إلا عبر عنوان HTTPS الرسمي."}
  ],
  "ctaH": "هل تريد تجربته؟",
  "ctaP": "جهازان، بلا تثبيت وبلا حساب. افتح الموقع على كليهما ثم اقرنهما.",
  "ctaBtn": "افتح BabyPhone.online",
  "toBlog": "اقرأ الدليل الكامل: كل ما يستطيع BabyPhone.online فعله ←",
  "backToApp": "← العودة إلى التطبيق",
}

T['fa'] = {
  "title": "دستگاه پایش کودک شما چگونه ایمن می‌شود؟ | BabyPhone.online",
  "desc": "BabyPhone.online چگونه کار می‌کند و فناوری مدرن مرورگر و WebRTC چگونه تصویر و صدای زنده میان دستگاه‌های شما را محافظت می‌کنند.",
  "kicker": "امنیت و حریم خصوصی",
  "h1": "BabyPhone.online چگونه کار می‌کند — و چگونه ارتباط شما خصوصی می‌ماند",
  "lede": "BabyPhone.online دو دستگاهی را که همین حالا دارید به دستگاه پایش کودک تبدیل می‌کند. یکی کنار کودک می‌ماند و دیگری همراه شماست. در ادامه می‌خوانید که ارتباط چگونه برقرار می‌شود و امنیت مدرن مرورگر چگونه از تصویر و صدای زنده شما محافظت می‌کند — به زبان ساده و بدون اصطلاحات فنی.",
  "readTime": "۵ دقیقه مطالعه",
  "updated": "به‌روزرسانی: مرداد ۱۴۰۵",
  "cardH": "حریم خصوصی از طراحی آغاز می‌شود",
  "cardP": "هدف ساده است: تنها همان دو دستگاهی که خودتان جفت کرده‌اید در جلسه زنده شرکت می‌کنند.",
  "cardList": [
    "خود مرورگر برای دوربین و میکروفون از شما اجازه می‌گیرد.",
    "WebRTC تصویر و صدای زنده را در مسیر رمزگذاری می‌کند.",
    "جفت‌کردن با کد QR شما را از تایپ کدهای طولانی بی‌نیاز می‌کند."
  ],
  "introP": "دستگاه پایش سنتی یک جفت بی‌سیم کوتاه‌برد است که باید بخرید، شارژ کنید و همراه ببرید. BabyPhone.online راه دیگری را برمی‌گزیند: دستگاه‌های خودتان همان‌جا در مرورگر به دوربین و نمایشگر تبدیل می‌شوند. اینجا پرسشی بجا پیش می‌آید — وقتی از اینترنت عبور می‌کند، چه کسی دیگری می‌تواند ببیند؟",
  "stepsH": "از دو دستگاه تا یک پایشگر، در چهار گام",
  "stepsP": "به سخت‌افزار ویژه نیازی نیست. یک گوشی، تبلت یا لپ‌تاپ با مرورگر به‌روز کافی است.",
  "steps": [
    "وب‌سایت را روی دستگاهی باز کنید که می‌خواهید کنار کودک بگذارید.",
    "مرورگر برای دوربین و میکروفون اجازه می‌خواهد. بدون اجازه شما وب‌سایت به آن‌ها دسترسی ندارد.",
    "با کد QR دستگاه دوم را به همان جلسه وصل کنید.",
    "دو مرورگر یک ارتباط مستقیم و بی‌درنگ برای تصویر و صدا برقرار می‌کنند."
  ],
  "flowH": "تصویر زنده شما مانند یک ویدئوی معمولی و بی‌محافظ فرستاده نمی‌شود",
  "flowP": "BabyPhone.online از WebRTC استفاده می‌کند: فناوری مرورگر که برای صدا و تصویر بی‌درنگ ساخته شده — همان چیزی که مرورگر شما برای تماس تصویری به کار می‌برد.",
  "flowBaby": "دستگاه کودک",
  "flowBabySub": "دوربین + میکروفون",
  "flowLink": "WebRTC",
  "flowLinkSub": "پیوند رسانه‌ای رمزگذاری‌شده",
  "flowParent": "دستگاه والدین",
  "flowParentSub": "نمایشگر زنده",
  "flowNote": "بسته به شبکه، WebRTC دو دستگاه را مستقیم به هم وصل می‌کند یا وقتی مسیر مستقیم بسته باشد داده رمزگذاری‌شده را از یک سرور بازپخش (TURN) عبور می‌دهد.",
  "layersH": "چهار لایه محافظت، به زبان ساده",
  "layers": [
    {"n": "۱. HTTPS از ارتباط با وب‌سایت محافظت می‌کند",
     "d": "مرورگر شما از راه HTTPS به BabyPhone.online می‌رسد. این کار جلوی خواندن یا دستکاری صفحه در مسیر توسط دیگران در شبکه را می‌گیرد."},
    {"n": "۲. WebRTC از تصویر و صدای زنده محافظت می‌کند",
     "d": "WebRTC برای رسانه بی‌درنگ از انتقال امن استفاده می‌کند، بنابراین جریان داده به شکل خوانا و بی‌محافظ در اینترنت جابه‌جا نمی‌شود."},
    {"n": "۳. اجازه دوربین و میکروفون را شما می‌دهید",
     "d": "وب‌سایت نمی‌تواند بی‌سروصدا دوربین را روشن کند. مرورگر پرسش اجازه خودش را نشان می‌دهد و می‌توانید بعداً آن را پس بگیرید."},
    {"n": "۴. کد QR جلسه درست را وصل می‌کند",
     "d": "اسکن‌کردن خطای تایپ را از میان برمی‌دارد و دستگاه اسکن‌کننده کلیدی یک‌بارمصرف می‌گیرد. هر کس کد را دستی وارد کند باز هم باید روی صفحه دستگاه کودک تأیید شود."}
  ],
  "honestH": "«رمزگذاری‌شده» دقیقاً یعنی چه؟",
  "honestP": "رمزگذاری مهم است، اما امنیت واقعی چیزی بیش از یک نماد قفل است. پس اینجا می‌گوییم این فناوری چه می‌کند — و چه نمی‌کند.",
  "doesH": "کاری که WebRTC می‌کند",
  "does": [
    "تصویر و صدای زنده را در مسیر رمزگذاری می‌کند.",
    "هر زمان شبکه اجازه دهد، دستگاه‌ها را مستقیم به هم وصل می‌کند.",
    "وقتی ارتباط مستقیم ممکن نباشد، رسانه رمزگذاری‌شده را از یک بازپخش عبور می‌دهد."
  ],
  "youH": "کاری که شما هم باید بکنید",
  "you": [
    "کد QR خود را با کسی در میان نگذارید. هر کس کد جفت‌شدن فعال را ببیند می‌تواند برای پیوستن به جلسه تلاش کند.",
    "دستگاه‌هایتان را قفل کنید. یک گوشی قفل‌نشده خطری بزرگ‌تر از خود ارتباط اینترنتی است.",
    "مرورگرتان را به‌روز نگه دارید. به‌روزرسانی‌های امنیتی iOS، اندروید و مرورگر همچنان مهم‌اند."
  ],
  "noticeLead": "خوب است بدانید:",
  "notice": " «رمزگذاری‌شده» به‌خودی‌خود یعنی این نیست که هر برنامه‌ای از یک الگوی امنیتی یکسان استفاده می‌کند. واتساپ پروتکل سرتاسری خودش را با کلیدهای هویت دارد. BabyPhone.online برای رسانه زنده در مرورگر از امنیت درون‌ساخت WebRTC بهره می‌گیرد. هدف — نفرستادن هرگز صدا یا تصویر بی‌محافظ روی اینترنت — مشابه است، اما معماری فرق دارد. ترجیح می‌دهیم این را روشن بگوییم تا اینکه ادعای دیگری را وام بگیریم.",
  "designH": "یک پایشگر کودک باید کمترین اطلاعات ممکن را درباره خانواده شما بداند",
  "designP": "اصل کار BabyPhone.online همین است: کمترین گام‌های ممکن، بدون دسترسی غیرضروری به دستگاه شما، بدون حساب کاربری، بدون تبلیغات، بدون ردیابی، و تنها یک ارتباط زنده موقت میان دو دستگاهی که خودتان جفت کرده‌اید. چیزی ضبط نمی‌شود و هیچ سروری تماشا نمی‌کند.",
  "faqH": "امنیت در یک نگاه",
  "faq": [
    {"n": "آیا کسی می‌تواند همین‌طوری دوربین من را روشن کند؟",
     "d": "نه، بدون اجازه دوربین که به مرورگر داده‌اید. افزون بر این، پیوستن به یک جلسه زنده نیازمند جفت‌شدن درست است و بیننده دوم باید روی صفحه دستگاه کودک تأیید شود. پس هرگز کد QR یا کد اتاق فعال را عمومی نکنید."},
    {"n": "آیا BabyPhone.online می‌تواند تصویر مرا در مسیر ببیند؟",
     "d": "WebRTC رسانه زنده را در مسیر رمزگذاری می‌کند. وقتی به سبب مسدودبودن مسیر مستقیم به سرور بازپخش نیاز شود، آن سرور تنها رسانه محافظت‌شده را عبور می‌دهد — نه می‌تواند ببیند و نه بشنود."},
    {"n": "آیا این همان واتساپ است؟",
     "d": "نه به‌معنای دقیق. واتساپ پروتکل سرتاسری خود را با کلیدهای هویت دارد؛ BabyPhone.online برای رسانه امن بی‌درنگ در مرورگر از WebRTC استفاده می‌کند. هدف مشابه است، معماری فنی یکی نیست."},
    {"n": "خودم برای بیشترین امنیت چه کنم؟",
     "d": "از دستگاه و مرورگر به‌روز استفاده کنید، کد اتاق و QR را نزد خود نگه دارید، قفل صفحه را فعال کنید، پس از پایان جلسه را ببندید و BabyPhone.online را تنها از نشانی رسمی HTTPS باز کنید."}
  ],
  "ctaH": "می‌خواهید امتحان کنید؟",
  "ctaP": "دو دستگاه، بدون نصب و بدون حساب. سایت را روی هر دو باز کنید و جفتشان کنید.",
  "ctaBtn": "بازکردن BabyPhone.online",
  "toBlog": "راهنمای کامل را بخوانید: هر آنچه BabyPhone.online می‌تواند انجام دهد ←",
  "backToApp": "← بازگشت به برنامه",
}

T['ur'] = {
  "title": "آپ کا بے بی مانیٹر کیسے محفوظ ہے؟ | BabyPhone.online",
  "desc": "BabyPhone.online کیسے کام کرتا ہے اور جدید براؤزر ٹیکنالوجی اور WebRTC آپ کے آلات کے درمیان براہِ راست ویڈیو اور آواز کی حفاظت کیسے کرتے ہیں۔",
  "kicker": "سیکیورٹی اور رازداری",
  "h1": "BabyPhone.online کیسے کام کرتا ہے — اور آپ کا کنکشن نجی کیسے رہتا ہے",
  "lede": "BabyPhone.online آپ کے پہلے سے موجود دو آلات کو بے بی مانیٹر بنا دیتا ہے۔ ایک بچے کے پاس رہتا ہے اور دوسرا آپ کے ساتھ۔ نیچے آسان زبان میں بتایا گیا ہے کہ رابطہ کیسے قائم ہوتا ہے اور جدید براؤزر سیکیورٹی آپ کی براہِ راست ویڈیو اور آواز کی حفاظت کیسے کرتی ہے۔",
  "readTime": "۵ منٹ کا مطالعہ",
  "updated": "اگست 2026 میں تازہ کاری",
  "cardH": "رازداری ڈیزائن سے شروع ہوتی ہے",
  "cardP": "مقصد سادہ ہے: براہِ راست سیشن میں صرف وہی دو آلات شامل ہوتے ہیں جنہیں آپ نے خود جوڑا ہے۔",
  "cardList": [
    "کیمرے اور مائیکروفون کی اجازت خود براؤزر آپ سے مانگتا ہے۔",
    "WebRTC براہِ راست ویڈیو اور آواز کو راستے میں خفیہ کرتا ہے۔",
    "QR کوڈ سے جوڑنے پر لمبے کوڈ لکھنے کی ضرورت نہیں رہتی۔"
  ],
  "introP": "روایتی بے بی مانیٹر دو کم فاصلے والے وائرلیس سیٹ ہوتے ہیں جنہیں خریدنا، چارج کرنا اور ساتھ لے جانا پڑتا ہے۔ BabyPhone.online دوسرا راستہ چنتا ہے: آپ کے اپنے آلات براؤزر ہی میں کیمرہ اور مانیٹر بن جاتے ہیں۔ یہاں ایک جائز سوال اٹھتا ہے — جب یہ انٹرنیٹ پر چلتا ہے تو اور کون دیکھ سکتا ہے؟",
  "stepsH": "چار مرحلوں میں دو آلات سے بے بی مانیٹر تک",
  "stepsP": "کسی خاص ہارڈویئر کی ضرورت نہیں۔ جدید براؤزر والا فون، ٹیبلٹ یا لیپ ٹاپ کافی ہے۔",
  "steps": [
    "وہ آلہ لیں جسے بچے کے پاس رکھنا ہے اور اس پر ویب سائٹ کھولیں۔",
    "براؤزر کیمرے اور مائیکروفون کی اجازت مانگے گا۔ آپ کی اجازت کے بغیر ویب سائٹ ان تک نہیں پہنچ سکتی۔",
    "QR کوڈ سے اپنا دوسرا آلہ اسی سیشن سے جوڑیں۔",
    "دونوں براؤزر ویڈیو اور آواز کے لیے براہِ راست، حقیقی وقت کا رابطہ بناتے ہیں۔"
  ],
  "flowH": "آپ کی براہِ راست تصویر عام، غیر محفوظ ویڈیو کی طرح نہیں بھیجی جاتی",
  "flowP": "BabyPhone.online‏ WebRTC استعمال کرتا ہے: وہ براؤزر ٹیکنالوجی جو حقیقی وقت کی آواز اور ویڈیو کے لیے بنی ہے — وہی جو ویڈیو کالز میں کام آتی ہے۔",
  "flowBaby": "بچے کا آلہ",
  "flowBabySub": "کیمرہ + مائیکروفون",
  "flowLink": "WebRTC",
  "flowLinkSub": "خفیہ میڈیا رابطہ",
  "flowParent": "والدین کا آلہ",
  "flowParentSub": "براہِ راست مانیٹر",
  "flowNote": "نیٹ ورک کے مطابق WebRTC دونوں آلات کو براہِ راست جوڑ دیتا ہے، یا اگر سیدھا راستہ بند ہو تو خفیہ ڈیٹا کو ریلے (TURN) سرور سے گزار دیتا ہے۔",
  "layersH": "تحفظ کی چار تہیں، آسان الفاظ میں",
  "layers": [
    {"n": "۱۔ HTTPS ویب سائٹ کے رابطے کی حفاظت کرتا ہے",
     "d": "آپ کا براؤزر BabyPhone.online تک HTTPS کے ذریعے پہنچتا ہے۔ اس سے نیٹ ورک پر موجود دوسروں کے لیے صفحہ پڑھنا یا راستے میں بدلنا مشکل ہو جاتا ہے۔"},
    {"n": "۲۔ WebRTC براہِ راست ویڈیو اور آواز کی حفاظت کرتا ہے",
     "d": "WebRTC حقیقی وقت کے میڈیا کے لیے محفوظ ترسیل استعمال کرتا ہے، اس لیے سلسلہ انٹرنیٹ پر پڑھے جانے کے قابل، غیر محفوظ ڈیٹا کی صورت میں سفر نہیں کرتا۔"},
    {"n": "۳۔ کیمرے اور مائیکروفون کی اجازت آپ دیتے ہیں",
     "d": "ویب سائٹ خاموشی سے کیمرہ نہیں کھول سکتی۔ براؤزر اپنی اجازت کی درخواست دکھاتا ہے، اور آپ یہ اجازت بعد میں واپس بھی لے سکتے ہیں۔"},
    {"n": "۴۔ QR کوڈ درست سیشن سے جوڑتا ہے",
     "d": "اسکین کرنے سے لکھنے کی غلطی نہیں ہوتی اور اسکین کرنے والے آلے کو ایک بار استعمال ہونے والی کلید ملتی ہے۔ جو کوئی کوڈ ہاتھ سے لکھے، اسے پھر بھی بچے کے آلے کی اسکرین پر منظوری لینا ہوگی۔"}
  ],
  "honestH": "«خفیہ» کا اصل مطلب کیا ہے؟",
  "honestP": "خفیہ کاری اہم ہے، مگر اصل حفاظت ایک تالے کے نشان سے کہیں بڑھ کر ہے۔ سو یہ ہے کہ یہ ٹیکنالوجی کیا کرتی ہے — اور کیا نہیں کرتی۔",
  "doesH": "WebRTC کیا کرتا ہے",
  "does": [
    "براہِ راست ویڈیو اور آواز کو راستے میں خفیہ کرتا ہے۔",
    "جب بھی نیٹ ورک اجازت دے، آپ کے آلات کو براہِ راست جوڑتا ہے۔",
    "براہِ راست رابطہ ممکن نہ ہو تو خفیہ میڈیا کو ریلے سے گزارتا ہے۔"
  ],
  "youH": "آپ کو بھی کیا کرنا چاہیے",
  "you": [
    "اپنا QR کوڈ کسی کو نہ دیں۔ جو کوئی فعال جوڑنے والا کوڈ دیکھ لے، وہ اس سیشن میں شامل ہونے کی کوشش کر سکتا ہے۔",
    "اپنے آلات لاک رکھیں۔ کھلا ہوا فون خود انٹرنیٹ کنکشن سے بڑا خطرہ ہے۔",
    "براؤزر کو تازہ رکھیں۔ iOS، اینڈرائیڈ اور براؤزر کی سیکیورٹی اپ ڈیٹس اہم رہتی ہیں۔"
  ],
  "noticeLead": "جاننے کی بات:",
  "notice": " «خفیہ» ہونے کا خودبخود یہ مطلب نہیں کہ ہر ایپ ایک ہی سیکیورٹی ماڈل استعمال کرتی ہے۔ واٹس ایپ کا اپنا اینڈ ٹو اینڈ پروٹوکول اور شناختی کلیدیں ہیں۔ BabyPhone.online براؤزر کے براہِ راست میڈیا کے لیے WebRTC میں شامل سیکیورٹی استعمال کرتا ہے۔ مقصد — غیر محفوظ آواز یا ویڈیو کبھی انٹرنیٹ پر نہ بھیجنا — ملتا جلتا ہے، مگر ساخت مختلف ہے۔ ہم دوسروں کا دعویٰ ادھار لینے کے بجائے یہ بات صاف کہنا بہتر سمجھتے ہیں۔",
  "designH": "بے بی مانیٹر کو آپ کے خاندان کے بارے میں کم سے کم جاننا چاہیے",
  "designP": "BabyPhone.online کا اصول یہی ہے: کم سے کم مراحل، آپ کے آلے تک کوئی غیر ضروری رسائی نہیں، نہ اکاؤنٹ، نہ اشتہار، نہ ٹریکنگ، اور صرف ان دو آلات کے درمیان ایک عارضی رابطہ جو آپ نے خود جوڑے۔ کچھ ریکارڈ نہیں ہوتا اور کوئی سرور ساتھ نہیں دیکھتا۔",
  "faqH": "مختصراً سیکیورٹی",
  "faq": [
    {"n": "کیا کوئی یونہی میرا کیمرہ کھول سکتا ہے؟",
     "d": "براؤزر کی کیمرہ اجازت کے بغیر نہیں۔ اس کے علاوہ براہِ راست سیشن میں شامل ہونے کے لیے درست جوڑ ضروری ہے، اور دوسرے دیکھنے والے کو بچے کے آلے کی اسکرین پر منظوری لینا ہوتی ہے۔ اس لیے فعال QR یا روم کوڈ کبھی عام نہ کریں۔"},
    {"n": "کیا BabyPhone.online راستے میں میری ویڈیو دیکھ سکتا ہے؟",
     "d": "WebRTC براہِ راست میڈیا کو راستے میں خفیہ کرتا ہے۔ جب نیٹ ورک سیدھا راستہ روک دے اور ریلے سرور درکار ہو، تو وہ صرف محفوظ میڈیا آگے بھیجتا ہے — اسے دیکھ یا سن نہیں سکتا۔"},
    {"n": "کیا یہ واٹس ایپ جیسا ہی ہے؟",
     "d": "لفظی طور پر نہیں۔ واٹس ایپ شناختی کلیدوں کے ساتھ اپنا اینڈ ٹو اینڈ پروٹوکول استعمال کرتا ہے؛ BabyPhone.online براؤزر میں محفوظ حقیقی وقت کے میڈیا کے لیے WebRTC استعمال کرتا ہے۔ مقصد ملتا جلتا ہے، تکنیکی ساخت نہیں۔"},
    {"n": "زیادہ سے زیادہ حفاظت کے لیے میں کیا کروں؟",
     "d": "تازہ آلہ اور براؤزر استعمال کریں، روم کوڈ اور QR اپنے پاس رکھیں، اسکرین لاک آن رکھیں، کام ختم ہونے پر سیشن بند کریں، اور BabyPhone.online صرف اس کے سرکاری HTTPS پتے سے کھولیں۔"}
  ],
  "ctaH": "آزمانا چاہیں گے؟",
  "ctaP": "دو آلات، نہ کوئی انسٹال، نہ اکاؤنٹ۔ دونوں پر سائٹ کھولیں اور جوڑ دیں۔",
  "ctaBtn": "BabyPhone.online کھولیں",
  "toBlog": "مکمل رہنما پڑھیں: BabyPhone.online کیا کچھ کر سکتا ہے ←",
  "backToApp": "← ایپ پر واپس",
}

T['sw'] = {
  "title": "Kifaa chako cha kufuatilia mtoto kinalindwaje? | BabyPhone.online",
  "desc": "Jinsi BabyPhone.online inavyofanya kazi na jinsi video na sauti ya moja kwa moja kati ya vifaa vyako inavyolindwa na teknolojia ya kisasa ya kivinjari na WebRTC.",
  "kicker": "USALAMA NA FARAGHA",
  "h1": "Jinsi BabyPhone.online inavyofanya kazi — na jinsi muunganisho wako unavyobaki wa faragha",
  "lede": "BabyPhone.online hubadilisha vifaa viwili ulivyo navyo tayari kuwa kifaa cha kufuatilia mtoto. Kimoja hukaa karibu na mtoto, kingine unakwenda nacho. Hapa chini tunaeleza jinsi muunganisho unavyoundwa na jinsi usalama wa kisasa wa kivinjari unavyolinda video na sauti yako ya moja kwa moja — kwa lugha rahisi, bila maneno magumu.",
  "readTime": "Dakika 5 za kusoma",
  "updated": "Imesasishwa Agosti 2026",
  "cardH": "Faragha huanzia kwenye muundo",
  "cardP": "Lengo ni rahisi: ni vifaa viwili tu ulivyounganisha mwenyewe vinavyoshiriki kwenye kipindi cha moja kwa moja.",
  "cardList": [
    "Kivinjari chako chenyewe ndicho kinachoomba ruhusa ya kamera na maikrofoni.",
    "WebRTC husimba video na sauti ya moja kwa moja zikiwa njiani.",
    "Kuunganisha kwa msimbo wa QR hukuepusha kuandika misimbo mirefu."
  ],
  "introP": "Kifaa cha kawaida cha kufuatilia mtoto ni jozi ya redio za masafa mafupi unazopaswa kununua, kuchaji na kubeba. BabyPhone.online huchukua njia nyingine: vifaa vyako mwenyewe vinakuwa kamera na kioo cha kufuatilia, moja kwa moja kwenye kivinjari. Hapo swali la haki hujitokeza — kama inapita kwenye intaneti, ni nani mwingine anaweza kuona?",
  "stepsH": "Kutoka vifaa viwili hadi kifuatiliaji kwa hatua nne",
  "stepsP": "Hakuna vifaa maalum vinavyohitajika. Simu, kompyuta kibao au kompyuta ndogo yenye kivinjari cha kisasa inatosha.",
  "steps": [
    "Fungua tovuti kwenye kifaa unachotaka kuweka karibu na mtoto.",
    "Kivinjari kitaomba ruhusa ya kamera na maikrofoni. Bila ruhusa yako, tovuti haiwezi kuvifikia.",
    "Tumia msimbo wa QR kuunganisha kifaa chako cha pili kwenye kipindi kilekile.",
    "Vivinjari viwili hujenga muunganisho wa moja kwa moja, wa papo hapo, kwa video na sauti."
  ],
  "flowH": "Picha yako ya moja kwa moja haitumwi kama video ya kawaida isiyolindwa",
  "flowP": "BabyPhone.online hutumia WebRTC: teknolojia ya kivinjari iliyoundwa kwa sauti na video ya papo hapo — ileile ambayo kivinjari chako hutumia kwa simu za video.",
  "flowBaby": "Kifaa cha mtoto",
  "flowBabySub": "kamera + maikrofoni",
  "flowLink": "WebRTC",
  "flowLinkSub": "muunganisho wa midia uliosimbwa",
  "flowParent": "Kifaa cha mzazi",
  "flowParentSub": "kufuatilia moja kwa moja",
  "flowNote": "Kutegemea mtandao, WebRTC huunganisha vifaa hivyo viwili moja kwa moja, au hupitisha data iliyosimbwa kupitia seva ya kupitisha (TURN) pale njia ya moja kwa moja inapozuiwa.",
  "layersH": "Tabaka nne za ulinzi, kwa maelezo rahisi",
  "layers": [
    {"n": "1. HTTPS hulinda muunganisho na tovuti",
     "d": "Kivinjari chako hufika BabyPhone.online kupitia HTTPS. Hilo husaidia kuzuia wengine kwenye mtandao kusoma au kubadilisha ukurasa ukiwa njiani."},
    {"n": "2. WebRTC hulinda video na sauti ya moja kwa moja",
     "d": "WebRTC hutumia usafirishaji salama kwa midia ya papo hapo, hivyo mtiririko hausafiri kwenye intaneti kama data inayosomeka na isiyolindwa."},
    {"n": "3. Wewe ndiye unayetoa ruhusa ya kamera na maikrofoni",
     "d": "Tovuti haiwezi kuwasha kamera yako kimyakimya. Kivinjari huonyesha ombi lake lenyewe, na unaweza kuondoa ruhusa hiyo baadaye."},
    {"n": "4. Msimbo wa QR huunganisha kipindi sahihi",
     "d": "Kuskani huondoa makosa ya kuandika, na kifaa kinachoskani hupata ufunguo wa matumizi moja. Yeyote aliyeandika msimbo kwa mkono bado lazima aidhinishwe kwenye skrini ya kifaa cha mtoto."}
  ],
  "honestH": "«Imesimbwa» maana yake nini hasa?",
  "honestP": "Usimbaji ni muhimu, lakini usalama halisi ni zaidi ya alama ya kufuli. Kwa hiyo hivi ndivyo teknolojia hii inavyofanya — na isivyofanya.",
  "doesH": "Yale WebRTC inayoyafanya",
  "does": [
    "Husimba video na sauti ya moja kwa moja zikiwa njiani.",
    "Huunganisha vifaa vyako moja kwa moja kila mtandao unaporuhusu.",
    "Hupitisha midia iliyosimbwa kupitia kipitishio pale muunganisho wa moja kwa moja hauwezekani."
  ],
  "youH": "Yale unayopaswa kufanya wewe pia",
  "you": [
    "Usishiriki msimbo wako wa QR. Yeyote anayeona msimbo hai wa kuunganisha anaweza kujaribu kujiunga na kipindi hicho.",
    "Funga vifaa vyako kwa kufuli. Simu isiyofungwa ni hatari kubwa kuliko muunganisho wa intaneti wenyewe.",
    "Weka kivinjari chako kisasa. Masasisho ya usalama ya iOS, Android na kivinjari bado ni muhimu."
  ],
  "noticeLead": "Ni vyema kujua:",
  "notice": " «imesimbwa» haimaanishi moja kwa moja kwamba kila programu hutumia mfumo uleule wa usalama. WhatsApp ina itifaki yake ya mwisho-hadi-mwisho yenye funguo za utambulisho. BabyPhone.online hutumia usalama uliomo ndani ya WebRTC kwa midia ya moja kwa moja kwenye kivinjari. Lengo — kutotuma kamwe sauti au video isiyolindwa kwenye intaneti — linafanana, lakini muundo ni tofauti. Tunapendelea kusema hivyo waziwazi kuliko kuazima madai ya wengine.",
  "designH": "Kifuatiliaji cha mtoto kinapaswa kujua kidogo iwezekanavyo kuhusu familia yako",
  "designP": "Hiyo ndiyo kanuni ya BabyPhone.online: hatua chache iwezekanavyo, hakuna ufikiaji usio wa lazima kwenye kifaa chako, hakuna akaunti, hakuna matangazo, hakuna ufuatiliaji, na muunganisho wa muda tu kati ya vifaa viwili ulivyounganisha mwenyewe. Hakuna kinachorekodiwa na hakuna seva inayotazama.",
  "faqH": "Usalama kwa kifupi",
  "faq": [
    {"n": "Je, mtu anaweza kuwasha kamera yangu tu hivyo?",
     "d": "Hapana, bila ruhusa ya kamera kutoka kwa kivinjari chako. Zaidi ya hayo, kujiunga na kipindi cha moja kwa moja kunahitaji muunganisho sahihi, na mtazamaji wa pili lazima aidhinishwe kwenye skrini ya kifaa cha mtoto. Kwa hiyo usishiriki hadharani msimbo hai wa QR au wa chumba."},
    {"n": "Je, BabyPhone.online inaweza kuona video yangu ikiwa njiani?",
     "d": "WebRTC husimba midia ya moja kwa moja ikiwa njiani. Pale seva ya kupitisha inapohitajika kwa sababu mtandao wako unazuia njia ya moja kwa moja, hupitisha tu midia iliyolindwa — haiwezi kuiona wala kuisikia."},
    {"n": "Je, hii ni sawa na WhatsApp?",
     "d": "Si kwa maana halisi. WhatsApp hutumia itifaki yake ya mwisho-hadi-mwisho yenye funguo za utambulisho; BabyPhone.online hutumia WebRTC kwa midia salama ya papo hapo kwenye kivinjari. Lengo linafanana, muundo wa kiufundi si uleule."},
    {"n": "Nifanye nini mwenyewe kwa usalama wa juu?",
     "d": "Tumia kifaa na kivinjari cha kisasa, weka msimbo wa chumba na QR kuwa siri, washa kufuli la skrini, funga kipindi ukimaliza, na fungua BabyPhone.online kupitia anwani yake rasmi ya HTTPS pekee."}
  ],
  "ctaH": "Tayari kujaribu?",
  "ctaP": "Vifaa viwili, hakuna usakinishaji, hakuna akaunti. Fungua tovuti kwenye vyote viwili na viunganishe.",
  "ctaBtn": "Fungua BabyPhone.online",
  "toBlog": "Soma mwongozo kamili: kila kitu BabyPhone.online inachoweza →",
  "backToApp": "← Rudi kwenye programu",
}
