# -*- coding: utf-8 -*-
T = {}

T['ru'] = {
  "title": "Как защищена ваша радионяня? | BabyPhone.online",
  "desc": "Как работает BabyPhone.online и как современные технологии браузера и WebRTC защищают видео и звук между вашими устройствами.",
  "kicker": "БЕЗОПАСНОСТЬ И ПРИВАТНОСТЬ",
  "h1": "Как работает BabyPhone.online — и почему связь остаётся приватной",
  "lede": "BabyPhone.online превращает два ваших устройства в радионяню. Одно остаётся рядом с ребёнком, второе вы берёте с собой. Ниже — как устанавливается соединение и как современная защита браузера оберегает живое видео и звук. Простым языком, без жаргона.",
  "readTime": "5 мин чтения",
  "updated": "Обновлено в августе 2026",
  "cardH": "Приватность начинается с замысла",
  "cardP": "Цель проста: в живой сессии участвуют только те два устройства, которые вы связали сами.",
  "cardList": [
    "Браузер сам запрашивает разрешение на камеру и микрофон.",
    "WebRTC шифрует видео и звук в пути.",
    "Связывание по QR-коду избавляет от набора длинных кодов."
  ],
  "introP": "Классическая радионяня — это пара маломощных раций, которые нужно купить, заряжать и возить с собой. BabyPhone.online идёт другим путём: ваши собственные устройства становятся камерой и монитором прямо в браузере. Отсюда закономерный вопрос: если всё идёт через интернет, кто ещё может подсматривать?",
  "stepsH": "От двух устройств к радионяне за четыре шага",
  "stepsP": "Специальное оборудование не нужно. Достаточно телефона, планшета или ноутбука с современным браузером.",
  "steps": [
    "Откройте сайт на устройстве, которое поставите рядом с ребёнком.",
    "Браузер запросит доступ к камере и микрофону. Без вашего разрешения сайт до них не доберётся.",
    "С помощью QR-кода подключите второе устройство к той же сессии.",
    "Два браузера устанавливают прямое соединение в реальном времени для видео и звука."
  ],
  "flowH": "Ваше живое изображение не передаётся как обычное незащищённое видео",
  "flowP": "BabyPhone.online использует WebRTC — браузерную технологию для звука и видео в реальном времени, ту же, что применяется для видеозвонков.",
  "flowBaby": "Устройство у ребёнка",
  "flowBabySub": "камера + микрофон",
  "flowLink": "WebRTC",
  "flowLinkSub": "зашифрованный медиаканал",
  "flowParent": "Устройство родителя",
  "flowParentSub": "живой монитор",
  "flowNote": "В зависимости от сети WebRTC соединяет устройства напрямую или пропускает зашифрованный поток через сервер-ретранслятор (TURN), если прямой путь закрыт.",
  "layersH": "Четыре уровня защиты простыми словами",
  "layers": [
    {"n": "1. HTTPS защищает соединение с сайтом",
     "d": "Браузер обращается к BabyPhone.online по HTTPS. Это мешает другим в сети читать страницу или подменять её по пути."},
    {"n": "2. WebRTC защищает живое видео и звук",
     "d": "WebRTC использует защищённый транспорт для медиа реального времени, поэтому поток не идёт по интернету как читаемые незащищённые данные."},
    {"n": "3. Доступ к камере и микрофону даёте вы",
     "d": "Сайт не может тихо включить камеру. Браузер показывает собственный запрос, и разрешение можно позже отозвать."},
    {"n": "4. QR-код связывает нужную сессию",
     "d": "Сканирование исключает опечатки, а сканирующее устройство получает одноразовый ключ. Тот, кто ввёл код вручную, всё равно должен быть одобрен на экране устройства у ребёнка."}
  ],
  "honestH": "Что на самом деле значит «зашифровано»?",
  "honestP": "Шифрование важно, но настоящая безопасность — это больше, чем значок замка. Вот что технология делает, а чего не делает.",
  "doesH": "Что делает WebRTC",
  "does": [
    "Шифрует живое видео и звук в пути.",
    "Соединяет устройства напрямую, когда сеть это позволяет.",
    "Пропускает зашифрованные медиа через ретранслятор, если прямое соединение невозможно."
  ],
  "youH": "Что стоит сделать и вам",
  "you": [
    "Не делитесь QR-кодом. Тот, кто увидит активный код связывания, может попытаться войти в сессию.",
    "Блокируйте устройства. Разблокированный телефон опаснее, чем само интернет-соединение.",
    "Обновляйте браузер. Обновления безопасности iOS, Android и браузера по-прежнему важны."
  ],
  "noticeLead": "Важно понимать:",
  "notice": " «зашифровано» не означает автоматически, что все приложения используют одну и ту же модель безопасности. У WhatsApp собственный сквозной протокол с ключами личности. BabyPhone.online использует защиту, встроенную в WebRTC, для живых медиа в браузере. Цель — никогда не отправлять незащищённые звук и видео через интернет — сопоставима, но архитектура другая. Мы предпочитаем говорить об этом прямо, а не заимствовать чужие обещания.",
  "designH": "Радионяня должна знать о вашей семье как можно меньше",
  "designP": "Это и есть принцип BabyPhone.online: минимум шагов, никакого лишнего доступа к устройству, без аккаунта, без рекламы, без слежки и временная связь между двумя устройствами, которые вы связали сами. Ничего не записывается, и ни один сервер не подсматривает.",
  "faqH": "Безопасность кратко",
  "faq": [
    {"n": "Может ли кто-то просто включить мою камеру?",
     "d": "Нет, без разрешения на камеру, выданного браузеру. Кроме того, для входа в живую сессию нужна правильная связка, а второй зритель должен быть одобрен на экране устройства у ребёнка. Поэтому никогда не публикуйте активный QR-код или код комнаты."},
    {"n": "Может ли BabyPhone.online смотреть моё видео по дороге?",
     "d": "WebRTC шифрует живые медиа в пути. Если нужен сервер-ретранслятор, потому что сеть закрывает прямой путь, он лишь пропускает защищённые данные — увидеть или услышать поток он не может."},
    {"n": "Это то же самое, что WhatsApp?",
     "d": "Не буквально. У WhatsApp собственный сквозной протокол с ключами личности; BabyPhone.online использует WebRTC для защищённых медиа реального времени в браузере. Цель сопоставима, техническая архитектура — нет."},
    {"n": "Что я могу сделать для максимальной безопасности?",
     "d": "Используйте актуальные устройство и браузер, держите код комнаты и QR в тайне, включите блокировку экрана, закрывайте сессию по окончании и открывайте BabyPhone.online только по официальному адресу HTTPS."}
  ],
  "ctaH": "Хотите попробовать?",
  "ctaP": "Два устройства, без установки и без аккаунта. Откройте сайт на обоих и свяжите их.",
  "ctaBtn": "Открыть BabyPhone.online",
  "toBlog": "Читать полное руководство: всё, что умеет BabyPhone.online →",
  "backToApp": "← Назад в приложение",
}

T['uk'] = {
  "title": "Як захищена ваша радіоняня? | BabyPhone.online",
  "desc": "Як працює BabyPhone.online і як сучасні технології браузера та WebRTC захищають відео й звук між вашими пристроями.",
  "kicker": "БЕЗПЕКА ТА ПРИВАТНІСТЬ",
  "h1": "Як працює BabyPhone.online — і чому ваше з'єднання лишається приватним",
  "lede": "BabyPhone.online перетворює два ваші пристрої на радіоняню. Один лишається біля дитини, другий ви берете із собою. Нижче — як встановлюється з'єднання і як сучасний захист браузера оберігає живе відео та звук. Простою мовою, без жаргону.",
  "readTime": "5 хв читання",
  "updated": "Оновлено в серпні 2026",
  "cardH": "Приватність починається із задуму",
  "cardP": "Мета проста: у живій сесії беруть участь лише ті два пристрої, які ви з'єднали самі.",
  "cardList": [
    "Браузер сам запитує дозвіл на камеру та мікрофон.",
    "WebRTC шифрує відео та звук у дорозі.",
    "З'єднання за QR-кодом позбавляє потреби набирати довгі коди."
  ],
  "introP": "Класична радіоняня — це пара рацій малого радіуса, які треба купити, заряджати й возити з собою. BabyPhone.online іде іншим шляхом: ваші власні пристрої стають камерою й монітором просто в браузері. Звідси слушне питання: якщо все йде через інтернет, хто ще може дивитися?",
  "stepsH": "Від двох пристроїв до радіоняні за чотири кроки",
  "stepsP": "Спеціального обладнання не потрібно. Достатньо телефона, планшета чи ноутбука із сучасним браузером.",
  "steps": [
    "Відкрийте сайт на пристрої, який поставите біля дитини.",
    "Браузер попросить дозвіл на камеру та мікрофон. Без вашого дозволу сайт до них не дістанеться.",
    "За допомогою QR-коду під'єднайте другий пристрій до тієї самої сесії.",
    "Два браузери створюють пряме з'єднання в реальному часі для відео та звуку."
  ],
  "flowH": "Ваше живе зображення не передається як звичайне незахищене відео",
  "flowP": "BabyPhone.online використовує WebRTC — браузерну технологію для звуку й відео в реальному часі, ту саму, що й для відеодзвінків.",
  "flowBaby": "Пристрій біля дитини",
  "flowBabySub": "камера + мікрофон",
  "flowLink": "WebRTC",
  "flowLinkSub": "зашифрований медіаканал",
  "flowParent": "Пристрій батьків",
  "flowParentSub": "живий монітор",
  "flowNote": "Залежно від мережі WebRTC з'єднує пристрої напряму або пропускає зашифрований потік через сервер-ретранслятор (TURN), якщо прямий шлях заблоковано.",
  "layersH": "Чотири рівні захисту простими словами",
  "layers": [
    {"n": "1. HTTPS захищає з'єднання із сайтом",
     "d": "Браузер звертається до BabyPhone.online через HTTPS. Це заважає іншим у мережі читати сторінку чи змінювати її дорогою."},
    {"n": "2. WebRTC захищає живе відео та звук",
     "d": "WebRTC використовує захищений транспорт для медіа реального часу, тож потік не йде інтернетом як читабельні незахищені дані."},
    {"n": "3. Доступ до камери й мікрофона надаєте ви",
     "d": "Сайт не може тихо ввімкнути камеру. Браузер показує власний запит, і дозвіл можна згодом відкликати."},
    {"n": "4. QR-код з'єднує потрібну сесію",
     "d": "Сканування усуває помилки набору, а пристрій, що сканує, отримує одноразовий ключ. Той, хто ввів код вручну, все одно має бути схвалений на екрані пристрою біля дитини."}
  ],
  "honestH": "Що насправді означає «зашифровано»?",
  "honestP": "Шифрування важливе, але справжня безпека — це більше, ніж значок замка. Ось що технологія робить, а чого не робить.",
  "doesH": "Що робить WebRTC",
  "does": [
    "Шифрує живе відео та звук у дорозі.",
    "З'єднує пристрої напряму, коли мережа це дозволяє.",
    "Пропускає зашифровані медіа через ретранслятор, якщо пряме з'єднання неможливе."
  ],
  "youH": "Що варто зробити й вам",
  "you": [
    "Не діліться QR-кодом. Хто побачить активний код з'єднання, може спробувати долучитися до сесії.",
    "Блокуйте пристрої. Розблокований телефон небезпечніший за саме інтернет-з'єднання.",
    "Оновлюйте браузер. Оновлення безпеки iOS, Android і браузера лишаються важливими."
  ],
  "noticeLead": "Варто знати:",
  "notice": " «зашифровано» не означає автоматично, що кожен застосунок використовує ту саму модель безпеки. WhatsApp має власний наскрізний протокол із ключами особи. BabyPhone.online використовує захист, вбудований у WebRTC, для живих медіа в браузері. Мета — ніколи не надсилати незахищені звук чи відео через інтернет — порівнянна, але архітектура інша. Ми радше скажемо це прямо, ніж позичатимемо чужі обіцянки.",
  "designH": "Радіоняня має знати про вашу родину якомога менше",
  "designP": "Саме такий принцип у BabyPhone.online: якнайменше кроків, жодного зайвого доступу до пристрою, без облікового запису, без реклами, без стеження і тимчасове з'єднання між двома пристроями, які ви з'єднали самі. Нічого не записується, і жоден сервер не підглядає.",
  "faqH": "Безпека коротко",
  "faq": [
    {"n": "Чи може хтось просто ввімкнути мою камеру?",
     "d": "Ні, без дозволу на камеру, наданого браузеру. До того ж для входу в живу сесію потрібне правильне з'єднання, а другого глядача треба схвалити на екрані пристрою біля дитини. Тому ніколи не публікуйте активний QR-код чи код кімнати."},
    {"n": "Чи може BabyPhone.online дивитися моє відео дорогою?",
     "d": "WebRTC шифрує живі медіа в дорозі. Коли потрібен сервер-ретранслятор, бо мережа блокує прямий шлях, він лише пропускає захищені дані — побачити чи почути потік він не може."},
    {"n": "Це те саме, що WhatsApp?",
     "d": "Не буквально. WhatsApp має власний наскрізний протокол із ключами особи; BabyPhone.online використовує WebRTC для захищених медіа реального часу в браузері. Мета порівнянна, технічна архітектура — ні."},
    {"n": "Що я можу зробити для максимальної безпеки?",
     "d": "Користуйтеся актуальними пристроєм і браузером, тримайте код кімнати та QR у таємниці, увімкніть блокування екрана, закривайте сесію після завершення й відкривайте BabyPhone.online лише за офіційною HTTPS-адресою."}
  ],
  "ctaH": "Хочете спробувати?",
  "ctaP": "Два пристрої, без встановлення та без облікового запису. Відкрийте сайт на обох і з'єднайте їх.",
  "ctaBtn": "Відкрити BabyPhone.online",
  "toBlog": "Читати повний посібник: усе, що вміє BabyPhone.online →",
  "backToApp": "← Назад до застосунку",
}

T['tr'] = {
  "title": "Bebek telsiziniz nasıl korunuyor? | BabyPhone.online",
  "desc": "BabyPhone.online nasıl çalışır ve cihazlarınız arasındaki canlı görüntü ile ses, modern tarayıcı teknolojisi ve WebRTC ile nasıl korunur.",
  "kicker": "GÜVENLİK VE GİZLİLİK",
  "h1": "BabyPhone.online nasıl çalışır — ve bağlantınız nasıl özel kalır",
  "lede": "BabyPhone.online, zaten sahip olduğunuz iki cihazı bir bebek telsizine dönüştürür. Biri bebeğinizin yanında kalır, diğeri sizinle gelir. Aşağıda bağlantının nasıl kurulduğunu ve modern tarayıcı güvenliğinin canlı görüntü ve sesi nasıl koruduğunu anlatıyoruz — teknik jargon olmadan, sade bir dille.",
  "readTime": "5 dk okuma",
  "updated": "Ağustos 2026'da güncellendi",
  "cardH": "Gizlilik tasarımla başlar",
  "cardP": "Amaç basit: canlı oturuma yalnızca kendi eşleştirdiğiniz iki cihaz katılır.",
  "cardList": [
    "Kamera ve mikrofon izni doğrudan tarayıcınız tarafından istenir.",
    "WebRTC canlı görüntü ve sesi yol boyunca şifreler.",
    "QR kodla eşleştirme, uzun kodları elle yazma derdini ortadan kaldırır."
  ],
  "introP": "Klasik bir bebek telsizi, satın alıp şarj etmeniz ve yanınızda taşımanız gereken kısa menzilli iki telsizdir. BabyPhone.online başka bir yol izler: kendi cihazlarınız doğrudan tarayıcıda kamera ve monitör olur. Bu da haklı bir soruyu getirir — internet üzerinden çalışıyorsa, başka kim izleyebilir?",
  "stepsH": "İki cihazdan bebek telsizine dört adımda",
  "stepsP": "Özel donanım gerekmez. Güncel bir tarayıcıya sahip telefon, tablet veya dizüstü bilgisayar yeterlidir.",
  "steps": [
    "Bebeğinizin yanına koymak istediğiniz cihazda siteyi açın.",
    "Tarayıcı kamera ve mikrofon için izin ister. İzniniz olmadan site bunlara erişemez.",
    "İkinci cihazı aynı oturuma bağlamak için QR kodu kullanın.",
    "İki tarayıcı, görüntü ve ses için doğrudan ve gerçek zamanlı bir bağlantı kurar."
  ],
  "flowH": "Canlı görüntünüz sıradan, korumasız bir video olarak gönderilmez",
  "flowP": "BabyPhone.online WebRTC kullanır: gerçek zamanlı ses ve görüntü için geliştirilmiş tarayıcı teknolojisi — tarayıcınızın görüntülü aramalarda kullandığının aynısı.",
  "flowBaby": "Bebek cihazı",
  "flowBabySub": "kamera + mikrofon",
  "flowLink": "WebRTC",
  "flowLinkSub": "şifreli medya bağlantısı",
  "flowParent": "Ebeveyn cihazı",
  "flowParentSub": "canlı monitör",
  "flowNote": "Ağa bağlı olarak WebRTC iki cihazı doğrudan bağlar ya da doğrudan yol kapalıysa şifreli trafiği bir aktarma (TURN) sunucusundan geçirir.",
  "layersH": "Dört koruma katmanı, sade bir dille",
  "layers": [
    {"n": "1. HTTPS site bağlantısını korur",
     "d": "Tarayıcınız BabyPhone.online'a HTTPS üzerinden ulaşır. Bu, ağdaki başkalarının sayfayı yolda okumasını veya değiştirmesini engellemeye yardımcı olur."},
    {"n": "2. WebRTC canlı görüntü ve sesi korur",
     "d": "WebRTC gerçek zamanlı medya için güvenli taşıma kullanır; böylece akış internette okunabilir, korumasız veri olarak dolaşmaz."},
    {"n": "3. Kamera ve mikrofon iznini siz verirsiniz",
     "d": "Site kameranızı sessizce açamaz. Tarayıcı kendi izin sorusunu gösterir ve bu izni daha sonra geri alabilirsiniz."},
    {"n": "4. QR kod doğru oturumu bağlar",
     "d": "Taramak yazım hatalarını ortadan kaldırır ve tarayan cihaz tek kullanımlık bir anahtar alır. Kodu elle yazan kişinin yine de bebek cihazının kendi ekranında onaylanması gerekir."}
  ],
  "honestH": "«Şifreli» tam olarak ne demek?",
  "honestP": "Şifreleme önemlidir, ama gerçek güvenlik bir asma kilit simgesinden ibaret değildir. İşte teknolojinin yaptığı — ve yapmadığı.",
  "doesH": "WebRTC'nin yaptığı",
  "does": [
    "Canlı görüntü ve sesi yol boyunca şifreler.",
    "Ağ izin verdiği sürece cihazlarınızı doğrudan bağlar.",
    "Doğrudan bağlantı mümkün değilse şifreli medyayı bir aktarıcı üzerinden geçirir."
  ],
  "youH": "Sizin de yapmanız gerekenler",
  "you": [
    "QR kodunuzu paylaşmayın. Etkin bir eşleştirme kodunu gören biri oturuma katılmayı deneyebilir.",
    "Cihazlarınızı kilitleyin. Kilidi açık bir telefon, internet bağlantısının kendisinden daha büyük bir risktir.",
    "Tarayıcınızı güncel tutun. iOS, Android ve tarayıcı güvenlik güncellemeleri önemini korur."
  ],
  "noticeLead": "Bilmekte fayda var:",
  "notice": " «şifreli» olması, her uygulamanın aynı güvenlik modelini kullandığı anlamına gelmez. WhatsApp'ın kimlik anahtarlarıyla çalışan kendi uçtan uca protokolü vardır. BabyPhone.online, tarayıcıdaki canlı medya için WebRTC'nin içine yerleşik güvenliği kullanır. Amaç — korumasız ses veya görüntüyü asla internete göndermemek — benzerdir, ancak mimari farklıdır. Bunu başkasının iddiasını ödünç almak yerine açıkça söylemeyi tercih ediyoruz.",
  "designH": "Bir bebek telsizi aileniz hakkında mümkün olduğunca az şey bilmeli",
  "designP": "BabyPhone.online'ın arkasındaki ilke bu: mümkün olduğunca az adım, cihazınıza gereksiz erişim yok, hesap yok, reklam yok, takip yok ve kendi eşleştirdiğiniz iki cihaz arasında geçici bir canlı bağlantı. Hiçbir şey kaydedilmez ve hiçbir sunucu izlemez.",
  "faqH": "Kısaca güvenlik",
  "faq": [
    {"n": "Biri kameramı öylece açabilir mi?",
     "d": "Tarayıcınızdan kamera izni almadan hayır. Ayrıca canlı bir oturuma katılmak doğru eşleştirmeyi gerektirir ve ikinci bir izleyicinin bebek cihazının kendi ekranında onaylanması gerekir. Bu yüzden etkin bir QR kodu veya oda kodunu asla herkese açık paylaşmayın."},
    {"n": "BabyPhone.online görüntümü yolda izleyebilir mi?",
     "d": "WebRTC canlı medyayı yol boyunca şifreler. Ağınız doğrudan yolu engellediği için aktarma sunucusu gerektiğinde, bu sunucu yalnızca korunan medyayı geçirir — akışı görebilmesi veya duyabilmesi mümkün değildir."},
    {"n": "Bu WhatsApp ile aynı mı?",
     "d": "Birebir değil. WhatsApp kimlik anahtarlarıyla kendi uçtan uca protokolünü kullanır; BabyPhone.online tarayıcıda güvenli gerçek zamanlı medya için WebRTC kullanır. Amaç benzer, teknik mimari aynı değil."},
    {"n": "En yüksek güvenlik için ben ne yapabilirim?",
     "d": "Güncel bir cihaz ve tarayıcı kullanın, oda kodunuzu ve QR'ı kendinize saklayın, ekran kilidini açın, işiniz bittiğinde oturumu kapatın ve BabyPhone.online'ı yalnızca resmi HTTPS adresinden açın."}
  ],
  "ctaH": "Denemeye hazır mısınız?",
  "ctaP": "İki cihaz, kurulum yok, hesap yok. Siteyi ikisinde de açın ve eşleştirin.",
  "ctaBtn": "BabyPhone.online'ı aç",
  "toBlog": "Tam rehberi okuyun: BabyPhone.online neler yapabiliyor →",
  "backToApp": "← Uygulamaya dön",
}

T['id'] = {
  "title": "Bagaimana baby monitor Anda diamankan? | BabyPhone.online",
  "desc": "Cara kerja BabyPhone.online dan bagaimana video serta suara langsung antar perangkat Anda dilindungi oleh teknologi peramban modern dan WebRTC.",
  "kicker": "KEAMANAN & PRIVASI",
  "h1": "Cara kerja BabyPhone.online — dan bagaimana koneksi Anda tetap privat",
  "lede": "BabyPhone.online mengubah dua perangkat yang sudah Anda miliki menjadi baby monitor. Satu tetap di dekat bayi, satunya ikut dengan Anda. Berikut penjelasan bagaimana koneksi terbentuk dan bagaimana keamanan peramban modern melindungi video dan suara langsung Anda — dengan bahasa sederhana, tanpa istilah teknis.",
  "readTime": "5 menit baca",
  "updated": "Diperbarui Agustus 2026",
  "cardH": "Privasi dimulai dari rancangannya",
  "cardP": "Tujuannya sederhana: hanya dua perangkat yang Anda pasangkan sendiri yang ikut dalam sesi langsung.",
  "cardList": [
    "Peramban Anda sendiri yang meminta izin kamera dan mikrofon.",
    "WebRTC mengenkripsi video dan suara langsung selama perjalanan.",
    "Memasangkan lewat kode QR menghindarkan Anda mengetik kode panjang."
  ],
  "introP": "Baby monitor klasik adalah sepasang radio jarak pendek yang harus dibeli, diisi daya, dan dibawa-bawa. BabyPhone.online mengambil jalan lain: perangkat Anda sendiri menjadi kamera dan monitor, langsung di peramban. Muncul pertanyaan yang wajar — jika berjalan lewat internet, siapa lagi yang bisa ikut melihat?",
  "stepsH": "Dari dua perangkat menjadi baby monitor dalam empat langkah",
  "stepsP": "Tidak perlu perangkat keras khusus. Ponsel, tablet, atau laptop dengan peramban modern sudah cukup.",
  "steps": [
    "Buka situs di perangkat yang ingin Anda letakkan dekat bayi.",
    "Peramban meminta izin kamera dan mikrofon. Tanpa izin Anda, situs tidak bisa mengaksesnya.",
    "Gunakan kode QR untuk menghubungkan perangkat kedua ke sesi yang sama.",
    "Kedua peramban membangun koneksi langsung secara real-time untuk video dan suara."
  ],
  "flowH": "Gambar langsung Anda tidak dikirim sebagai video biasa tanpa perlindungan",
  "flowP": "BabyPhone.online memakai WebRTC: teknologi peramban yang dibuat untuk audio dan video real-time — sama seperti yang dipakai peramban untuk panggilan video.",
  "flowBaby": "Perangkat bayi",
  "flowBabySub": "kamera + mikrofon",
  "flowLink": "WebRTC",
  "flowLinkSub": "jalur media terenkripsi",
  "flowParent": "Perangkat orang tua",
  "flowParentSub": "monitor langsung",
  "flowNote": "Tergantung jaringannya, WebRTC menghubungkan kedua perangkat secara langsung, atau meneruskan lalu lintas terenkripsi lewat server relai (TURN) bila jalur langsung terhalang.",
  "layersH": "Empat lapis perlindungan, dijelaskan sederhana",
  "layers": [
    {"n": "1. HTTPS melindungi koneksi ke situs",
     "d": "Peramban Anda menghubungi BabyPhone.online lewat HTTPS. Ini membantu mencegah orang lain di jaringan ikut membaca atau mengubah halaman di tengah jalan."},
    {"n": "2. WebRTC melindungi video dan suara langsung",
     "d": "WebRTC memakai transportasi aman untuk media real-time, sehingga aliran tidak melintasi internet sebagai data terbaca yang tanpa perlindungan."},
    {"n": "3. Anda yang memberi akses kamera dan mikrofon",
     "d": "Situs tidak bisa menyalakan kamera diam-diam. Peramban menampilkan permintaan izinnya sendiri, dan izin itu bisa Anda cabut nanti."},
    {"n": "4. Kode QR menautkan sesi yang tepat",
     "d": "Memindai menghilangkan salah ketik, dan perangkat yang memindai menerima kunci sekali pakai. Siapa pun yang mengetik kode secara manual tetap harus disetujui di layar perangkat bayi."}
  ],
  "honestH": "Apa arti «terenkripsi» sebenarnya?",
  "honestP": "Enkripsi itu penting, tetapi keamanan sungguhan lebih dari sekadar ikon gembok. Jadi inilah yang dilakukan teknologi ini — dan yang tidak.",
  "doesH": "Yang dilakukan WebRTC",
  "does": [
    "Mengenkripsi video dan suara langsung selama perjalanan.",
    "Menghubungkan perangkat Anda secara langsung selama jaringan mengizinkan.",
    "Meneruskan media terenkripsi lewat relai bila koneksi langsung tidak memungkinkan."
  ],
  "youH": "Yang juga perlu Anda lakukan",
  "you": [
    "Jangan bagikan kode QR Anda. Siapa pun yang melihat kode pemasangan aktif bisa mencoba masuk ke sesi itu.",
    "Kunci perangkat Anda. Ponsel yang tidak terkunci lebih berisiko daripada koneksi internetnya sendiri.",
    "Perbarui peramban Anda. Pembaruan keamanan iOS, Android, dan peramban tetap penting."
  ],
  "noticeLead": "Perlu diketahui:",
  "notice": " «terenkripsi» tidak otomatis berarti setiap aplikasi memakai model keamanan yang sama. WhatsApp punya protokol ujung-ke-ujung sendiri dengan kunci identitas. BabyPhone.online memakai keamanan yang sudah tertanam di WebRTC untuk media langsung di peramban. Tujuannya — tidak pernah mengirim audio atau video tanpa perlindungan lewat internet — sebanding, tetapi arsitekturnya berbeda. Kami lebih memilih mengatakannya terus terang daripada meminjam klaim pihak lain.",
  "designH": "Baby monitor sebaiknya tahu sesedikit mungkin tentang keluarga Anda",
  "designP": "Itulah prinsip di balik BabyPhone.online: sesedikit mungkin langkah, tanpa akses yang tidak perlu ke perangkat Anda, tanpa akun, tanpa iklan, tanpa pelacakan, dan koneksi langsung yang bersifat sementara antara dua perangkat yang Anda pasangkan sendiri. Tidak ada yang direkam dan tidak ada server yang ikut menonton.",
  "faqH": "Keamanan secara singkat",
  "faq": [
    {"n": "Bisakah orang lain begitu saja menyalakan kamera saya?",
     "d": "Tidak, tanpa izin kamera dari peramban Anda. Selain itu, bergabung ke sesi langsung membutuhkan pemasangan yang benar, dan penonton kedua harus disetujui di layar perangkat bayi. Jadi jangan pernah membagikan kode QR atau kode ruang yang aktif secara terbuka."},
    {"n": "Bisakah BabyPhone.online melihat video saya di perjalanan?",
     "d": "WebRTC mengenkripsi media langsung selama perjalanan. Ketika server relai dibutuhkan karena jaringan Anda menghalangi jalur langsung, server itu hanya meneruskan media yang terlindungi — ia tidak bisa melihat atau mendengar aliran tersebut."},
    {"n": "Apakah ini sama dengan WhatsApp?",
     "d": "Tidak secara harfiah. WhatsApp memakai protokol ujung-ke-ujung sendiri dengan kunci identitas; BabyPhone.online memakai WebRTC untuk media real-time yang aman di peramban. Tujuannya sebanding, arsitektur teknisnya tidak sama."},
    {"n": "Apa yang bisa saya lakukan untuk keamanan maksimal?",
     "d": "Gunakan perangkat dan peramban yang mutakhir, rahasiakan kode ruang dan QR Anda, aktifkan kunci layar, tutup sesi setelah selesai, dan buka BabyPhone.online hanya lewat alamat HTTPS resminya."}
  ],
  "ctaH": "Siap mencobanya?",
  "ctaP": "Dua perangkat, tanpa pemasangan aplikasi, tanpa akun. Buka situsnya di keduanya lalu pasangkan.",
  "ctaBtn": "Buka BabyPhone.online",
  "toBlog": "Baca panduan lengkap: semua yang bisa dilakukan BabyPhone.online →",
  "backToApp": "← Kembali ke aplikasi",
}
