# -*- coding: utf-8 -*-
T = {}

T['zh'] = {
  "title": "你的婴儿监视器如何得到保护？| BabyPhone.online",
  "desc": "BabyPhone.online 的工作原理，以及现代浏览器技术和 WebRTC 如何保护设备之间的实时画面与声音。",
  "kicker": "安全与隐私",
  "h1": "BabyPhone.online 如何工作 —— 以及你的连接如何保持私密",
  "lede": "BabyPhone.online 把你已有的两台设备变成婴儿监视器。一台留在宝宝身边，另一台带在身上。下面用通俗的语言说明连接是怎么建立的，以及现代浏览器安全机制如何保护你的实时画面和声音。",
  "readTime": "阅读约 5 分钟",
  "updated": "更新于 2026 年 8 月",
  "cardH": "隐私从设计之初就开始",
  "cardP": "目标很简单：只有你自己配对的这两台设备才参与实时会话。",
  "cardList": [
    "摄像头和麦克风的权限由浏览器自己向你询问。",
    "WebRTC 在传输过程中对实时画面和声音加密。",
    "用二维码配对，省去手动输入长串代码。"
  ],
  "introP": "传统婴儿监视器是一对短距离对讲设备，需要购买、充电并随身携带。BabyPhone.online 走的是另一条路：你自己的设备直接在浏览器里变成摄像头和监视屏。这自然引出一个问题——既然走互联网，还有谁能看到？",
  "stepsH": "四步把两台设备变成婴儿监视器",
  "stepsP": "不需要专门的硬件。一部手机、平板或笔记本电脑，配上较新的浏览器就够了。",
  "steps": [
    "在你想放在宝宝身边的设备上打开网站。",
    "浏览器会请求摄像头和麦克风权限。未经你同意，网站无法访问。",
    "用二维码把第二台设备连接到同一个会话。",
    "两个浏览器为画面和声音建立直接的实时连接。"
  ],
  "flowH": "你的实时画面不会以普通、未受保护的视频形式传输",
  "flowP": "BabyPhone.online 使用 WebRTC：专为实时音视频设计的浏览器技术，与浏览器进行视频通话时用的是同一类技术。",
  "flowBaby": "宝宝端设备",
  "flowBabySub": "摄像头 + 麦克风",
  "flowLink": "WebRTC",
  "flowLinkSub": "加密的媒体连接",
  "flowParent": "家长端设备",
  "flowParentSub": "实时监看",
  "flowNote": "视网络情况，WebRTC 会让两台设备直接相连；当直连被阻断时，则通过中继（TURN）服务器转发已加密的数据。",
  "layersH": "四层保护，用通俗的话解释",
  "layers": [
    {"n": "1. HTTPS 保护与网站的连接",
     "d": "浏览器通过 HTTPS 访问 BabyPhone.online。这有助于防止网络上的其他人在传输途中读取或篡改网页。"},
    {"n": "2. WebRTC 保护实时画面和声音",
     "d": "WebRTC 为实时媒体使用安全传输，因此数据流不会以可读的、未受保护的形式在互联网上传送。"},
    {"n": "3. 摄像头和麦克风的权限由你授予",
     "d": "网站无法悄悄打开摄像头。浏览器会显示自己的授权提示，你之后也可以撤销该权限。"},
    {"n": "4. 二维码连接到正确的会话",
     "d": "扫码可避免输入错误，扫描的设备还会获得一次性密钥。手动输入代码的人，仍需在宝宝端设备的屏幕上获得批准。"}
  ],
  "honestH": "“加密”到底是什么意思？",
  "honestP": "加密很重要，但真正的安全不止一个锁形图标。所以这里说明这项技术能做什么——以及不能做什么。",
  "doesH": "WebRTC 能做到的",
  "does": [
    "在传输过程中加密实时画面和声音。",
    "只要网络允许，就让你的设备直接相连。",
    "无法直连时，通过中继转发已加密的媒体。"
  ],
  "youH": "你自己也要做的",
  "you": [
    "不要分享你的二维码。看到有效配对码的人可能会尝试加入该会话。",
    "锁好你的设备。一部未锁定的手机，风险比互联网连接本身更大。",
    "保持浏览器更新。iOS、Android 和浏览器的安全更新依然重要。"
  ],
  "noticeLead": "值得知道的是：",
  "notice": "“加密”并不自动意味着每个应用都采用相同的安全模型。WhatsApp 有自己的端到端协议和身份密钥。BabyPhone.online 对浏览器中的实时媒体使用 WebRTC 内建的安全机制。二者的目标相近——绝不把未受保护的音视频送上互联网——但架构不同。我们宁愿把这一点说清楚，也不愿借用别人的说法。",
  "designH": "婴儿监视器应当尽可能少地了解你的家庭",
  "designP": "这正是 BabyPhone.online 的原则：步骤尽量少，不对设备做多余的访问，无需账号，没有广告，不做追踪，只在你亲自配对的两台设备之间建立一条临时的实时连接。不录制任何内容，也没有服务器在旁观看。",
  "faqH": "安全要点",
  "faq": [
    {"n": "别人能随便打开我的摄像头吗？",
     "d": "没有浏览器授予的摄像头权限就不行。此外，加入实时会话需要正确的配对，第二位观看者还必须在宝宝端设备的屏幕上获得批准。因此，切勿公开分享有效的二维码或房间代码。"},
    {"n": "BabyPhone.online 能在传输途中看到我的画面吗？",
     "d": "WebRTC 在传输过程中对实时媒体加密。当你的网络阻断直连而需要中继服务器时，它只是转发受保护的媒体——既看不到也听不到内容。"},
    {"n": "这和 WhatsApp 一样吗？",
     "d": "并不完全一样。WhatsApp 使用自己的端到端协议和身份密钥；BabyPhone.online 使用 WebRTC 在浏览器中传输安全的实时媒体。目的相近，技术架构不同。"},
    {"n": "为了最高的安全性，我自己能做什么？",
     "d": "使用较新的设备和浏览器，妥善保管房间代码和二维码，开启屏幕锁，用完后关闭会话，并且只通过官方 HTTPS 地址打开 BabyPhone.online。"}
  ],
  "ctaH": "想试试看吗？",
  "ctaP": "两台设备，无需安装，无需账号。在两台设备上打开网站并完成配对。",
  "ctaBtn": "打开 BabyPhone.online",
  "toBlog": "阅读完整指南：BabyPhone.online 的全部功能 →",
  "backToApp": "← 返回应用",
}

T['ja'] = {
  "title": "ベビーモニターはどう守られている？| BabyPhone.online",
  "desc": "BabyPhone.online のしくみと、端末間のライブ映像・音声が最新のブラウザ技術と WebRTC でどう保護されるかを解説します。",
  "kicker": "セキュリティとプライバシー",
  "h1": "BabyPhone.online のしくみ — そして接続がプライベートに保たれる理由",
  "lede": "BabyPhone.online は、すでにお持ちの 2 台の端末をベビーモニターに変えます。1 台は赤ちゃんのそばに、もう 1 台は手元に。ここでは接続がどう確立されるのか、そして最新のブラウザのセキュリティがライブ映像と音声をどう守るのかを、専門用語を使わずに説明します。",
  "readTime": "読了 5 分",
  "updated": "2026 年 8 月更新",
  "cardH": "プライバシーは設計から始まる",
  "cardP": "目的はシンプルです。ライブセッションに参加するのは、ご自身がペアリングした 2 台だけです。",
  "cardList": [
    "カメラとマイクの許可は、ブラウザ自身が尋ねます。",
    "WebRTC がライブ映像と音声を送信中に暗号化します。",
    "QR コードでのペアリングなら、長いコードを打ち直す必要がありません。"
  ],
  "introP": "従来のベビーモニターは、購入して充電し、持ち運ぶ必要のある近距離無線機 2 台のセットです。BabyPhone.online は別の道を選びます。お手持ちの端末が、ブラウザのままカメラとモニターになります。ここで当然の疑問が生まれます — インターネット経由なら、ほかに誰が見られるのか？",
  "stepsH": "2 台の端末をベビーモニターにする 4 ステップ",
  "stepsP": "専用機器は不要です。最新のブラウザが動くスマートフォン、タブレット、ノート PC があれば十分です。",
  "steps": [
    "赤ちゃんのそばに置きたい端末でサイトを開きます。",
    "ブラウザがカメラとマイクの許可を求めます。許可しなければ、サイトはアクセスできません。",
    "QR コードで 2 台目の端末を同じセッションに接続します。",
    "2 つのブラウザが映像と音声のために、直接のリアルタイム接続を確立します。"
  ],
  "flowH": "ライブ映像は、ふつうの無防備な動画として送られるわけではありません",
  "flowP": "BabyPhone.online は WebRTC を使います。リアルタイムの音声・映像のために作られたブラウザ技術で、ビデオ通話に使われるものと同じ種類です。",
  "flowBaby": "赤ちゃん側の端末",
  "flowBabySub": "カメラ + マイク",
  "flowLink": "WebRTC",
  "flowLinkSub": "暗号化されたメディア接続",
  "flowParent": "保護者側の端末",
  "flowParentSub": "ライブモニター",
  "flowNote": "ネットワークの状況に応じて、WebRTC は 2 台を直接つなぐか、直接の経路がふさがれている場合は暗号化された通信を中継（TURN）サーバー経由で通します。",
  "layersH": "4 つの保護のしくみを、やさしく解説",
  "layers": [
    {"n": "1. HTTPS がサイトへの接続を守る",
     "d": "ブラウザは HTTPS で BabyPhone.online に接続します。これにより、同じネットワーク上の他者がページを読み取ったり、途中で書き換えたりしにくくなります。"},
    {"n": "2. WebRTC がライブ映像と音声を守る",
     "d": "WebRTC はリアルタイムメディアに安全な転送方式を使うため、ストリームが読み取れる無防備なデータとしてインターネットを流れることはありません。"},
    {"n": "3. カメラとマイクの許可はあなたが与える",
     "d": "サイトが黙ってカメラを起動することはできません。ブラウザが独自の確認を表示し、その許可は後から取り消せます。"},
    {"n": "4. QR コードが正しいセッションにつなぐ",
     "d": "読み取りなら入力ミスがなく、読み取った端末は使い捨ての鍵を受け取ります。コードを手入力した相手は、赤ちゃん側の端末の画面で承認される必要があります。"}
  ],
  "honestH": "「暗号化」とは実際どういう意味でしょうか",
  "honestP": "暗号化は重要ですが、本当の安全は鍵アイコン 1 つでは語れません。そこで、この技術にできること — そしてできないことを説明します。",
  "doesH": "WebRTC ができること",
  "does": [
    "ライブ映像と音声を送信中に暗号化します。",
    "ネットワークが許す限り、端末どうしを直接つなぎます。",
    "直接接続できないときは、暗号化されたメディアを中継経由で通します。"
  ],
  "youH": "あなた自身にお願いしたいこと",
  "you": [
    "QR コードを共有しないでください。有効なペアリングコードを見た人が、セッションへの参加を試みる可能性があります。",
    "端末をロックしてください。ロックされていないスマートフォンは、インターネット接続そのものより大きなリスクです。",
    "ブラウザを最新に保ってください。iOS、Android、ブラウザのセキュリティ更新は引き続き重要です。"
  ],
  "noticeLead": "知っておきたいこと：",
  "notice": "「暗号化」されているからといって、すべてのアプリが同じセキュリティ設計だとは限りません。WhatsApp は独自のエンドツーエンド方式と本人確認用の鍵を持っています。BabyPhone.online は、ブラウザのライブメディアに WebRTC 内蔵のセキュリティを使います。無防備な音声や映像をインターネットに流さないという目的は近いものの、構造は異なります。他社の主張を借りるより、そう率直にお伝えします。",
  "designH": "ベビーモニターは、ご家族について知ることが少ないほどよい",
  "designP": "それが BabyPhone.online の考え方です。手順は最小限、端末への不要なアクセスはなし、アカウントなし、広告なし、追跡なし。ご自身でペアリングした 2 台のあいだに、一時的なライブ接続があるだけです。録画も行わず、サーバーがのぞき見ることもありません。",
  "faqH": "安全について、手短に",
  "faq": [
    {"n": "誰かが勝手にカメラを起動できますか？",
     "d": "ブラウザのカメラ許可なしにはできません。さらにライブセッションへの参加には正しいペアリングが必要で、2 人目の視聴者は赤ちゃん側の端末の画面で承認される必要があります。有効な QR コードやルームコードを公開しないでください。"},
    {"n": "BabyPhone.online は途中で映像を見られますか？",
     "d": "WebRTC は送信中のライブメディアを暗号化します。ネットワークが直接経路をふさいでいて中継サーバーが必要な場合も、保護されたメディアを通すだけで、内容を見ることも聞くこともできません。"},
    {"n": "これは WhatsApp と同じですか？",
     "d": "文字どおり同じではありません。WhatsApp は本人確認の鍵を伴う独自のエンドツーエンド方式、BabyPhone.online はブラウザでの安全なリアルタイムメディアに WebRTC を使います。目的は近くても、技術的な構造は同じではありません。"},
    {"n": "できるだけ安全にするために、自分では何ができますか？",
     "d": "端末とブラウザを最新に保ち、ルームコードと QR は人に見せず、画面ロックを有効にし、使い終わったらセッションを閉じ、BabyPhone.online は公式の HTTPS アドレスからのみ開いてください。"}
  ],
  "ctaH": "試してみませんか？",
  "ctaP": "端末 2 台、インストール不要、アカウント不要。両方でサイトを開いてペアリングするだけです。",
  "ctaBtn": "BabyPhone.online を開く",
  "toBlog": "詳しいガイドを読む：BabyPhone.online にできること →",
  "backToApp": "← アプリに戻る",
}

T['ko'] = {
  "title": "베이비 모니터는 어떻게 보호되나요? | BabyPhone.online",
  "desc": "BabyPhone.online의 작동 방식과, 기기 간 실시간 영상·음성이 최신 브라우저 기술과 WebRTC로 어떻게 보호되는지 설명합니다.",
  "kicker": "보안 및 개인정보",
  "h1": "BabyPhone.online의 작동 방식 — 그리고 연결이 사적으로 유지되는 이유",
  "lede": "BabyPhone.online은 이미 갖고 계신 기기 두 대를 베이비 모니터로 바꿔 줍니다. 한 대는 아기 곁에, 다른 한 대는 곁에 두세요. 아래에서는 연결이 어떻게 이뤄지는지, 그리고 최신 브라우저 보안이 실시간 영상과 소리를 어떻게 보호하는지 어려운 용어 없이 설명합니다.",
  "readTime": "5분 분량",
  "updated": "2026년 8월 업데이트",
  "cardH": "개인정보 보호는 설계에서 시작됩니다",
  "cardP": "목표는 단순합니다. 실시간 세션에는 직접 연결하신 두 기기만 참여합니다.",
  "cardList": [
    "카메라와 마이크 권한은 브라우저가 직접 묻습니다.",
    "WebRTC가 전송 중 실시간 영상과 소리를 암호화합니다.",
    "QR 코드로 연결하면 긴 코드를 옮겨 적을 필요가 없습니다."
  ],
  "introP": "전통적인 베이비 모니터는 구입하고 충전해 들고 다녀야 하는 근거리 무전기 두 대입니다. BabyPhone.online은 다른 길을 택했습니다. 브라우저에서 바로, 내 기기가 카메라이자 모니터가 됩니다. 그러면 당연한 질문이 생깁니다. 인터넷을 거친다면 다른 누군가도 볼 수 있을까요?",
  "stepsH": "네 단계로 기기 두 대를 베이비 모니터로",
  "stepsP": "전용 장비는 필요 없습니다. 최신 브라우저가 있는 휴대폰, 태블릿, 노트북이면 충분합니다.",
  "steps": [
    "아기 곁에 둘 기기에서 웹사이트를 엽니다.",
    "브라우저가 카메라와 마이크 권한을 묻습니다. 허용하지 않으면 사이트는 접근할 수 없습니다.",
    "QR 코드로 두 번째 기기를 같은 세션에 연결합니다.",
    "두 브라우저가 영상과 소리를 위한 직접 실시간 연결을 만듭니다."
  ],
  "flowH": "실시간 화면은 평범한, 보호되지 않은 영상으로 전송되지 않습니다",
  "flowP": "BabyPhone.online은 WebRTC를 사용합니다. 실시간 음성·영상을 위해 만들어진 브라우저 기술로, 영상 통화에 쓰이는 것과 같은 종류입니다.",
  "flowBaby": "아기 쪽 기기",
  "flowBabySub": "카메라 + 마이크",
  "flowLink": "WebRTC",
  "flowLinkSub": "암호화된 미디어 연결",
  "flowParent": "부모 쪽 기기",
  "flowParentSub": "실시간 모니터",
  "flowNote": "네트워크 상황에 따라 WebRTC는 두 기기를 직접 연결하거나, 직접 경로가 막혀 있으면 암호화된 트래픽을 중계(TURN) 서버로 전달합니다.",
  "layersH": "네 가지 보호 장치, 쉽게 설명하면",
  "layers": [
    {"n": "1. HTTPS가 사이트 연결을 보호합니다",
     "d": "브라우저는 HTTPS로 BabyPhone.online에 접속합니다. 덕분에 같은 네트워크의 다른 사람이 페이지를 엿보거나 도중에 바꾸기 어렵습니다."},
    {"n": "2. WebRTC가 실시간 영상과 소리를 보호합니다",
     "d": "WebRTC는 실시간 미디어에 안전한 전송 방식을 사용하므로, 스트림이 읽을 수 있는 보호되지 않은 데이터로 인터넷을 오가지 않습니다."},
    {"n": "3. 카메라와 마이크 권한은 사용자가 줍니다",
     "d": "사이트가 몰래 카메라를 켤 수는 없습니다. 브라우저가 자체 확인 창을 보여 주며, 그 권한은 나중에 회수할 수 있습니다."},
    {"n": "4. QR 코드가 올바른 세션에 연결합니다",
     "d": "스캔하면 입력 실수가 없고, 스캔한 기기는 일회용 키를 받습니다. 코드를 직접 입력한 사람은 아기 쪽 기기 화면에서 승인을 받아야 합니다."}
  ],
  "honestH": "‘암호화’란 실제로 무슨 뜻일까요?",
  "honestP": "암호화는 중요하지만, 진짜 안전은 자물쇠 아이콘 하나로 설명되지 않습니다. 그래서 이 기술이 하는 일과 하지 않는 일을 밝힙니다.",
  "doesH": "WebRTC가 하는 일",
  "does": [
    "전송 중 실시간 영상과 소리를 암호화합니다.",
    "네트워크가 허용하는 한 기기를 직접 연결합니다.",
    "직접 연결이 불가능하면 암호화된 미디어를 중계로 전달합니다."
  ],
  "youH": "함께 해 주셔야 할 일",
  "you": [
    "QR 코드를 공유하지 마세요. 활성화된 연결 코드를 본 사람이 세션 참여를 시도할 수 있습니다.",
    "기기를 잠가 두세요. 잠기지 않은 휴대폰이 인터넷 연결 자체보다 더 큰 위험입니다.",
    "브라우저를 최신으로 유지하세요. iOS, Android, 브라우저의 보안 업데이트는 여전히 중요합니다."
  ],
  "noticeLead": "알아 두면 좋은 점:",
  "notice": " ‘암호화’가 곧 모든 앱이 같은 보안 구조를 쓴다는 뜻은 아닙니다. WhatsApp은 신원 키를 사용하는 자체 종단 간 프로토콜을 갖고 있습니다. BabyPhone.online은 브라우저의 실시간 미디어에 WebRTC에 내장된 보안을 사용합니다. 보호되지 않은 음성이나 영상을 인터넷에 보내지 않는다는 목표는 비슷하지만 구조는 다릅니다. 남의 주장을 빌리기보다 이 점을 분명히 말씀드립니다.",
  "designH": "베이비 모니터는 가족에 대해 가능한 한 적게 알아야 합니다",
  "designP": "그것이 BabyPhone.online의 원칙입니다. 단계는 최소한으로, 기기에 대한 불필요한 접근은 없이, 계정도 광고도 추적도 없이, 직접 연결하신 두 기기 사이의 일시적인 실시간 연결만 있습니다. 아무것도 녹화하지 않으며 어떤 서버도 들여다보지 않습니다.",
  "faqH": "짧게 보는 보안",
  "faq": [
    {"n": "누군가 그냥 제 카메라를 켤 수 있나요?",
     "d": "브라우저의 카메라 권한 없이는 불가능합니다. 또한 실시간 세션에 들어오려면 올바른 연결이 필요하고, 두 번째 시청자는 아기 쪽 기기 화면에서 승인을 받아야 합니다. 그러니 활성화된 QR 코드나 방 코드를 공개적으로 공유하지 마세요."},
    {"n": "BabyPhone.online이 전송 중인 영상을 볼 수 있나요?",
     "d": "WebRTC는 전송 중 실시간 미디어를 암호화합니다. 네트워크가 직접 경로를 막아 중계 서버가 필요할 때에도, 보호된 미디어를 전달할 뿐 내용을 보거나 들을 수는 없습니다."},
    {"n": "WhatsApp과 같은 건가요?",
     "d": "말 그대로 같지는 않습니다. WhatsApp은 신원 키를 쓰는 자체 종단 간 프로토콜을, BabyPhone.online은 브라우저의 안전한 실시간 미디어를 위해 WebRTC를 사용합니다. 목적은 비슷해도 기술 구조는 다릅니다."},
    {"n": "가장 안전하게 쓰려면 무엇을 하면 되나요?",
     "d": "최신 기기와 브라우저를 쓰고, 방 코드와 QR은 비공개로 두고, 화면 잠금을 켜고, 사용을 마치면 세션을 닫고, BabyPhone.online은 공식 HTTPS 주소로만 여세요."}
  ],
  "ctaH": "한번 해 보시겠어요?",
  "ctaP": "기기 두 대면 됩니다. 설치도 계정도 필요 없습니다. 두 기기에서 사이트를 열고 연결하세요.",
  "ctaBtn": "BabyPhone.online 열기",
  "toBlog": "전체 안내 보기: BabyPhone.online이 할 수 있는 모든 것 →",
  "backToApp": "← 앱으로 돌아가기",
}

T['vi'] = {
  "title": "Máy theo dõi em bé của bạn được bảo vệ thế nào? | BabyPhone.online",
  "desc": "Cách BabyPhone.online hoạt động và cách hình ảnh, âm thanh trực tiếp giữa các thiết bị được bảo vệ bằng công nghệ trình duyệt hiện đại và WebRTC.",
  "kicker": "BẢO MẬT & QUYỀN RIÊNG TƯ",
  "h1": "BabyPhone.online hoạt động thế nào — và vì sao kết nối của bạn vẫn riêng tư",
  "lede": "BabyPhone.online biến hai thiết bị bạn đã có thành máy theo dõi em bé. Một chiếc ở cạnh bé, chiếc kia theo bạn. Dưới đây là cách kết nối được thiết lập và cách bảo mật trình duyệt hiện đại bảo vệ hình ảnh cùng âm thanh trực tiếp — bằng ngôn ngữ dễ hiểu, không thuật ngữ rắc rối.",
  "readTime": "Đọc 5 phút",
  "updated": "Cập nhật tháng 8 năm 2026",
  "cardH": "Quyền riêng tư bắt đầu từ thiết kế",
  "cardP": "Mục tiêu rất đơn giản: chỉ hai thiết bị do chính bạn ghép đôi mới tham gia phiên trực tiếp.",
  "cardList": [
    "Chính trình duyệt hỏi bạn quyền dùng camera và micrô.",
    "WebRTC mã hóa hình ảnh và âm thanh trực tiếp trên đường truyền.",
    "Ghép đôi bằng mã QR giúp bạn khỏi phải gõ lại những mã dài."
  ],
  "introP": "Máy theo dõi truyền thống là một cặp bộ đàm tầm ngắn phải mua, phải sạc và phải mang theo. BabyPhone.online chọn hướng khác: chính thiết bị của bạn trở thành camera và màn hình theo dõi, ngay trong trình duyệt. Từ đó nảy ra một câu hỏi hợp lý — nếu chạy qua Internet thì còn ai có thể xem?",
  "stepsH": "Từ hai thiết bị thành máy theo dõi trong bốn bước",
  "stepsP": "Không cần phần cứng chuyên dụng. Một chiếc điện thoại, máy tính bảng hay laptop với trình duyệt đời mới là đủ.",
  "steps": [
    "Mở trang web trên thiết bị bạn muốn đặt cạnh bé.",
    "Trình duyệt sẽ hỏi quyền dùng camera và micrô. Không có sự cho phép của bạn, trang web không truy cập được.",
    "Dùng mã QR để kết nối thiết bị thứ hai vào cùng phiên.",
    "Hai trình duyệt tạo một kết nối trực tiếp, theo thời gian thực, cho hình và tiếng."
  ],
  "flowH": "Hình ảnh trực tiếp của bạn không được gửi đi như một video thông thường, không được bảo vệ",
  "flowP": "BabyPhone.online dùng WebRTC: công nghệ trình duyệt sinh ra cho âm thanh và video thời gian thực — cùng loại mà trình duyệt dùng cho cuộc gọi video.",
  "flowBaby": "Thiết bị ở chỗ bé",
  "flowBabySub": "camera + micrô",
  "flowLink": "WebRTC",
  "flowLinkSub": "kết nối media được mã hóa",
  "flowParent": "Thiết bị của bố mẹ",
  "flowParentSub": "màn hình trực tiếp",
  "flowNote": "Tùy mạng, WebRTC kết nối trực tiếp hai thiết bị, hoặc chuyển dữ liệu đã mã hóa qua máy chủ trung chuyển (TURN) khi đường trực tiếp bị chặn.",
  "layersH": "Bốn lớp bảo vệ, giải thích đơn giản",
  "layers": [
    {"n": "1. HTTPS bảo vệ kết nối tới trang web",
     "d": "Trình duyệt truy cập BabyPhone.online qua HTTPS. Điều này giúp ngăn người khác trên mạng đọc lén hoặc sửa trang giữa đường."},
    {"n": "2. WebRTC bảo vệ hình ảnh và âm thanh trực tiếp",
     "d": "WebRTC dùng cơ chế truyền an toàn cho media thời gian thực, nên luồng dữ liệu không đi qua Internet dưới dạng dữ liệu đọc được, không được bảo vệ."},
    {"n": "3. Bạn là người cấp quyền camera và micrô",
     "d": "Trang web không thể lặng lẽ bật camera. Trình duyệt hiển thị hộp thoại xin phép của riêng nó, và bạn có thể thu hồi quyền đó sau."},
    {"n": "4. Mã QR nối đúng phiên",
     "d": "Quét mã loại bỏ lỗi gõ nhầm, và thiết bị quét nhận một khóa dùng một lần. Ai nhập mã bằng tay vẫn phải được phê duyệt ngay trên màn hình thiết bị ở chỗ bé."}
  ],
  "honestH": "«Được mã hóa» thực ra nghĩa là gì?",
  "honestP": "Mã hóa rất quan trọng, nhưng an toàn thật sự không chỉ là một biểu tượng ổ khóa. Vậy nên đây là những gì công nghệ này làm — và không làm.",
  "doesH": "Những gì WebRTC làm được",
  "does": [
    "Mã hóa hình ảnh và âm thanh trực tiếp trên đường truyền.",
    "Kết nối trực tiếp hai thiết bị bất cứ khi nào mạng cho phép.",
    "Chuyển media đã mã hóa qua máy chủ trung chuyển khi không thể kết nối trực tiếp."
  ],
  "youH": "Những gì bạn cũng nên làm",
  "you": [
    "Đừng chia sẻ mã QR. Ai nhìn thấy mã ghép đôi đang hoạt động đều có thể thử tham gia phiên đó.",
    "Hãy khóa thiết bị. Một chiếc điện thoại không khóa còn rủi ro hơn cả đường truyền Internet.",
    "Giữ trình duyệt luôn mới. Các bản cập nhật bảo mật cho iOS, Android và trình duyệt vẫn rất quan trọng."
  ],
  "noticeLead": "Điều đáng biết:",
  "notice": " «được mã hóa» không tự động có nghĩa mọi ứng dụng đều dùng cùng một mô hình bảo mật. WhatsApp có giao thức đầu-cuối riêng với khóa danh tính. BabyPhone.online dùng phần bảo mật vốn có trong WebRTC cho media trực tiếp trên trình duyệt. Mục tiêu — không bao giờ gửi âm thanh hay hình ảnh không được bảo vệ qua Internet — là tương đương, nhưng kiến trúc thì khác. Chúng tôi thà nói thẳng điều đó còn hơn mượn tuyên bố của người khác.",
  "designH": "Máy theo dõi em bé nên biết càng ít càng tốt về gia đình bạn",
  "designP": "Đó là nguyên tắc của BabyPhone.online: càng ít bước càng tốt, không truy cập thừa vào thiết bị, không tài khoản, không quảng cáo, không theo dõi, và chỉ một kết nối tạm thời giữa hai thiết bị do chính bạn ghép đôi. Không có gì được ghi lại và không máy chủ nào xem cùng.",
  "faqH": "Bảo mật, nói ngắn gọn",
  "faq": [
    {"n": "Người khác có thể bật camera của tôi không?",
     "d": "Không, nếu chưa được bạn cấp quyền camera trong trình duyệt. Ngoài ra, muốn vào một phiên trực tiếp thì phải ghép đôi đúng, và người xem thứ hai còn phải được phê duyệt trên màn hình thiết bị ở chỗ bé. Vì vậy đừng bao giờ công khai mã QR hay mã phòng đang hoạt động."},
    {"n": "BabyPhone.online có xem được video của tôi trên đường truyền không?",
     "d": "WebRTC mã hóa media trực tiếp khi truyền đi. Khi cần máy chủ trung chuyển vì mạng chặn đường trực tiếp, máy chủ đó chỉ chuyển tiếp media đã được bảo vệ — nó không thể xem hay nghe."},
    {"n": "Cái này có giống WhatsApp không?",
     "d": "Không hẳn. WhatsApp dùng giao thức đầu-cuối riêng với khóa danh tính; BabyPhone.online dùng WebRTC cho media thời gian thực an toàn trên trình duyệt. Mục đích tương đương, kiến trúc kỹ thuật thì không."},
    {"n": "Tôi có thể làm gì để an toàn nhất?",
     "d": "Dùng thiết bị và trình duyệt còn được cập nhật, giữ kín mã phòng và mã QR, bật khóa màn hình, đóng phiên khi dùng xong, và chỉ mở BabyPhone.online qua địa chỉ HTTPS chính thức."}
  ],
  "ctaH": "Muốn thử chưa?",
  "ctaP": "Hai thiết bị, không cài đặt, không tài khoản. Mở trang web trên cả hai rồi ghép đôi.",
  "ctaBtn": "Mở BabyPhone.online",
  "toBlog": "Đọc hướng dẫn đầy đủ: mọi thứ BabyPhone.online làm được →",
  "backToApp": "← Quay lại ứng dụng",
}
